// Code generated by ent, DO NOT EDIT.

package lastreadnotification

import (
	"entgo.io/ent/dialect/sql"
	"github.com/makesalekz/utils/v2/struc"
)

const (
	// Label holds the string label denoting the lastreadnotification type in the database.
	Label = "last_read_notification"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldLastReadID holds the string denoting the last_read_id field in the database.
	FieldLastReadID = "last_read_id"
	// Table holds the table name of the lastreadnotification in the database.
	Table = "last_read_notifications"
)

// Columns holds all SQL columns for lastreadnotification fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldType,
	FieldLastReadID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultType holds the default value on creation for the "type" field.
	DefaultType struc.NotificationType
)

// OrderOption defines the ordering options for the LastReadNotification queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByLastReadID orders the results by the last_read_id field.
func ByLastReadID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastReadID, opts...).ToFunc()
}
