stages:
  - build
  - deploy

include:
  - project: 'deploy/common-cicd'
    file: '/common-project.yml'
    ref: 'main'

docker-build:
  rules:
    - if: '$ENVIRONMENT_CODE == "dev"'
      variables:
        DOCKER_RUN_ARGS: -p 8003:8000 --volume ./configs:/data/conf
    - if: '$ENVIRONMENT_CODE == "stage"'
      variables:
        DOCKER_RUN_ARGS: -p 8003:8000 --volume ./configs:/data/conf
  extends: .docker-service-build
  before_script:
    - !reference ['.before-script', 'before_script']
    - export GOOGLE_APPLICATION_CREDENTIALS_FILE=$(docker exec vault vault kv get -mount=secret -field=data app/notifications/gserviceaccount)
    - export FIREBASE_CONFIG_FILE=$(docker exec vault vault kv get -mount=secret -field=data app/notifications/firebase)
    - export JWT_SECRET=$(docker exec vault vault kv get -mount=secret -field=data app/global/jwt)
  after_script:
    - echo ${ENVIRONMENT_CODE} http://${CI_PROJECT_NAME}-${ENVIRONMENT_CODE}
