stages:
  - build
  - deploy

include:
  - project: 'deploy/common-cicd'
    file: '/common-project.yml'
    ref: 'main'

docker-build:
  tags:
    - ${RUNNER_TAG}
  stage: build
  variables:
    HTTP_PORT: 8003
    GRPC_PORT: 9003
    PG_ARGS: -e PGDATA=/var/lib/postgresql/data/pgdata -e POSTGRES_DB=api -e POSTGRES_USER=me -e POSTGRES_PASSWORD=password
    DOCKER_RUN_ARGS: -e GOOGLE_APPLICATION_CREDENTIALS_FILE -e FIREBASE_CONFIG_FILE -e JWT_SECRET
  script:
    - export GOOGLE_APPLICATION_CREDENTIALS_FILE=$(docker exec vault vault kv get -mount=secret -field=data app/notifications/gserviceaccount)
    - export FIREBASE_CONFIG_FILE=$(docker exec vault vault kv get -mount=secret -field=data app/notifications/firebase)
    - export JWT_SECRET=$(docker exec vault vault kv get -mount=secret -field=data app/global/jwt)
    - echo "build docker $DOCKER_RUN_ARGS"
    - docker build ${DOCKER_BUILD_ARGS} -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} .
    - tag_sha_latest_and_push
    - docker stop ${CI_PROJECT_NAME}-${ENVIRONMENT_CODE} || true
    - docker stop ${CI_PROJECT_NAME}-${ENVIRONMENT_CODE}-db || true
    - mkdir -p .docker/data
    - chmod 777 .docker/data
    - docker run -d --rm --hostname ${CI_PROJECT_NAME}_db ${PG_ARGS} --network ${ENVIRONMENT_CODE} -p 5432:5432 --volume ${CI_PROJECT_DIR}/.docker/data:/var/lib/postgresql/data --name ${CI_PROJECT_NAME}-${ENVIRONMENT_CODE}-db postgres:latest
    - docker run -d --rm --hostname ${CI_PROJECT_NAME} ${DOCKER_RUN_ARGS} --network ${ENVIRONMENT_CODE} -p ${HTTP_PORT}:8000 -p ${GRPC_PORT}:9000 --volume ./configs:/data/conf --name ${CI_PROJECT_NAME}-${ENVIRONMENT_CODE} ${CI_REGISTRY_IMAGE}:${ENVIRONMENT_CODE}
  after_script:
    - echo ${ENVIRONMENT_CODE} http://${CI_PROJECT_NAME}-${ENVIRONMENT_CODE}
