// Code generated by MockGen. DO NOT EDIT.
// Source: internal/data/dialer/chats.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIChatsRemote is a mock of IChatsRemote interface.
type MockIChatsRemote struct {
	ctrl     *gomock.Controller
	recorder *MockIChatsRemoteMockRecorder
}

// MockIChatsRemoteMockRecorder is the mock recorder for MockIChatsRemote.
type MockIChatsRemoteMockRecorder struct {
	mock *MockIChatsRemote
}

// NewMockIChatsRemote creates a new mock instance.
func NewMockIChatsRemote(ctrl *gomock.Controller) *MockIChatsRemote {
	mock := &MockIChatsRemote{ctrl: ctrl}
	mock.recorder = &MockIChatsRemoteMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIChatsRemote) EXPECT() *MockIChatsRemoteMockRecorder {
	return m.recorder
}

// CountUnreadMessages mocks base method.
func (m *MockIChatsRemote) CountUnreadMessages(ctx context.Context, userIDs []int64) (map[int64]int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUnreadMessages", ctx, userIDs)
	ret0, _ := ret[0].(map[int64]int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUnreadMessages indicates an expected call of CountUnreadMessages.
func (mr *MockIChatsRemoteMockRecorder) CountUnreadMessages(ctx, userIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUnreadMessages", reflect.TypeOf((*MockIChatsRemote)(nil).CountUnreadMessages), ctx, userIDs)
}
