// Code generated by MockGen. DO NOT EDIT.
// Source: internal/data/devices.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	ent "gitlab.calendaria.team/services/notifications/ent"
	data "gitlab.calendaria.team/services/notifications/internal/data"
)

// MockDevicesRepo is a mock of DevicesRepo interface.
type MockDevicesRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDevicesRepoMockRecorder
}

// MockDevicesRepoMockRecorder is the mock recorder for MockDevicesRepo.
type MockDevicesRepoMockRecorder struct {
	mock *MockDevicesRepo
}

// NewMockDevicesRepo creates a new mock instance.
func NewMockDevicesRepo(ctrl *gomock.Controller) *MockDevicesRepo {
	mock := &MockDevicesRepo{ctrl: ctrl}
	mock.recorder = &MockDevicesRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDevicesRepo) EXPECT() *MockDevicesRepoMockRecorder {
	return m.recorder
}

// CreateDevice mocks base method.
func (m *MockDevicesRepo) CreateDevice(ctx context.Context, deviceDto data.DeviceDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDevice", ctx, deviceDto)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDevice indicates an expected call of CreateDevice.
func (mr *MockDevicesRepoMockRecorder) CreateDevice(ctx, deviceDto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDevice", reflect.TypeOf((*MockDevicesRepo)(nil).CreateDevice), ctx, deviceDto)
}

// DeleteDevice mocks base method.
func (m *MockDevicesRepo) DeleteDevice(ctx context.Context, deviceKey data.DeviceKey) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDevice", ctx, deviceKey)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteDevice indicates an expected call of DeleteDevice.
func (mr *MockDevicesRepoMockRecorder) DeleteDevice(ctx, deviceKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDevice", reflect.TypeOf((*MockDevicesRepo)(nil).DeleteDevice), ctx, deviceKey)
}

// DeleteDevicesByTokens mocks base method.
func (m *MockDevicesRepo) DeleteDevicesByTokens(ctx context.Context, tokens []string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDevicesByTokens", ctx, tokens)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteDevicesByTokens indicates an expected call of DeleteDevicesByTokens.
func (mr *MockDevicesRepoMockRecorder) DeleteDevicesByTokens(ctx, tokens interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDevicesByTokens", reflect.TypeOf((*MockDevicesRepo)(nil).DeleteDevicesByTokens), ctx, tokens)
}

// DeleteUserDevicesTokens mocks base method.
func (m *MockDevicesRepo) DeleteUserDevicesTokens(ctx context.Context, userID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserDevicesTokens", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteUserDevicesTokens indicates an expected call of DeleteUserDevicesTokens.
func (mr *MockDevicesRepoMockRecorder) DeleteUserDevicesTokens(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserDevicesTokens", reflect.TypeOf((*MockDevicesRepo)(nil).DeleteUserDevicesTokens), ctx, userID)
}

// GetDevice mocks base method.
func (m *MockDevicesRepo) GetDevice(ctx context.Context, deviceKey data.DeviceKey) (*ent.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDevice", ctx, deviceKey)
	ret0, _ := ret[0].(*ent.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDevice indicates an expected call of GetDevice.
func (mr *MockDevicesRepoMockRecorder) GetDevice(ctx, deviceKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDevice", reflect.TypeOf((*MockDevicesRepo)(nil).GetDevice), ctx, deviceKey)
}

// GetDevicesForUser mocks base method.
func (m *MockDevicesRepo) GetDevicesForUser(ctx context.Context, userID int64) ([]*ent.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDevicesForUser", ctx, userID)
	ret0, _ := ret[0].([]*ent.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDevicesForUser indicates an expected call of GetDevicesForUser.
func (mr *MockDevicesRepoMockRecorder) GetDevicesForUser(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDevicesForUser", reflect.TypeOf((*MockDevicesRepo)(nil).GetDevicesForUser), ctx, userID)
}

// GetDevicesForUsers mocks base method.
func (m *MockDevicesRepo) GetDevicesForUsers(ctx context.Context, usersIDs []int64) ([]*ent.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDevicesForUsers", ctx, usersIDs)
	ret0, _ := ret[0].([]*ent.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDevicesForUsers indicates an expected call of GetDevicesForUsers.
func (mr *MockDevicesRepoMockRecorder) GetDevicesForUsers(ctx, usersIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDevicesForUsers", reflect.TypeOf((*MockDevicesRepo)(nil).GetDevicesForUsers), ctx, usersIDs)
}
