// Code generated by MockGen. DO NOT EDIT.
// Source: internal/data/dialer/events.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIEventsRemote is a mock of IEventsRemote interface.
type MockIEventsRemote struct {
	ctrl     *gomock.Controller
	recorder *MockIEventsRemoteMockRecorder
}

// MockIEventsRemoteMockRecorder is the mock recorder for MockIEventsRemote.
type MockIEventsRemoteMockRecorder struct {
	mock *MockIEventsRemote
}

// NewMockIEventsRemote creates a new mock instance.
func NewMockIEventsRemote(ctrl *gomock.Controller) *MockIEventsRemote {
	mock := &MockIEventsRemote{ctrl: ctrl}
	mock.recorder = &MockIEventsRemoteMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIEventsRemote) EXPECT() *MockIEventsRemoteMockRecorder {
	return m.recorder
}

// GetEventsCount mocks base method.
func (m *MockIEventsRemote) GetEventsCount(ctx context.Context, userIDs []int64) (map[int64]int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventsCount", ctx, userIDs)
	ret0, _ := ret[0].(map[int64]int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventsCount indicates an expected call of GetEventsCount.
func (mr *MockIEventsRemoteMockRecorder) GetEventsCount(ctx, userIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventsCount", reflect.TypeOf((*MockIEventsRemote)(nil).GetEventsCount), ctx, userIDs)
}
