// Code generated by MockGen. DO NOT EDIT.
// Source: internal/data/notifications.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	ent "gitlab.calendaria.team/services/notifications/ent"
	data "gitlab.calendaria.team/services/notifications/internal/data"
	utils_v1 "gitlab.calendaria.team/services/utils/api/utils/v1"
)

// MockNotificationsRepo is a mock of NotificationsRepo interface.
type MockNotificationsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationsRepoMockRecorder
}

// MockNotificationsRepoMockRecorder is the mock recorder for MockNotificationsRepo.
type MockNotificationsRepoMockRecorder struct {
	mock *MockNotificationsRepo
}

// NewMockNotificationsRepo creates a new mock instance.
func NewMockNotificationsRepo(ctrl *gomock.Controller) *MockNotificationsRepo {
	mock := &MockNotificationsRepo{ctrl: ctrl}
	mock.recorder = &MockNotificationsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationsRepo) EXPECT() *MockNotificationsRepoMockRecorder {
	return m.recorder
}

// CountNotifications mocks base method.
func (m *MockNotificationsRepo) CountNotifications(ctx context.Context, userID int64, notificationType string) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountNotifications", ctx, userID, notificationType)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountNotifications indicates an expected call of CountNotifications.
func (mr *MockNotificationsRepoMockRecorder) CountNotifications(ctx, userID, notificationType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountNotifications", reflect.TypeOf((*MockNotificationsRepo)(nil).CountNotifications), ctx, userID, notificationType)
}

// CountUnreadNotifications mocks base method.
func (m *MockNotificationsRepo) CountUnreadNotifications(ctx context.Context, userID int64) ([]data.Counter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUnreadNotifications", ctx, userID)
	ret0, _ := ret[0].([]data.Counter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUnreadNotifications indicates an expected call of CountUnreadNotifications.
func (mr *MockNotificationsRepoMockRecorder) CountUnreadNotifications(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUnreadNotifications", reflect.TypeOf((*MockNotificationsRepo)(nil).CountUnreadNotifications), ctx, userID)
}

// CountUnreadNotificationsByType mocks base method.
func (m *MockNotificationsRepo) CountUnreadNotificationsByType(ctx context.Context, userIDs []int64, notificationType string) (map[int64]int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUnreadNotificationsByType", ctx, userIDs, notificationType)
	ret0, _ := ret[0].(map[int64]int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUnreadNotificationsByType indicates an expected call of CountUnreadNotificationsByType.
func (mr *MockNotificationsRepoMockRecorder) CountUnreadNotificationsByType(ctx, userIDs, notificationType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUnreadNotificationsByType", reflect.TypeOf((*MockNotificationsRepo)(nil).CountUnreadNotificationsByType), ctx, userIDs, notificationType)
}

// CreateNotifications mocks base method.
func (m *MockNotificationsRepo) CreateNotifications(ctx context.Context, data []*data.NotificationDto) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNotifications", ctx, data)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNotifications indicates an expected call of CreateNotifications.
func (mr *MockNotificationsRepoMockRecorder) CreateNotifications(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNotifications", reflect.TypeOf((*MockNotificationsRepo)(nil).CreateNotifications), ctx, data)
}

// ListNotifications mocks base method.
func (m *MockNotificationsRepo) ListNotifications(ctx context.Context, filter *data.FilterNotificationsDto, paginate *utils_v1.PaginateRequest) ([]*ent.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNotifications", ctx, filter, paginate)
	ret0, _ := ret[0].([]*ent.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNotifications indicates an expected call of ListNotifications.
func (mr *MockNotificationsRepoMockRecorder) ListNotifications(ctx, filter, paginate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotifications", reflect.TypeOf((*MockNotificationsRepo)(nil).ListNotifications), ctx, filter, paginate)
}

// ReadNotification mocks base method.
func (m *MockNotificationsRepo) ReadNotification(ctx context.Context, readDto data.ReadNotificationDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadNotification", ctx, readDto)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReadNotification indicates an expected call of ReadNotification.
func (mr *MockNotificationsRepoMockRecorder) ReadNotification(ctx, readDto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadNotification", reflect.TypeOf((*MockNotificationsRepo)(nil).ReadNotification), ctx, readDto)
}
