// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: send/v1/sender.proto

package send_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Sender_SenderInfo_FullMethodName        = "/api.send.v1.Sender/SenderInfo"
	Sender_PersonalSmsSender_FullMethodName = "/api.send.v1.Sender/PersonalSmsSender"
)

// SenderClient is the client API for Sender service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SenderClient interface {
	SenderInfo(ctx context.Context, in *DummyRequest, opts ...grpc.CallOption) (*DummyReply, error)
	PersonalSmsSender(ctx context.Context, in *PersonalSmsSenderRequest, opts ...grpc.CallOption) (*PersonalSmsSenderReply, error)
}

type senderClient struct {
	cc grpc.ClientConnInterface
}

func NewSenderClient(cc grpc.ClientConnInterface) SenderClient {
	return &senderClient{cc}
}

func (c *senderClient) SenderInfo(ctx context.Context, in *DummyRequest, opts ...grpc.CallOption) (*DummyReply, error) {
	out := new(DummyReply)
	err := c.cc.Invoke(ctx, Sender_SenderInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *senderClient) PersonalSmsSender(ctx context.Context, in *PersonalSmsSenderRequest, opts ...grpc.CallOption) (*PersonalSmsSenderReply, error) {
	out := new(PersonalSmsSenderReply)
	err := c.cc.Invoke(ctx, Sender_PersonalSmsSender_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SenderServer is the server API for Sender service.
// All implementations must embed UnimplementedSenderServer
// for forward compatibility
type SenderServer interface {
	SenderInfo(context.Context, *DummyRequest) (*DummyReply, error)
	PersonalSmsSender(context.Context, *PersonalSmsSenderRequest) (*PersonalSmsSenderReply, error)
	mustEmbedUnimplementedSenderServer()
}

// UnimplementedSenderServer must be embedded to have forward compatible implementations.
type UnimplementedSenderServer struct {
}

func (UnimplementedSenderServer) SenderInfo(context.Context, *DummyRequest) (*DummyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SenderInfo not implemented")
}
func (UnimplementedSenderServer) PersonalSmsSender(context.Context, *PersonalSmsSenderRequest) (*PersonalSmsSenderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PersonalSmsSender not implemented")
}
func (UnimplementedSenderServer) mustEmbedUnimplementedSenderServer() {}

// UnsafeSenderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SenderServer will
// result in compilation errors.
type UnsafeSenderServer interface {
	mustEmbedUnimplementedSenderServer()
}

func RegisterSenderServer(s grpc.ServiceRegistrar, srv SenderServer) {
	s.RegisterService(&Sender_ServiceDesc, srv)
}

func _Sender_SenderInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DummyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SenderServer).SenderInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sender_SenderInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SenderServer).SenderInfo(ctx, req.(*DummyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sender_PersonalSmsSender_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PersonalSmsSenderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SenderServer).PersonalSmsSender(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sender_PersonalSmsSender_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SenderServer).PersonalSmsSender(ctx, req.(*PersonalSmsSenderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Sender_ServiceDesc is the grpc.ServiceDesc for Sender service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sender_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.send.v1.Sender",
	HandlerType: (*SenderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SenderInfo",
			Handler:    _Sender_SenderInfo_Handler,
		},
		{
			MethodName: "PersonalSmsSender",
			Handler:    _Sender_PersonalSmsSender_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "send/v1/sender.proto",
}
