syntax = "proto3";

package api.send.v1;

import "google/api/annotations.proto";
import "errors/errors.proto";

option go_package = "notifications/api/send/v1;send_v1";
option java_multiple_files = true;
option java_package = "api.send.v1";

service Sender {
	rpc CreateFcmDevice (FcmDeviceRequest) returns (EmptyReply) {
		option (google.api.http) = {
			post: "/v1/notifications/fcm/devices"
			body: "*"
		};
	};
	rpc DeleteFcmDevice (FcmDeviceRequest) returns (EmptyReply) {
		option (google.api.http) = {
			delete: "/v1/notifications/fcm/devices"
		};
	};
	rpc PersonalSmsSender (PersonalSmsSenderRequest) returns (EmptyReply);
}

message EmptyReply {}

message FcmDeviceRequest {
	string token = 1;
}

message PersonalSmsSenderRequest {
	string phone = 1;
	string message = 2;
}

enum ErrorReason {
  // Set default error code.
  option (errors.default_code) = 500;

  // Set the error code separately for an enumeration.
  INTERNAL = 0;
  GRPC_CONNECTION = 1;
  SERVICE_FAILED = 2;
  DATABASE_QUERY = 3;
  
  UNAUTHORIZED = 10 [(errors.code) = 401];
  FCM_FAILED = 11;
  SMS_FAILED = 12;
  
  DEVICE_NOT_FOUND = 20 [(errors.code) = 404];
  INVALID_REQUEST = 21 [(errors.code) = 400];
}