// Code generated by ent, DO NOT EDIT.

package notificationdata

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the notificationdata type in the database.
	Label = "notification_data"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldEvent holds the string denoting the event field in the database.
	FieldEvent = "event"
	// FieldMember holds the string denoting the member field in the database.
	FieldMember = "member"
	// FieldChat holds the string denoting the chat field in the database.
	FieldChat = "chat"
	// FieldMessage holds the string denoting the message field in the database.
	FieldMessage = "message"
	// FieldContact holds the string denoting the contact field in the database.
	FieldContact = "contact"
	// FieldTask holds the string denoting the task field in the database.
	FieldTask = "task"
	// FieldProject holds the string denoting the project field in the database.
	FieldProject = "project"
	// FieldUser holds the string denoting the user field in the database.
	FieldUser = "user"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldPluralCount holds the string denoting the plural_count field in the database.
	FieldPluralCount = "plural_count"
	// EdgeNotification holds the string denoting the notification edge name in mutations.
	EdgeNotification = "notification"
	// Table holds the table name of the notificationdata in the database.
	Table = "notification_data"
	// NotificationTable is the table that holds the notification relation/edge.
	NotificationTable = "notifications"
	// NotificationInverseTable is the table name for the Notification entity.
	// It exists in this package in order to avoid circular dependency with the "notification" package.
	NotificationInverseTable = "notifications"
	// NotificationColumn is the table column denoting the notification relation/edge.
	NotificationColumn = "notification_data_id"
)

// Columns holds all SQL columns for notificationdata fields.
var Columns = []string{
	FieldID,
	FieldType,
	FieldEvent,
	FieldMember,
	FieldChat,
	FieldMessage,
	FieldContact,
	FieldTask,
	FieldProject,
	FieldUser,
	FieldMetadata,
	FieldPluralCount,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the NotificationData queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByEvent orders the results by the event field.
func ByEvent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEvent, opts...).ToFunc()
}

// ByMember orders the results by the member field.
func ByMember(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMember, opts...).ToFunc()
}

// ByChat orders the results by the chat field.
func ByChat(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChat, opts...).ToFunc()
}

// ByMessage orders the results by the message field.
func ByMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMessage, opts...).ToFunc()
}

// ByContact orders the results by the contact field.
func ByContact(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContact, opts...).ToFunc()
}

// ByTask orders the results by the task field.
func ByTask(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTask, opts...).ToFunc()
}

// ByProject orders the results by the project field.
func ByProject(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProject, opts...).ToFunc()
}

// ByUser orders the results by the user field.
func ByUser(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUser, opts...).ToFunc()
}

// ByMetadata orders the results by the metadata field.
func ByMetadata(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetadata, opts...).ToFunc()
}

// ByPluralCount orders the results by the plural_count field.
func ByPluralCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPluralCount, opts...).ToFunc()
}

// ByNotificationField orders the results by notification field.
func ByNotificationField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNotificationStep(), sql.OrderByField(field, opts...))
	}
}
func newNotificationStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(NotificationInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, NotificationTable, NotificationColumn),
	)
}
