// Code generated by ent, DO NOT EDIT.

package notificationdata

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/makesalekz/notifications/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldLTE(FieldID, id))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldEQ(FieldType, v))
}

// Event applies equality check predicate on the "event" field. It's identical to EventEQ.
func Event(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldEQ(FieldEvent, v))
}

// Member applies equality check predicate on the "member" field. It's identical to MemberEQ.
func Member(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldEQ(FieldMember, v))
}

// Chat applies equality check predicate on the "chat" field. It's identical to ChatEQ.
func Chat(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldEQ(FieldChat, v))
}

// Message applies equality check predicate on the "message" field. It's identical to MessageEQ.
func Message(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldEQ(FieldMessage, v))
}

// Contact applies equality check predicate on the "contact" field. It's identical to ContactEQ.
func Contact(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldEQ(FieldContact, v))
}

// Task applies equality check predicate on the "task" field. It's identical to TaskEQ.
func Task(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldEQ(FieldTask, v))
}

// Project applies equality check predicate on the "project" field. It's identical to ProjectEQ.
func Project(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldEQ(FieldProject, v))
}

// TargetUserID applies equality check predicate on the "target_user_id" field. It's identical to TargetUserIDEQ.
func TargetUserID(v int64) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldEQ(FieldTargetUserID, v))
}

// Metadata applies equality check predicate on the "metadata" field. It's identical to MetadataEQ.
func Metadata(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldEQ(FieldMetadata, v))
}

// PluralCount applies equality check predicate on the "plural_count" field. It's identical to PluralCountEQ.
func PluralCount(v int64) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldEQ(FieldPluralCount, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldHasSuffix(FieldType, v))
}

// TypeIsNil applies the IsNil predicate on the "type" field.
func TypeIsNil() predicate.NotificationData {
	return predicate.NotificationData(sql.FieldIsNull(FieldType))
}

// TypeNotNil applies the NotNil predicate on the "type" field.
func TypeNotNil() predicate.NotificationData {
	return predicate.NotificationData(sql.FieldNotNull(FieldType))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldContainsFold(FieldType, v))
}

// EventEQ applies the EQ predicate on the "event" field.
func EventEQ(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldEQ(FieldEvent, v))
}

// EventNEQ applies the NEQ predicate on the "event" field.
func EventNEQ(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldNEQ(FieldEvent, v))
}

// EventIn applies the In predicate on the "event" field.
func EventIn(vs ...string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldIn(FieldEvent, vs...))
}

// EventNotIn applies the NotIn predicate on the "event" field.
func EventNotIn(vs ...string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldNotIn(FieldEvent, vs...))
}

// EventGT applies the GT predicate on the "event" field.
func EventGT(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldGT(FieldEvent, v))
}

// EventGTE applies the GTE predicate on the "event" field.
func EventGTE(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldGTE(FieldEvent, v))
}

// EventLT applies the LT predicate on the "event" field.
func EventLT(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldLT(FieldEvent, v))
}

// EventLTE applies the LTE predicate on the "event" field.
func EventLTE(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldLTE(FieldEvent, v))
}

// EventContains applies the Contains predicate on the "event" field.
func EventContains(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldContains(FieldEvent, v))
}

// EventHasPrefix applies the HasPrefix predicate on the "event" field.
func EventHasPrefix(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldHasPrefix(FieldEvent, v))
}

// EventHasSuffix applies the HasSuffix predicate on the "event" field.
func EventHasSuffix(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldHasSuffix(FieldEvent, v))
}

// EventIsNil applies the IsNil predicate on the "event" field.
func EventIsNil() predicate.NotificationData {
	return predicate.NotificationData(sql.FieldIsNull(FieldEvent))
}

// EventNotNil applies the NotNil predicate on the "event" field.
func EventNotNil() predicate.NotificationData {
	return predicate.NotificationData(sql.FieldNotNull(FieldEvent))
}

// EventEqualFold applies the EqualFold predicate on the "event" field.
func EventEqualFold(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldEqualFold(FieldEvent, v))
}

// EventContainsFold applies the ContainsFold predicate on the "event" field.
func EventContainsFold(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldContainsFold(FieldEvent, v))
}

// MemberEQ applies the EQ predicate on the "member" field.
func MemberEQ(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldEQ(FieldMember, v))
}

// MemberNEQ applies the NEQ predicate on the "member" field.
func MemberNEQ(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldNEQ(FieldMember, v))
}

// MemberIn applies the In predicate on the "member" field.
func MemberIn(vs ...string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldIn(FieldMember, vs...))
}

// MemberNotIn applies the NotIn predicate on the "member" field.
func MemberNotIn(vs ...string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldNotIn(FieldMember, vs...))
}

// MemberGT applies the GT predicate on the "member" field.
func MemberGT(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldGT(FieldMember, v))
}

// MemberGTE applies the GTE predicate on the "member" field.
func MemberGTE(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldGTE(FieldMember, v))
}

// MemberLT applies the LT predicate on the "member" field.
func MemberLT(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldLT(FieldMember, v))
}

// MemberLTE applies the LTE predicate on the "member" field.
func MemberLTE(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldLTE(FieldMember, v))
}

// MemberContains applies the Contains predicate on the "member" field.
func MemberContains(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldContains(FieldMember, v))
}

// MemberHasPrefix applies the HasPrefix predicate on the "member" field.
func MemberHasPrefix(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldHasPrefix(FieldMember, v))
}

// MemberHasSuffix applies the HasSuffix predicate on the "member" field.
func MemberHasSuffix(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldHasSuffix(FieldMember, v))
}

// MemberIsNil applies the IsNil predicate on the "member" field.
func MemberIsNil() predicate.NotificationData {
	return predicate.NotificationData(sql.FieldIsNull(FieldMember))
}

// MemberNotNil applies the NotNil predicate on the "member" field.
func MemberNotNil() predicate.NotificationData {
	return predicate.NotificationData(sql.FieldNotNull(FieldMember))
}

// MemberEqualFold applies the EqualFold predicate on the "member" field.
func MemberEqualFold(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldEqualFold(FieldMember, v))
}

// MemberContainsFold applies the ContainsFold predicate on the "member" field.
func MemberContainsFold(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldContainsFold(FieldMember, v))
}

// ChatEQ applies the EQ predicate on the "chat" field.
func ChatEQ(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldEQ(FieldChat, v))
}

// ChatNEQ applies the NEQ predicate on the "chat" field.
func ChatNEQ(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldNEQ(FieldChat, v))
}

// ChatIn applies the In predicate on the "chat" field.
func ChatIn(vs ...string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldIn(FieldChat, vs...))
}

// ChatNotIn applies the NotIn predicate on the "chat" field.
func ChatNotIn(vs ...string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldNotIn(FieldChat, vs...))
}

// ChatGT applies the GT predicate on the "chat" field.
func ChatGT(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldGT(FieldChat, v))
}

// ChatGTE applies the GTE predicate on the "chat" field.
func ChatGTE(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldGTE(FieldChat, v))
}

// ChatLT applies the LT predicate on the "chat" field.
func ChatLT(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldLT(FieldChat, v))
}

// ChatLTE applies the LTE predicate on the "chat" field.
func ChatLTE(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldLTE(FieldChat, v))
}

// ChatContains applies the Contains predicate on the "chat" field.
func ChatContains(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldContains(FieldChat, v))
}

// ChatHasPrefix applies the HasPrefix predicate on the "chat" field.
func ChatHasPrefix(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldHasPrefix(FieldChat, v))
}

// ChatHasSuffix applies the HasSuffix predicate on the "chat" field.
func ChatHasSuffix(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldHasSuffix(FieldChat, v))
}

// ChatIsNil applies the IsNil predicate on the "chat" field.
func ChatIsNil() predicate.NotificationData {
	return predicate.NotificationData(sql.FieldIsNull(FieldChat))
}

// ChatNotNil applies the NotNil predicate on the "chat" field.
func ChatNotNil() predicate.NotificationData {
	return predicate.NotificationData(sql.FieldNotNull(FieldChat))
}

// ChatEqualFold applies the EqualFold predicate on the "chat" field.
func ChatEqualFold(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldEqualFold(FieldChat, v))
}

// ChatContainsFold applies the ContainsFold predicate on the "chat" field.
func ChatContainsFold(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldContainsFold(FieldChat, v))
}

// MessageEQ applies the EQ predicate on the "message" field.
func MessageEQ(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldEQ(FieldMessage, v))
}

// MessageNEQ applies the NEQ predicate on the "message" field.
func MessageNEQ(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldNEQ(FieldMessage, v))
}

// MessageIn applies the In predicate on the "message" field.
func MessageIn(vs ...string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldIn(FieldMessage, vs...))
}

// MessageNotIn applies the NotIn predicate on the "message" field.
func MessageNotIn(vs ...string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldNotIn(FieldMessage, vs...))
}

// MessageGT applies the GT predicate on the "message" field.
func MessageGT(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldGT(FieldMessage, v))
}

// MessageGTE applies the GTE predicate on the "message" field.
func MessageGTE(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldGTE(FieldMessage, v))
}

// MessageLT applies the LT predicate on the "message" field.
func MessageLT(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldLT(FieldMessage, v))
}

// MessageLTE applies the LTE predicate on the "message" field.
func MessageLTE(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldLTE(FieldMessage, v))
}

// MessageContains applies the Contains predicate on the "message" field.
func MessageContains(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldContains(FieldMessage, v))
}

// MessageHasPrefix applies the HasPrefix predicate on the "message" field.
func MessageHasPrefix(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldHasPrefix(FieldMessage, v))
}

// MessageHasSuffix applies the HasSuffix predicate on the "message" field.
func MessageHasSuffix(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldHasSuffix(FieldMessage, v))
}

// MessageIsNil applies the IsNil predicate on the "message" field.
func MessageIsNil() predicate.NotificationData {
	return predicate.NotificationData(sql.FieldIsNull(FieldMessage))
}

// MessageNotNil applies the NotNil predicate on the "message" field.
func MessageNotNil() predicate.NotificationData {
	return predicate.NotificationData(sql.FieldNotNull(FieldMessage))
}

// MessageEqualFold applies the EqualFold predicate on the "message" field.
func MessageEqualFold(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldEqualFold(FieldMessage, v))
}

// MessageContainsFold applies the ContainsFold predicate on the "message" field.
func MessageContainsFold(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldContainsFold(FieldMessage, v))
}

// ContactEQ applies the EQ predicate on the "contact" field.
func ContactEQ(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldEQ(FieldContact, v))
}

// ContactNEQ applies the NEQ predicate on the "contact" field.
func ContactNEQ(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldNEQ(FieldContact, v))
}

// ContactIn applies the In predicate on the "contact" field.
func ContactIn(vs ...string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldIn(FieldContact, vs...))
}

// ContactNotIn applies the NotIn predicate on the "contact" field.
func ContactNotIn(vs ...string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldNotIn(FieldContact, vs...))
}

// ContactGT applies the GT predicate on the "contact" field.
func ContactGT(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldGT(FieldContact, v))
}

// ContactGTE applies the GTE predicate on the "contact" field.
func ContactGTE(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldGTE(FieldContact, v))
}

// ContactLT applies the LT predicate on the "contact" field.
func ContactLT(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldLT(FieldContact, v))
}

// ContactLTE applies the LTE predicate on the "contact" field.
func ContactLTE(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldLTE(FieldContact, v))
}

// ContactContains applies the Contains predicate on the "contact" field.
func ContactContains(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldContains(FieldContact, v))
}

// ContactHasPrefix applies the HasPrefix predicate on the "contact" field.
func ContactHasPrefix(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldHasPrefix(FieldContact, v))
}

// ContactHasSuffix applies the HasSuffix predicate on the "contact" field.
func ContactHasSuffix(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldHasSuffix(FieldContact, v))
}

// ContactIsNil applies the IsNil predicate on the "contact" field.
func ContactIsNil() predicate.NotificationData {
	return predicate.NotificationData(sql.FieldIsNull(FieldContact))
}

// ContactNotNil applies the NotNil predicate on the "contact" field.
func ContactNotNil() predicate.NotificationData {
	return predicate.NotificationData(sql.FieldNotNull(FieldContact))
}

// ContactEqualFold applies the EqualFold predicate on the "contact" field.
func ContactEqualFold(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldEqualFold(FieldContact, v))
}

// ContactContainsFold applies the ContainsFold predicate on the "contact" field.
func ContactContainsFold(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldContainsFold(FieldContact, v))
}

// TaskEQ applies the EQ predicate on the "task" field.
func TaskEQ(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldEQ(FieldTask, v))
}

// TaskNEQ applies the NEQ predicate on the "task" field.
func TaskNEQ(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldNEQ(FieldTask, v))
}

// TaskIn applies the In predicate on the "task" field.
func TaskIn(vs ...string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldIn(FieldTask, vs...))
}

// TaskNotIn applies the NotIn predicate on the "task" field.
func TaskNotIn(vs ...string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldNotIn(FieldTask, vs...))
}

// TaskGT applies the GT predicate on the "task" field.
func TaskGT(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldGT(FieldTask, v))
}

// TaskGTE applies the GTE predicate on the "task" field.
func TaskGTE(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldGTE(FieldTask, v))
}

// TaskLT applies the LT predicate on the "task" field.
func TaskLT(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldLT(FieldTask, v))
}

// TaskLTE applies the LTE predicate on the "task" field.
func TaskLTE(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldLTE(FieldTask, v))
}

// TaskContains applies the Contains predicate on the "task" field.
func TaskContains(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldContains(FieldTask, v))
}

// TaskHasPrefix applies the HasPrefix predicate on the "task" field.
func TaskHasPrefix(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldHasPrefix(FieldTask, v))
}

// TaskHasSuffix applies the HasSuffix predicate on the "task" field.
func TaskHasSuffix(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldHasSuffix(FieldTask, v))
}

// TaskIsNil applies the IsNil predicate on the "task" field.
func TaskIsNil() predicate.NotificationData {
	return predicate.NotificationData(sql.FieldIsNull(FieldTask))
}

// TaskNotNil applies the NotNil predicate on the "task" field.
func TaskNotNil() predicate.NotificationData {
	return predicate.NotificationData(sql.FieldNotNull(FieldTask))
}

// TaskEqualFold applies the EqualFold predicate on the "task" field.
func TaskEqualFold(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldEqualFold(FieldTask, v))
}

// TaskContainsFold applies the ContainsFold predicate on the "task" field.
func TaskContainsFold(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldContainsFold(FieldTask, v))
}

// ProjectEQ applies the EQ predicate on the "project" field.
func ProjectEQ(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldEQ(FieldProject, v))
}

// ProjectNEQ applies the NEQ predicate on the "project" field.
func ProjectNEQ(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldNEQ(FieldProject, v))
}

// ProjectIn applies the In predicate on the "project" field.
func ProjectIn(vs ...string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldIn(FieldProject, vs...))
}

// ProjectNotIn applies the NotIn predicate on the "project" field.
func ProjectNotIn(vs ...string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldNotIn(FieldProject, vs...))
}

// ProjectGT applies the GT predicate on the "project" field.
func ProjectGT(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldGT(FieldProject, v))
}

// ProjectGTE applies the GTE predicate on the "project" field.
func ProjectGTE(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldGTE(FieldProject, v))
}

// ProjectLT applies the LT predicate on the "project" field.
func ProjectLT(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldLT(FieldProject, v))
}

// ProjectLTE applies the LTE predicate on the "project" field.
func ProjectLTE(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldLTE(FieldProject, v))
}

// ProjectContains applies the Contains predicate on the "project" field.
func ProjectContains(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldContains(FieldProject, v))
}

// ProjectHasPrefix applies the HasPrefix predicate on the "project" field.
func ProjectHasPrefix(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldHasPrefix(FieldProject, v))
}

// ProjectHasSuffix applies the HasSuffix predicate on the "project" field.
func ProjectHasSuffix(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldHasSuffix(FieldProject, v))
}

// ProjectIsNil applies the IsNil predicate on the "project" field.
func ProjectIsNil() predicate.NotificationData {
	return predicate.NotificationData(sql.FieldIsNull(FieldProject))
}

// ProjectNotNil applies the NotNil predicate on the "project" field.
func ProjectNotNil() predicate.NotificationData {
	return predicate.NotificationData(sql.FieldNotNull(FieldProject))
}

// ProjectEqualFold applies the EqualFold predicate on the "project" field.
func ProjectEqualFold(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldEqualFold(FieldProject, v))
}

// ProjectContainsFold applies the ContainsFold predicate on the "project" field.
func ProjectContainsFold(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldContainsFold(FieldProject, v))
}

// TargetUserIDEQ applies the EQ predicate on the "target_user_id" field.
func TargetUserIDEQ(v int64) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldEQ(FieldTargetUserID, v))
}

// TargetUserIDNEQ applies the NEQ predicate on the "target_user_id" field.
func TargetUserIDNEQ(v int64) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldNEQ(FieldTargetUserID, v))
}

// TargetUserIDIn applies the In predicate on the "target_user_id" field.
func TargetUserIDIn(vs ...int64) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldIn(FieldTargetUserID, vs...))
}

// TargetUserIDNotIn applies the NotIn predicate on the "target_user_id" field.
func TargetUserIDNotIn(vs ...int64) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldNotIn(FieldTargetUserID, vs...))
}

// TargetUserIDGT applies the GT predicate on the "target_user_id" field.
func TargetUserIDGT(v int64) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldGT(FieldTargetUserID, v))
}

// TargetUserIDGTE applies the GTE predicate on the "target_user_id" field.
func TargetUserIDGTE(v int64) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldGTE(FieldTargetUserID, v))
}

// TargetUserIDLT applies the LT predicate on the "target_user_id" field.
func TargetUserIDLT(v int64) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldLT(FieldTargetUserID, v))
}

// TargetUserIDLTE applies the LTE predicate on the "target_user_id" field.
func TargetUserIDLTE(v int64) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldLTE(FieldTargetUserID, v))
}

// TargetUserIDIsNil applies the IsNil predicate on the "target_user_id" field.
func TargetUserIDIsNil() predicate.NotificationData {
	return predicate.NotificationData(sql.FieldIsNull(FieldTargetUserID))
}

// TargetUserIDNotNil applies the NotNil predicate on the "target_user_id" field.
func TargetUserIDNotNil() predicate.NotificationData {
	return predicate.NotificationData(sql.FieldNotNull(FieldTargetUserID))
}

// MetadataEQ applies the EQ predicate on the "metadata" field.
func MetadataEQ(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldEQ(FieldMetadata, v))
}

// MetadataNEQ applies the NEQ predicate on the "metadata" field.
func MetadataNEQ(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldNEQ(FieldMetadata, v))
}

// MetadataIn applies the In predicate on the "metadata" field.
func MetadataIn(vs ...string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldIn(FieldMetadata, vs...))
}

// MetadataNotIn applies the NotIn predicate on the "metadata" field.
func MetadataNotIn(vs ...string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldNotIn(FieldMetadata, vs...))
}

// MetadataGT applies the GT predicate on the "metadata" field.
func MetadataGT(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldGT(FieldMetadata, v))
}

// MetadataGTE applies the GTE predicate on the "metadata" field.
func MetadataGTE(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldGTE(FieldMetadata, v))
}

// MetadataLT applies the LT predicate on the "metadata" field.
func MetadataLT(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldLT(FieldMetadata, v))
}

// MetadataLTE applies the LTE predicate on the "metadata" field.
func MetadataLTE(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldLTE(FieldMetadata, v))
}

// MetadataContains applies the Contains predicate on the "metadata" field.
func MetadataContains(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldContains(FieldMetadata, v))
}

// MetadataHasPrefix applies the HasPrefix predicate on the "metadata" field.
func MetadataHasPrefix(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldHasPrefix(FieldMetadata, v))
}

// MetadataHasSuffix applies the HasSuffix predicate on the "metadata" field.
func MetadataHasSuffix(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldHasSuffix(FieldMetadata, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.NotificationData {
	return predicate.NotificationData(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.NotificationData {
	return predicate.NotificationData(sql.FieldNotNull(FieldMetadata))
}

// MetadataEqualFold applies the EqualFold predicate on the "metadata" field.
func MetadataEqualFold(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldEqualFold(FieldMetadata, v))
}

// MetadataContainsFold applies the ContainsFold predicate on the "metadata" field.
func MetadataContainsFold(v string) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldContainsFold(FieldMetadata, v))
}

// PluralCountEQ applies the EQ predicate on the "plural_count" field.
func PluralCountEQ(v int64) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldEQ(FieldPluralCount, v))
}

// PluralCountNEQ applies the NEQ predicate on the "plural_count" field.
func PluralCountNEQ(v int64) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldNEQ(FieldPluralCount, v))
}

// PluralCountIn applies the In predicate on the "plural_count" field.
func PluralCountIn(vs ...int64) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldIn(FieldPluralCount, vs...))
}

// PluralCountNotIn applies the NotIn predicate on the "plural_count" field.
func PluralCountNotIn(vs ...int64) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldNotIn(FieldPluralCount, vs...))
}

// PluralCountGT applies the GT predicate on the "plural_count" field.
func PluralCountGT(v int64) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldGT(FieldPluralCount, v))
}

// PluralCountGTE applies the GTE predicate on the "plural_count" field.
func PluralCountGTE(v int64) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldGTE(FieldPluralCount, v))
}

// PluralCountLT applies the LT predicate on the "plural_count" field.
func PluralCountLT(v int64) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldLT(FieldPluralCount, v))
}

// PluralCountLTE applies the LTE predicate on the "plural_count" field.
func PluralCountLTE(v int64) predicate.NotificationData {
	return predicate.NotificationData(sql.FieldLTE(FieldPluralCount, v))
}

// PluralCountIsNil applies the IsNil predicate on the "plural_count" field.
func PluralCountIsNil() predicate.NotificationData {
	return predicate.NotificationData(sql.FieldIsNull(FieldPluralCount))
}

// PluralCountNotNil applies the NotNil predicate on the "plural_count" field.
func PluralCountNotNil() predicate.NotificationData {
	return predicate.NotificationData(sql.FieldNotNull(FieldPluralCount))
}

// HasNotification applies the HasEdge predicate on the "notification" edge.
func HasNotification() predicate.NotificationData {
	return predicate.NotificationData(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, NotificationTable, NotificationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNotificationWith applies the HasEdge predicate on the "notification" edge with a given conditions (other predicates).
func HasNotificationWith(preds ...predicate.Notification) predicate.NotificationData {
	return predicate.NotificationData(func(s *sql.Selector) {
		step := newNotificationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.NotificationData) predicate.NotificationData {
	return predicate.NotificationData(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.NotificationData) predicate.NotificationData {
	return predicate.NotificationData(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.NotificationData) predicate.NotificationData {
	return predicate.NotificationData(sql.NotPredicates(p))
}
