// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"gitlab.calendaria.team/services/notifications/internal/biz"
	"gitlab.calendaria.team/services/notifications/internal/conf"
	"gitlab.calendaria.team/services/notifications/internal/data"
	"gitlab.calendaria.team/services/notifications/internal/server"
	"gitlab.calendaria.team/services/notifications/internal/service"
	"gitlab.calendaria.team/services/utils/v1/config"
	"gitlab.calendaria.team/services/utils/v2/dialer"
	"gitlab.calendaria.team/services/utils/v2/jwt"
	"gitlab.calendaria.team/services/utils/v2/nats"
	"gitlab.calendaria.team/services/utils/v2/tracing"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	iJwtProcessor, err := jwt.NewJwtProcessor(configConfig)
	if err != nil {
		return nil, nil, err
	}
	tracer := tracing.NewTracer(configConfig)
	smscClient := data.NewSmscClient(configConfig, logger)
	smsUsecase, err := biz.NewSmsUsecase(logger, smscClient)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(bootstrap, configConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	devicesRepo := data.NewDevicesRepo(dataData, logger)
	notificationsRepo := data.NewNotificationsRepo(dataData)
	localizer, err := data.NewLocalizer()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	conn, cleanup2, err := data.NewNatsClient(bootstrap)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	iQueueManager := nats.NewQueueManager(configConfig, conn, logger)
	fcmUsecase, err := biz.NewFcmUsecase(logger, devicesRepo, notificationsRepo, localizer, iQueueManager)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	localizedEmailTemplates, err := biz.NewLocalizedEmailTemplates()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	emailUsecase, err := biz.NewEmailUsecase(configConfig, logger, iQueueManager, localizedEmailTemplates, localizer)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	senderService := service.NewSenderService(smsUsecase, fcmUsecase, emailUsecase)
	iDialerManager, err := dialer.NewServiceDialerManager(configConfig, tracer, iJwtProcessor)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	iIamRemote, cleanup3, err := data.NewIamRemote(logger, bootstrap, iDialerManager)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	notificationsUsecase, err := biz.NewNotificationsUsecase(localizer, notificationsRepo, iIamRemote)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	notificationsService := service.NewNotificationsService(notificationsUsecase)
	grpcServer := server.NewGRPCServer(bootstrap, iJwtProcessor, tracer, senderService, notificationsService)
	httpServer := server.NewHTTPServer(bootstrap, iJwtProcessor)
	app := newApp(logger, configConfig, grpcServer, httpServer)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
