// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"notifications/internal/biz"
	"notifications/internal/conf"
	"notifications/internal/data"
	"notifications/internal/server"
	"notifications/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	config, err := data.NewConfig(bootstrap)
	if err != nil {
		return nil, nil, err
	}
	jwtProcessor, err := data.NewJwtProcessor(config)
	if err != nil {
		return nil, nil, err
	}
	smsUsecase, err := biz.NewSmsUsecase(config, logger)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(bootstrap, logger)
	if err != nil {
		return nil, nil, err
	}
	devicesRepo := data.NewDevicesRepo(dataData, logger)
	natsClient, cleanup2, err := data.NewNatsClient(config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	queueManager := biz.NewQueueManager(config, natsClient, logger)
	fcmUsecase, err := biz.NewFcmUsecase(config, logger, devicesRepo, queueManager)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	senderService := service.NewSenderService(logger, jwtProcessor, smsUsecase, fcmUsecase)
	notificationsRepo := data.NewNotificationsRepo(dataData)
	notificationsUsecase, err := biz.NewNotificationsUsecase(logger, config, jwtProcessor, notificationsRepo)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	notificationsService := service.NewNotificationsService(logger, notificationsUsecase)
	grpcServer := server.NewGRPCServer(bootstrap, jwtProcessor, senderService, notificationsService)
	httpServer := server.NewHTTPServer(bootstrap, jwtProcessor, senderService, notificationsService)
	app := newApp(logger, config, grpcServer, httpServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
