// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/notifications/v1/models.proto

package notifications_v1

import (
	events_v1 "github.com/makesalekz/notifications/internal/stub/events_v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	EventId       int64                  `protobuf:"varint,5,opt,name=eventId,proto3" json:"eventId,omitempty"`
	ContactId     int64                  `protobuf:"varint,6,opt,name=contactId,proto3" json:"contactId,omitempty"`
	TaskId        int64                  `protobuf:"varint,8,opt,name=taskId,proto3" json:"taskId,omitempty"`
	ProjectId     int64                  `protobuf:"varint,9,opt,name=projectId,proto3" json:"projectId,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	// Event field removed from proto registration to decouple from events service.
	// Kept as a Go field for backward compatibility with existing code.
	Event         *events_v1.Event       `json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_api_notifications_v1_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_api_notifications_v1_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*Notification) Descriptor() ([]byte, []int) {
	return file_api_notifications_v1_models_proto_rawDescGZIP(), []int{0}
}

func (x *Notification) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Notification) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Notification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notification) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Notification) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *Notification) GetContactId() int64 {
	if x != nil {
		return x.ContactId
	}
	return 0
}

func (x *Notification) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *Notification) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *Notification) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Notification) GetEvent() *events_v1.Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type NotificationDto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	EventId       int64                  `protobuf:"varint,4,opt,name=eventId,proto3" json:"eventId,omitempty"`
	ContactId     int64                  `protobuf:"varint,5,opt,name=contactId,proto3" json:"contactId,omitempty"`
	TaskId        int64                  `protobuf:"varint,6,opt,name=taskId,proto3" json:"taskId,omitempty"`
	ProjectId     int64                  `protobuf:"varint,7,opt,name=projectId,proto3" json:"projectId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationDto) Reset() {
	*x = NotificationDto{}
	mi := &file_api_notifications_v1_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationDto) ProtoMessage() {}

func (x *NotificationDto) ProtoReflect() protoreflect.Message {
	mi := &file_api_notifications_v1_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*NotificationDto) Descriptor() ([]byte, []int) {
	return file_api_notifications_v1_models_proto_rawDescGZIP(), []int{1}
}

func (x *NotificationDto) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *NotificationDto) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NotificationDto) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *NotificationDto) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *NotificationDto) GetContactId() int64 {
	if x != nil {
		return x.ContactId
	}
	return 0
}

func (x *NotificationDto) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *NotificationDto) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

var File_api_notifications_v1_models_proto protoreflect.FileDescriptor

// rawDesc generated from models.proto WITHOUT events.v1.Event dependency.
const file_api_notifications_v1_models_proto_rawDesc = "" +
	"\x0a!api/notifications/v1/models.proto\x12\x10notifications.v1\x22\xe8\x01\x0a\x0cNo" +
	"tification\x12\x0e\x0a\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\x0a\x04type\x18\x02 \x01(\x09R\x04type\x12\x14\x0a\x05title\x18\x03 \x01(" +
	"\x09R\x05title\x12\x12\x0a\x04text\x18\x04 \x01(\x09R\x04text\x12\x18\x0a\x07eventId\x18\x05 \x01(\x03R\x07eventId\x12\x1c\x0a\x09co" +
	"ntactId\x18\x06 \x01(\x03R\x09contactId\x12\x1c\x0a\x09createdAt\x18\x07 \x01(\x09R\x09createdAt\x12\x16\x0a\x06ta" +
	"skId\x18\x08 \x01(\x03R\x06taskId\x12\x1c\x0a\x09projectId\x18\x09 \x01(\x03R\x09projectId\x22\xc1\x01\x0a\x0fNotific" +
	"ationDto\x12\x16\x0a\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x14\x0a\x05title\x18\x02 \x01(\x09R\x05title\x12\x12\x0a\x04te" +
	"xt\x18\x03 \x01(\x09R\x04text\x12\x18\x0a\x07eventId\x18\x04 \x01(\x03R\x07eventId\x12\x1c\x0a\x09contactId\x18\x05 \x01(\x03R" +
	"\x09contactId\x12\x16\x0a\x06taskId\x18\x06 \x01(\x03R\x06taskId\x12\x1c\x0a\x09projectId\x18\x07 \x01(\x03R\x09proje" +
	"ctIdBi\x0a\x10notifications.v1P\x01ZSgitlab.calendaria.team/services/" +
	"notifications/api/notifications/v1;notifications_v1b\x06proto3"

var (
	file_api_notifications_v1_models_proto_rawDescOnce sync.Once
	file_api_notifications_v1_models_proto_rawDescData []byte
)

func file_api_notifications_v1_models_proto_rawDescGZIP() []byte {
	file_api_notifications_v1_models_proto_rawDescOnce.Do(func() {
		file_api_notifications_v1_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_notifications_v1_models_proto_rawDesc), len(file_api_notifications_v1_models_proto_rawDesc)))
	})
	return file_api_notifications_v1_models_proto_rawDescData
}

var file_api_notifications_v1_models_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_notifications_v1_models_proto_goTypes = []any{
	(*Notification)(nil),    // 0: notifications.v1.Notification
	(*NotificationDto)(nil), // 1: notifications.v1.NotificationDto
}
var file_api_notifications_v1_models_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_notifications_v1_models_proto_init() }
func file_api_notifications_v1_models_proto_init() {
	if File_api_notifications_v1_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_notifications_v1_models_proto_rawDesc), len(file_api_notifications_v1_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_notifications_v1_models_proto_goTypes,
		DependencyIndexes: file_api_notifications_v1_models_proto_depIdxs,
		MessageInfos:      file_api_notifications_v1_models_proto_msgTypes,
	}.Build()
	File_api_notifications_v1_models_proto = out.File
	file_api_notifications_v1_models_proto_goTypes = nil
	file_api_notifications_v1_models_proto_depIdxs = nil
}
