// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.0
// - protoc             v4.24.4
// source: notifications/v1/notifications.proto

package notifications_v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationNotificationsListNotifications = "/api.notifications.v1.Notifications/ListNotifications"

type NotificationsHTTPServer interface {
	ListNotifications(context.Context, *ListNotificationsRequest) (*ListNotificationsReply, error)
}

func RegisterNotificationsHTTPServer(s *http.Server, srv NotificationsHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/notifications/list", _Notifications_ListNotifications0_HTTP_Handler(srv))
}

func _Notifications_ListNotifications0_HTTP_Handler(srv NotificationsHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListNotificationsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationNotificationsListNotifications)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListNotifications(ctx, req.(*ListNotificationsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListNotificationsReply)
		return ctx.Result(200, reply)
	}
}

type NotificationsHTTPClient interface {
	ListNotifications(ctx context.Context, req *ListNotificationsRequest, opts ...http.CallOption) (rsp *ListNotificationsReply, err error)
}

type NotificationsHTTPClientImpl struct {
	cc *http.Client
}

func NewNotificationsHTTPClient(client *http.Client) NotificationsHTTPClient {
	return &NotificationsHTTPClientImpl{client}
}

func (c *NotificationsHTTPClientImpl) ListNotifications(ctx context.Context, in *ListNotificationsRequest, opts ...http.CallOption) (*ListNotificationsReply, error) {
	var out ListNotificationsReply
	pattern := "/v1/notifications/list"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationNotificationsListNotifications))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
