// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.0
// - protoc             v4.24.4
// source: notifications/v1/sender.proto

package notifications_v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSenderCreateFcmDevice = "/api.notifications.v1.Sender/CreateFcmDevice"
const OperationSenderDeleteFcmDevice = "/api.notifications.v1.Sender/DeleteFcmDevice"

type SenderHTTPServer interface {
	CreateFcmDevice(context.Context, *FcmDeviceRequest) (*EmptyReply, error)
	DeleteFcmDevice(context.Context, *FcmDeviceRequest) (*EmptyReply, error)
}

func RegisterSenderHTTPServer(s *http.Server, srv SenderHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/notifications/fcm/devices", _Sender_CreateFcmDevice0_HTTP_Handler(srv))
	r.DELETE("/v1/notifications/fcm/devices", _Sender_DeleteFcmDevice0_HTTP_Handler(srv))
}

func _Sender_CreateFcmDevice0_HTTP_Handler(srv SenderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FcmDeviceRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSenderCreateFcmDevice)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateFcmDevice(ctx, req.(*FcmDeviceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*EmptyReply)
		return ctx.Result(200, reply)
	}
}

func _Sender_DeleteFcmDevice0_HTTP_Handler(srv SenderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FcmDeviceRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSenderDeleteFcmDevice)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteFcmDevice(ctx, req.(*FcmDeviceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*EmptyReply)
		return ctx.Result(200, reply)
	}
}

type SenderHTTPClient interface {
	CreateFcmDevice(ctx context.Context, req *FcmDeviceRequest, opts ...http.CallOption) (rsp *EmptyReply, err error)
	DeleteFcmDevice(ctx context.Context, req *FcmDeviceRequest, opts ...http.CallOption) (rsp *EmptyReply, err error)
}

type SenderHTTPClientImpl struct {
	cc *http.Client
}

func NewSenderHTTPClient(client *http.Client) SenderHTTPClient {
	return &SenderHTTPClientImpl{client}
}

func (c *SenderHTTPClientImpl) CreateFcmDevice(ctx context.Context, in *FcmDeviceRequest, opts ...http.CallOption) (*EmptyReply, error) {
	var out EmptyReply
	pattern := "/v1/notifications/fcm/devices"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSenderCreateFcmDevice))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *SenderHTTPClientImpl) DeleteFcmDevice(ctx context.Context, in *FcmDeviceRequest, opts ...http.CallOption) (*EmptyReply, error) {
	var out EmptyReply
	pattern := "/v1/notifications/fcm/devices"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSenderDeleteFcmDevice))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
