// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/notifications/v1/sender.proto

package notifications_v1

import (
	context "context"
	v1 "github.com/makesalekz/utils/api/utils/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Sender_CreateFcmDevice_FullMethodName   = "/notifications.v1.Sender/CreateFcmDevice"
	Sender_DeleteFcmDevice_FullMethodName   = "/notifications.v1.Sender/DeleteFcmDevice"
	Sender_PersonalSmsSender_FullMethodName = "/notifications.v1.Sender/PersonalSmsSender"
	Sender_EmailSender_FullMethodName       = "/notifications.v1.Sender/EmailSender"
)

// SenderClient is the client API for Sender service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SenderClient interface {
	CreateFcmDevice(ctx context.Context, in *FcmDataRequest, opts ...grpc.CallOption) (*v1.EmptyReply, error)
	DeleteFcmDevice(ctx context.Context, in *FcmDeviceRequest, opts ...grpc.CallOption) (*v1.EmptyReply, error)
	PersonalSmsSender(ctx context.Context, in *PersonalSmsSenderRequest, opts ...grpc.CallOption) (*v1.EmptyReply, error)
	EmailSender(ctx context.Context, in *EmailSenderRequest, opts ...grpc.CallOption) (*v1.EmptyReply, error)
}

type senderClient struct {
	cc grpc.ClientConnInterface
}

func NewSenderClient(cc grpc.ClientConnInterface) SenderClient {
	return &senderClient{cc}
}

func (c *senderClient) CreateFcmDevice(ctx context.Context, in *FcmDataRequest, opts ...grpc.CallOption) (*v1.EmptyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.EmptyReply)
	err := c.cc.Invoke(ctx, Sender_CreateFcmDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *senderClient) DeleteFcmDevice(ctx context.Context, in *FcmDeviceRequest, opts ...grpc.CallOption) (*v1.EmptyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.EmptyReply)
	err := c.cc.Invoke(ctx, Sender_DeleteFcmDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *senderClient) PersonalSmsSender(ctx context.Context, in *PersonalSmsSenderRequest, opts ...grpc.CallOption) (*v1.EmptyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.EmptyReply)
	err := c.cc.Invoke(ctx, Sender_PersonalSmsSender_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *senderClient) EmailSender(ctx context.Context, in *EmailSenderRequest, opts ...grpc.CallOption) (*v1.EmptyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.EmptyReply)
	err := c.cc.Invoke(ctx, Sender_EmailSender_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SenderServer is the server API for Sender service.
// All implementations must embed UnimplementedSenderServer
// for forward compatibility.
type SenderServer interface {
	CreateFcmDevice(context.Context, *FcmDataRequest) (*v1.EmptyReply, error)
	DeleteFcmDevice(context.Context, *FcmDeviceRequest) (*v1.EmptyReply, error)
	PersonalSmsSender(context.Context, *PersonalSmsSenderRequest) (*v1.EmptyReply, error)
	EmailSender(context.Context, *EmailSenderRequest) (*v1.EmptyReply, error)
	mustEmbedUnimplementedSenderServer()
}

// UnimplementedSenderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSenderServer struct{}

func (UnimplementedSenderServer) CreateFcmDevice(context.Context, *FcmDataRequest) (*v1.EmptyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFcmDevice not implemented")
}
func (UnimplementedSenderServer) DeleteFcmDevice(context.Context, *FcmDeviceRequest) (*v1.EmptyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFcmDevice not implemented")
}
func (UnimplementedSenderServer) PersonalSmsSender(context.Context, *PersonalSmsSenderRequest) (*v1.EmptyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PersonalSmsSender not implemented")
}
func (UnimplementedSenderServer) EmailSender(context.Context, *EmailSenderRequest) (*v1.EmptyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmailSender not implemented")
}
func (UnimplementedSenderServer) mustEmbedUnimplementedSenderServer() {}
func (UnimplementedSenderServer) testEmbeddedByValue()                {}

// UnsafeSenderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SenderServer will
// result in compilation errors.
type UnsafeSenderServer interface {
	mustEmbedUnimplementedSenderServer()
}

func RegisterSenderServer(s grpc.ServiceRegistrar, srv SenderServer) {
	// If the following call pancis, it indicates UnimplementedSenderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Sender_ServiceDesc, srv)
}

func _Sender_CreateFcmDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FcmDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SenderServer).CreateFcmDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sender_CreateFcmDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SenderServer).CreateFcmDevice(ctx, req.(*FcmDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sender_DeleteFcmDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FcmDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SenderServer).DeleteFcmDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sender_DeleteFcmDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SenderServer).DeleteFcmDevice(ctx, req.(*FcmDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sender_PersonalSmsSender_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PersonalSmsSenderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SenderServer).PersonalSmsSender(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sender_PersonalSmsSender_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SenderServer).PersonalSmsSender(ctx, req.(*PersonalSmsSenderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sender_EmailSender_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailSenderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SenderServer).EmailSender(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sender_EmailSender_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SenderServer).EmailSender(ctx, req.(*EmailSenderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Sender_ServiceDesc is the grpc.ServiceDesc for Sender service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sender_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notifications.v1.Sender",
	HandlerType: (*SenderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFcmDevice",
			Handler:    _Sender_CreateFcmDevice_Handler,
		},
		{
			MethodName: "DeleteFcmDevice",
			Handler:    _Sender_DeleteFcmDevice_Handler,
		},
		{
			MethodName: "PersonalSmsSender",
			Handler:    _Sender_PersonalSmsSender_Handler,
		},
		{
			MethodName: "EmailSender",
			Handler:    _Sender_EmailSender_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/notifications/v1/sender.proto",
}
