// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/notifications/v1/sender.proto

package notifications_v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	v1 "github.com/makesalekz/utils/api/utils/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FcmDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FcmDeviceRequest) Reset() {
	*x = FcmDeviceRequest{}
	mi := &file_api_notifications_v1_sender_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FcmDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FcmDeviceRequest) ProtoMessage() {}

func (x *FcmDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notifications_v1_sender_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FcmDeviceRequest.ProtoReflect.Descriptor instead.
func (*FcmDeviceRequest) Descriptor() ([]byte, []int) {
	return file_api_notifications_v1_sender_proto_rawDescGZIP(), []int{0}
}

func (x *FcmDeviceRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type FcmDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Language      string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	OldToken      *string                `protobuf:"bytes,3,opt,name=oldToken,proto3,oneof" json:"oldToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FcmDataRequest) Reset() {
	*x = FcmDataRequest{}
	mi := &file_api_notifications_v1_sender_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FcmDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FcmDataRequest) ProtoMessage() {}

func (x *FcmDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notifications_v1_sender_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FcmDataRequest.ProtoReflect.Descriptor instead.
func (*FcmDataRequest) Descriptor() ([]byte, []int) {
	return file_api_notifications_v1_sender_proto_rawDescGZIP(), []int{1}
}

func (x *FcmDataRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *FcmDataRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *FcmDataRequest) GetOldToken() string {
	if x != nil && x.OldToken != nil {
		return *x.OldToken
	}
	return ""
}

type PersonalSmsSenderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Sender        string                 `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonalSmsSenderRequest) Reset() {
	*x = PersonalSmsSenderRequest{}
	mi := &file_api_notifications_v1_sender_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonalSmsSenderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalSmsSenderRequest) ProtoMessage() {}

func (x *PersonalSmsSenderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notifications_v1_sender_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalSmsSenderRequest.ProtoReflect.Descriptor instead.
func (*PersonalSmsSenderRequest) Descriptor() ([]byte, []int) {
	return file_api_notifications_v1_sender_proto_rawDescGZIP(), []int{2}
}

func (x *PersonalSmsSenderRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *PersonalSmsSenderRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PersonalSmsSenderRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

type EmailSenderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Language      *string                `protobuf:"bytes,1,opt,name=language,proto3,oneof" json:"language,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Emails        []string               `protobuf:"bytes,3,rep,name=emails,proto3" json:"emails,omitempty"`
	Data          map[string]string      `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailSenderRequest) Reset() {
	*x = EmailSenderRequest{}
	mi := &file_api_notifications_v1_sender_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailSenderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailSenderRequest) ProtoMessage() {}

func (x *EmailSenderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notifications_v1_sender_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailSenderRequest.ProtoReflect.Descriptor instead.
func (*EmailSenderRequest) Descriptor() ([]byte, []int) {
	return file_api_notifications_v1_sender_proto_rawDescGZIP(), []int{3}
}

func (x *EmailSenderRequest) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

func (x *EmailSenderRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EmailSenderRequest) GetEmails() []string {
	if x != nil {
		return x.Emails
	}
	return nil
}

func (x *EmailSenderRequest) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_api_notifications_v1_sender_proto protoreflect.FileDescriptor

const file_api_notifications_v1_sender_proto_rawDesc = "" +
	"\n" +
	"!api/notifications/v1/sender.proto\x12\x10notifications.v1\x1a\x19api/utils/v1/models.proto\x1a\x17validate/validate.proto\"(\n" +
	"\x10FcmDeviceRequest\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"p\n" +
	"\x0eFcmDataRequest\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1f\n" +
	"\boldToken\x18\x03 \x01(\tH\x00R\boldToken\x88\x01\x01B\v\n" +
	"\t_oldToken\"b\n" +
	"\x18PersonalSmsSenderRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\tR\x06sender\"\xaa\x02\n" +
	"\x12EmailSenderRequest\x122\n" +
	"\blanguage\x18\x01 \x01(\tB\x11\xfaB\x0er\fR\x02enR\x02ruR\x02kkH\x00R\blanguage\x88\x01\x01\x120\n" +
	"\x04type\x18\x02 \x01(\tB\x1c\xfaB\x19r\x17R\x06inviteR\rconfirm_emailR\x04type\x12$\n" +
	"\x06emails\x18\x03 \x03(\tB\f\xfaB\t\x92\x01\x06\"\x04r\x02`\x01R\x06emails\x12B\n" +
	"\x04data\x18\x04 \x03(\v2..notifications.v1.EmailSenderRequest.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\v\n" +
	"\t_language2\xc2\x02\n" +
	"\x06Sender\x12I\n" +
	"\x0fCreateFcmDevice\x12 .notifications.v1.FcmDataRequest\x1a\x14.utils.v1.EmptyReply\x12K\n" +
	"\x0fDeleteFcmDevice\x12\".notifications.v1.FcmDeviceRequest\x1a\x14.utils.v1.EmptyReply\x12U\n" +
	"\x11PersonalSmsSender\x12*.notifications.v1.PersonalSmsSenderRequest\x1a\x14.utils.v1.EmptyReply\x12I\n" +
	"\vEmailSender\x12$.notifications.v1.EmailSenderRequest\x1a\x14.utils.v1.EmptyReplyBi\n" +
	"\x10notifications.v1P\x01ZSgitlab.calendaria.team/services/notifications/api/notifications/v1;notifications_v1b\x06proto3"

var (
	file_api_notifications_v1_sender_proto_rawDescOnce sync.Once
	file_api_notifications_v1_sender_proto_rawDescData []byte
)

func file_api_notifications_v1_sender_proto_rawDescGZIP() []byte {
	file_api_notifications_v1_sender_proto_rawDescOnce.Do(func() {
		file_api_notifications_v1_sender_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_notifications_v1_sender_proto_rawDesc), len(file_api_notifications_v1_sender_proto_rawDesc)))
	})
	return file_api_notifications_v1_sender_proto_rawDescData
}

var file_api_notifications_v1_sender_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_notifications_v1_sender_proto_goTypes = []any{
	(*FcmDeviceRequest)(nil),         // 0: notifications.v1.FcmDeviceRequest
	(*FcmDataRequest)(nil),           // 1: notifications.v1.FcmDataRequest
	(*PersonalSmsSenderRequest)(nil), // 2: notifications.v1.PersonalSmsSenderRequest
	(*EmailSenderRequest)(nil),       // 3: notifications.v1.EmailSenderRequest
	nil,                              // 4: notifications.v1.EmailSenderRequest.DataEntry
	(*v1.EmptyReply)(nil),            // 5: utils.v1.EmptyReply
}
var file_api_notifications_v1_sender_proto_depIdxs = []int32{
	4, // 0: notifications.v1.EmailSenderRequest.data:type_name -> notifications.v1.EmailSenderRequest.DataEntry
	1, // 1: notifications.v1.Sender.CreateFcmDevice:input_type -> notifications.v1.FcmDataRequest
	0, // 2: notifications.v1.Sender.DeleteFcmDevice:input_type -> notifications.v1.FcmDeviceRequest
	2, // 3: notifications.v1.Sender.PersonalSmsSender:input_type -> notifications.v1.PersonalSmsSenderRequest
	3, // 4: notifications.v1.Sender.EmailSender:input_type -> notifications.v1.EmailSenderRequest
	5, // 5: notifications.v1.Sender.CreateFcmDevice:output_type -> utils.v1.EmptyReply
	5, // 6: notifications.v1.Sender.DeleteFcmDevice:output_type -> utils.v1.EmptyReply
	5, // 7: notifications.v1.Sender.PersonalSmsSender:output_type -> utils.v1.EmptyReply
	5, // 8: notifications.v1.Sender.EmailSender:output_type -> utils.v1.EmptyReply
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_notifications_v1_sender_proto_init() }
func file_api_notifications_v1_sender_proto_init() {
	if File_api_notifications_v1_sender_proto != nil {
		return
	}
	file_api_notifications_v1_sender_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_notifications_v1_sender_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_notifications_v1_sender_proto_rawDesc), len(file_api_notifications_v1_sender_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_notifications_v1_sender_proto_goTypes,
		DependencyIndexes: file_api_notifications_v1_sender_proto_depIdxs,
		MessageInfos:      file_api_notifications_v1_sender_proto_msgTypes,
	}.Build()
	File_api_notifications_v1_sender_proto = out.File
	file_api_notifications_v1_sender_proto_goTypes = nil
	file_api_notifications_v1_sender_proto_depIdxs = nil
}
