// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/makesalekz/notifications/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/makesalekz/notifications/ent/device"
	"github.com/makesalekz/notifications/ent/lastreadnotification"
	"github.com/makesalekz/notifications/ent/notification"
	"github.com/makesalekz/notifications/ent/notificationdata"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Device is the client for interacting with the Device builders.
	Device *DeviceClient
	// LastReadNotification is the client for interacting with the LastReadNotification builders.
	LastReadNotification *LastReadNotificationClient
	// Notification is the client for interacting with the Notification builders.
	Notification *NotificationClient
	// NotificationData is the client for interacting with the NotificationData builders.
	NotificationData *NotificationDataClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Device = NewDeviceClient(c.config)
	c.LastReadNotification = NewLastReadNotificationClient(c.config)
	c.Notification = NewNotificationClient(c.config)
	c.NotificationData = NewNotificationDataClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                  ctx,
		config:               cfg,
		Device:               NewDeviceClient(cfg),
		LastReadNotification: NewLastReadNotificationClient(cfg),
		Notification:         NewNotificationClient(cfg),
		NotificationData:     NewNotificationDataClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                  ctx,
		config:               cfg,
		Device:               NewDeviceClient(cfg),
		LastReadNotification: NewLastReadNotificationClient(cfg),
		Notification:         NewNotificationClient(cfg),
		NotificationData:     NewNotificationDataClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Device.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Device.Use(hooks...)
	c.LastReadNotification.Use(hooks...)
	c.Notification.Use(hooks...)
	c.NotificationData.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Device.Intercept(interceptors...)
	c.LastReadNotification.Intercept(interceptors...)
	c.Notification.Intercept(interceptors...)
	c.NotificationData.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *DeviceMutation:
		return c.Device.mutate(ctx, m)
	case *LastReadNotificationMutation:
		return c.LastReadNotification.mutate(ctx, m)
	case *NotificationMutation:
		return c.Notification.mutate(ctx, m)
	case *NotificationDataMutation:
		return c.NotificationData.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// DeviceClient is a client for the Device schema.
type DeviceClient struct {
	config
}

// NewDeviceClient returns a client for the Device from the given config.
func NewDeviceClient(c config) *DeviceClient {
	return &DeviceClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `device.Hooks(f(g(h())))`.
func (c *DeviceClient) Use(hooks ...Hook) {
	c.hooks.Device = append(c.hooks.Device, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `device.Intercept(f(g(h())))`.
func (c *DeviceClient) Intercept(interceptors ...Interceptor) {
	c.inters.Device = append(c.inters.Device, interceptors...)
}

// Create returns a builder for creating a Device entity.
func (c *DeviceClient) Create() *DeviceCreate {
	mutation := newDeviceMutation(c.config, OpCreate)
	return &DeviceCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Device entities.
func (c *DeviceClient) CreateBulk(builders ...*DeviceCreate) *DeviceCreateBulk {
	return &DeviceCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DeviceClient) MapCreateBulk(slice any, setFunc func(*DeviceCreate, int)) *DeviceCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DeviceCreateBulk{err: fmt.Errorf("calling to DeviceClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DeviceCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DeviceCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Device.
func (c *DeviceClient) Update() *DeviceUpdate {
	mutation := newDeviceMutation(c.config, OpUpdate)
	return &DeviceUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DeviceClient) UpdateOne(d *Device) *DeviceUpdateOne {
	mutation := newDeviceMutation(c.config, OpUpdateOne, withDevice(d))
	return &DeviceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DeviceClient) UpdateOneID(id int64) *DeviceUpdateOne {
	mutation := newDeviceMutation(c.config, OpUpdateOne, withDeviceID(id))
	return &DeviceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Device.
func (c *DeviceClient) Delete() *DeviceDelete {
	mutation := newDeviceMutation(c.config, OpDelete)
	return &DeviceDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DeviceClient) DeleteOne(d *Device) *DeviceDeleteOne {
	return c.DeleteOneID(d.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DeviceClient) DeleteOneID(id int64) *DeviceDeleteOne {
	builder := c.Delete().Where(device.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DeviceDeleteOne{builder}
}

// Query returns a query builder for Device.
func (c *DeviceClient) Query() *DeviceQuery {
	return &DeviceQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDevice},
		inters: c.Interceptors(),
	}
}

// Get returns a Device entity by its id.
func (c *DeviceClient) Get(ctx context.Context, id int64) (*Device, error) {
	return c.Query().Where(device.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DeviceClient) GetX(ctx context.Context, id int64) *Device {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *DeviceClient) Hooks() []Hook {
	return c.hooks.Device
}

// Interceptors returns the client interceptors.
func (c *DeviceClient) Interceptors() []Interceptor {
	return c.inters.Device
}

func (c *DeviceClient) mutate(ctx context.Context, m *DeviceMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DeviceCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DeviceUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DeviceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DeviceDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Device mutation op: %q", m.Op())
	}
}

// LastReadNotificationClient is a client for the LastReadNotification schema.
type LastReadNotificationClient struct {
	config
}

// NewLastReadNotificationClient returns a client for the LastReadNotification from the given config.
func NewLastReadNotificationClient(c config) *LastReadNotificationClient {
	return &LastReadNotificationClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `lastreadnotification.Hooks(f(g(h())))`.
func (c *LastReadNotificationClient) Use(hooks ...Hook) {
	c.hooks.LastReadNotification = append(c.hooks.LastReadNotification, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `lastreadnotification.Intercept(f(g(h())))`.
func (c *LastReadNotificationClient) Intercept(interceptors ...Interceptor) {
	c.inters.LastReadNotification = append(c.inters.LastReadNotification, interceptors...)
}

// Create returns a builder for creating a LastReadNotification entity.
func (c *LastReadNotificationClient) Create() *LastReadNotificationCreate {
	mutation := newLastReadNotificationMutation(c.config, OpCreate)
	return &LastReadNotificationCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of LastReadNotification entities.
func (c *LastReadNotificationClient) CreateBulk(builders ...*LastReadNotificationCreate) *LastReadNotificationCreateBulk {
	return &LastReadNotificationCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *LastReadNotificationClient) MapCreateBulk(slice any, setFunc func(*LastReadNotificationCreate, int)) *LastReadNotificationCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &LastReadNotificationCreateBulk{err: fmt.Errorf("calling to LastReadNotificationClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*LastReadNotificationCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &LastReadNotificationCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for LastReadNotification.
func (c *LastReadNotificationClient) Update() *LastReadNotificationUpdate {
	mutation := newLastReadNotificationMutation(c.config, OpUpdate)
	return &LastReadNotificationUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *LastReadNotificationClient) UpdateOne(lrn *LastReadNotification) *LastReadNotificationUpdateOne {
	mutation := newLastReadNotificationMutation(c.config, OpUpdateOne, withLastReadNotification(lrn))
	return &LastReadNotificationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *LastReadNotificationClient) UpdateOneID(id int64) *LastReadNotificationUpdateOne {
	mutation := newLastReadNotificationMutation(c.config, OpUpdateOne, withLastReadNotificationID(id))
	return &LastReadNotificationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for LastReadNotification.
func (c *LastReadNotificationClient) Delete() *LastReadNotificationDelete {
	mutation := newLastReadNotificationMutation(c.config, OpDelete)
	return &LastReadNotificationDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *LastReadNotificationClient) DeleteOne(lrn *LastReadNotification) *LastReadNotificationDeleteOne {
	return c.DeleteOneID(lrn.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *LastReadNotificationClient) DeleteOneID(id int64) *LastReadNotificationDeleteOne {
	builder := c.Delete().Where(lastreadnotification.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &LastReadNotificationDeleteOne{builder}
}

// Query returns a query builder for LastReadNotification.
func (c *LastReadNotificationClient) Query() *LastReadNotificationQuery {
	return &LastReadNotificationQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeLastReadNotification},
		inters: c.Interceptors(),
	}
}

// Get returns a LastReadNotification entity by its id.
func (c *LastReadNotificationClient) Get(ctx context.Context, id int64) (*LastReadNotification, error) {
	return c.Query().Where(lastreadnotification.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *LastReadNotificationClient) GetX(ctx context.Context, id int64) *LastReadNotification {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *LastReadNotificationClient) Hooks() []Hook {
	return c.hooks.LastReadNotification
}

// Interceptors returns the client interceptors.
func (c *LastReadNotificationClient) Interceptors() []Interceptor {
	return c.inters.LastReadNotification
}

func (c *LastReadNotificationClient) mutate(ctx context.Context, m *LastReadNotificationMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&LastReadNotificationCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&LastReadNotificationUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&LastReadNotificationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&LastReadNotificationDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown LastReadNotification mutation op: %q", m.Op())
	}
}

// NotificationClient is a client for the Notification schema.
type NotificationClient struct {
	config
}

// NewNotificationClient returns a client for the Notification from the given config.
func NewNotificationClient(c config) *NotificationClient {
	return &NotificationClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `notification.Hooks(f(g(h())))`.
func (c *NotificationClient) Use(hooks ...Hook) {
	c.hooks.Notification = append(c.hooks.Notification, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `notification.Intercept(f(g(h())))`.
func (c *NotificationClient) Intercept(interceptors ...Interceptor) {
	c.inters.Notification = append(c.inters.Notification, interceptors...)
}

// Create returns a builder for creating a Notification entity.
func (c *NotificationClient) Create() *NotificationCreate {
	mutation := newNotificationMutation(c.config, OpCreate)
	return &NotificationCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Notification entities.
func (c *NotificationClient) CreateBulk(builders ...*NotificationCreate) *NotificationCreateBulk {
	return &NotificationCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *NotificationClient) MapCreateBulk(slice any, setFunc func(*NotificationCreate, int)) *NotificationCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &NotificationCreateBulk{err: fmt.Errorf("calling to NotificationClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*NotificationCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &NotificationCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Notification.
func (c *NotificationClient) Update() *NotificationUpdate {
	mutation := newNotificationMutation(c.config, OpUpdate)
	return &NotificationUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *NotificationClient) UpdateOne(n *Notification) *NotificationUpdateOne {
	mutation := newNotificationMutation(c.config, OpUpdateOne, withNotification(n))
	return &NotificationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *NotificationClient) UpdateOneID(id int64) *NotificationUpdateOne {
	mutation := newNotificationMutation(c.config, OpUpdateOne, withNotificationID(id))
	return &NotificationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Notification.
func (c *NotificationClient) Delete() *NotificationDelete {
	mutation := newNotificationMutation(c.config, OpDelete)
	return &NotificationDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *NotificationClient) DeleteOne(n *Notification) *NotificationDeleteOne {
	return c.DeleteOneID(n.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *NotificationClient) DeleteOneID(id int64) *NotificationDeleteOne {
	builder := c.Delete().Where(notification.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &NotificationDeleteOne{builder}
}

// Query returns a query builder for Notification.
func (c *NotificationClient) Query() *NotificationQuery {
	return &NotificationQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeNotification},
		inters: c.Interceptors(),
	}
}

// Get returns a Notification entity by its id.
func (c *NotificationClient) Get(ctx context.Context, id int64) (*Notification, error) {
	return c.Query().Where(notification.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *NotificationClient) GetX(ctx context.Context, id int64) *Notification {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryNotificationData queries the notification_data edge of a Notification.
func (c *NotificationClient) QueryNotificationData(n *Notification) *NotificationDataQuery {
	query := (&NotificationDataClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := n.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(notification.Table, notification.FieldID, id),
			sqlgraph.To(notificationdata.Table, notificationdata.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, notification.NotificationDataTable, notification.NotificationDataColumn),
		)
		fromV = sqlgraph.Neighbors(n.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *NotificationClient) Hooks() []Hook {
	return c.hooks.Notification
}

// Interceptors returns the client interceptors.
func (c *NotificationClient) Interceptors() []Interceptor {
	return c.inters.Notification
}

func (c *NotificationClient) mutate(ctx context.Context, m *NotificationMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&NotificationCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&NotificationUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&NotificationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&NotificationDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Notification mutation op: %q", m.Op())
	}
}

// NotificationDataClient is a client for the NotificationData schema.
type NotificationDataClient struct {
	config
}

// NewNotificationDataClient returns a client for the NotificationData from the given config.
func NewNotificationDataClient(c config) *NotificationDataClient {
	return &NotificationDataClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `notificationdata.Hooks(f(g(h())))`.
func (c *NotificationDataClient) Use(hooks ...Hook) {
	c.hooks.NotificationData = append(c.hooks.NotificationData, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `notificationdata.Intercept(f(g(h())))`.
func (c *NotificationDataClient) Intercept(interceptors ...Interceptor) {
	c.inters.NotificationData = append(c.inters.NotificationData, interceptors...)
}

// Create returns a builder for creating a NotificationData entity.
func (c *NotificationDataClient) Create() *NotificationDataCreate {
	mutation := newNotificationDataMutation(c.config, OpCreate)
	return &NotificationDataCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of NotificationData entities.
func (c *NotificationDataClient) CreateBulk(builders ...*NotificationDataCreate) *NotificationDataCreateBulk {
	return &NotificationDataCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *NotificationDataClient) MapCreateBulk(slice any, setFunc func(*NotificationDataCreate, int)) *NotificationDataCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &NotificationDataCreateBulk{err: fmt.Errorf("calling to NotificationDataClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*NotificationDataCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &NotificationDataCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for NotificationData.
func (c *NotificationDataClient) Update() *NotificationDataUpdate {
	mutation := newNotificationDataMutation(c.config, OpUpdate)
	return &NotificationDataUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *NotificationDataClient) UpdateOne(nd *NotificationData) *NotificationDataUpdateOne {
	mutation := newNotificationDataMutation(c.config, OpUpdateOne, withNotificationData(nd))
	return &NotificationDataUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *NotificationDataClient) UpdateOneID(id int64) *NotificationDataUpdateOne {
	mutation := newNotificationDataMutation(c.config, OpUpdateOne, withNotificationDataID(id))
	return &NotificationDataUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for NotificationData.
func (c *NotificationDataClient) Delete() *NotificationDataDelete {
	mutation := newNotificationDataMutation(c.config, OpDelete)
	return &NotificationDataDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *NotificationDataClient) DeleteOne(nd *NotificationData) *NotificationDataDeleteOne {
	return c.DeleteOneID(nd.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *NotificationDataClient) DeleteOneID(id int64) *NotificationDataDeleteOne {
	builder := c.Delete().Where(notificationdata.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &NotificationDataDeleteOne{builder}
}

// Query returns a query builder for NotificationData.
func (c *NotificationDataClient) Query() *NotificationDataQuery {
	return &NotificationDataQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeNotificationData},
		inters: c.Interceptors(),
	}
}

// Get returns a NotificationData entity by its id.
func (c *NotificationDataClient) Get(ctx context.Context, id int64) (*NotificationData, error) {
	return c.Query().Where(notificationdata.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *NotificationDataClient) GetX(ctx context.Context, id int64) *NotificationData {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryNotification queries the notification edge of a NotificationData.
func (c *NotificationDataClient) QueryNotification(nd *NotificationData) *NotificationQuery {
	query := (&NotificationClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := nd.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(notificationdata.Table, notificationdata.FieldID, id),
			sqlgraph.To(notification.Table, notification.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, notificationdata.NotificationTable, notificationdata.NotificationColumn),
		)
		fromV = sqlgraph.Neighbors(nd.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *NotificationDataClient) Hooks() []Hook {
	return c.hooks.NotificationData
}

// Interceptors returns the client interceptors.
func (c *NotificationDataClient) Interceptors() []Interceptor {
	return c.inters.NotificationData
}

func (c *NotificationDataClient) mutate(ctx context.Context, m *NotificationDataMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&NotificationDataCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&NotificationDataUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&NotificationDataUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&NotificationDataDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown NotificationData mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Device, LastReadNotification, Notification, NotificationData []ent.Hook
	}
	inters struct {
		Device, LastReadNotification, Notification, NotificationData []ent.Interceptor
	}
)
