// Code generated by ent, DO NOT EDIT.

package ent

import (
	"gitlab.calendaria.team/services/notifications/ent/device"
	"gitlab.calendaria.team/services/notifications/ent/lastreadnotification"
	"gitlab.calendaria.team/services/notifications/ent/notification"
	"gitlab.calendaria.team/services/notifications/ent/notificationdata"
	"gitlab.calendaria.team/services/notifications/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entql"
	"entgo.io/ent/schema/field"
)

// schemaGraph holds a representation of ent/schema at runtime.
var schemaGraph = func() *sqlgraph.Schema {
	graph := &sqlgraph.Schema{Nodes: make([]*sqlgraph.Node, 4)}
	graph.Nodes[0] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   device.Table,
			Columns: device.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: device.FieldID,
			},
		},
		Type: "Device",
		Fields: map[string]*sqlgraph.FieldSpec{
			device.FieldUserID:    {Type: field.TypeInt64, Column: device.FieldUserID},
			device.FieldToken:     {Type: field.TypeString, Column: device.FieldToken},
			device.FieldCreatedAt: {Type: field.TypeTime, Column: device.FieldCreatedAt},
			device.FieldLanguage:  {Type: field.TypeString, Column: device.FieldLanguage},
		},
	}
	graph.Nodes[1] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   lastreadnotification.Table,
			Columns: lastreadnotification.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: lastreadnotification.FieldID,
			},
		},
		Type: "LastReadNotification",
		Fields: map[string]*sqlgraph.FieldSpec{
			lastreadnotification.FieldUserID:     {Type: field.TypeInt64, Column: lastreadnotification.FieldUserID},
			lastreadnotification.FieldType:       {Type: field.TypeString, Column: lastreadnotification.FieldType},
			lastreadnotification.FieldLastReadID: {Type: field.TypeInt64, Column: lastreadnotification.FieldLastReadID},
		},
	}
	graph.Nodes[2] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   notification.Table,
			Columns: notification.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: notification.FieldID,
			},
		},
		Type: "Notification",
		Fields: map[string]*sqlgraph.FieldSpec{
			notification.FieldUserID:             {Type: field.TypeInt64, Column: notification.FieldUserID},
			notification.FieldType:               {Type: field.TypeString, Column: notification.FieldType},
			notification.FieldTitle:              {Type: field.TypeString, Column: notification.FieldTitle},
			notification.FieldText:               {Type: field.TypeString, Column: notification.FieldText},
			notification.FieldEventID:            {Type: field.TypeInt64, Column: notification.FieldEventID},
			notification.FieldContactID:          {Type: field.TypeInt64, Column: notification.FieldContactID},
			notification.FieldTaskID:             {Type: field.TypeInt64, Column: notification.FieldTaskID},
			notification.FieldCreatedAt:          {Type: field.TypeTime, Column: notification.FieldCreatedAt},
			notification.FieldNotificationDataID: {Type: field.TypeInt64, Column: notification.FieldNotificationDataID},
		},
	}
	graph.Nodes[3] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   notificationdata.Table,
			Columns: notificationdata.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: notificationdata.FieldID,
			},
		},
		Type: "NotificationData",
		Fields: map[string]*sqlgraph.FieldSpec{
			notificationdata.FieldType:        {Type: field.TypeString, Column: notificationdata.FieldType},
			notificationdata.FieldEvent:       {Type: field.TypeString, Column: notificationdata.FieldEvent},
			notificationdata.FieldMember:      {Type: field.TypeString, Column: notificationdata.FieldMember},
			notificationdata.FieldChat:        {Type: field.TypeString, Column: notificationdata.FieldChat},
			notificationdata.FieldMessage:     {Type: field.TypeString, Column: notificationdata.FieldMessage},
			notificationdata.FieldContact:     {Type: field.TypeString, Column: notificationdata.FieldContact},
			notificationdata.FieldTask:        {Type: field.TypeString, Column: notificationdata.FieldTask},
			notificationdata.FieldMetadata:    {Type: field.TypeString, Column: notificationdata.FieldMetadata},
			notificationdata.FieldPluralCount: {Type: field.TypeInt64, Column: notificationdata.FieldPluralCount},
		},
	}
	graph.MustAddE(
		"notification_data",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   notification.NotificationDataTable,
			Columns: []string{notification.NotificationDataColumn},
			Bidi:    false,
		},
		"Notification",
		"NotificationData",
	)
	graph.MustAddE(
		"notification",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   notificationdata.NotificationTable,
			Columns: []string{notificationdata.NotificationColumn},
			Bidi:    false,
		},
		"NotificationData",
		"Notification",
	)
	return graph
}()

// predicateAdder wraps the addPredicate method.
// All update, update-one and query builders implement this interface.
type predicateAdder interface {
	addPredicate(func(s *sql.Selector))
}

// addPredicate implements the predicateAdder interface.
func (dq *DeviceQuery) addPredicate(pred func(s *sql.Selector)) {
	dq.predicates = append(dq.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the DeviceQuery builder.
func (dq *DeviceQuery) Filter() *DeviceFilter {
	return &DeviceFilter{config: dq.config, predicateAdder: dq}
}

// addPredicate implements the predicateAdder interface.
func (m *DeviceMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the DeviceMutation builder.
func (m *DeviceMutation) Filter() *DeviceFilter {
	return &DeviceFilter{config: m.config, predicateAdder: m}
}

// DeviceFilter provides a generic filtering capability at runtime for DeviceQuery.
type DeviceFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *DeviceFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[0].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql int64 predicate on the id field.
func (f *DeviceFilter) WhereID(p entql.Int64P) {
	f.Where(p.Field(device.FieldID))
}

// WhereUserID applies the entql int64 predicate on the user_id field.
func (f *DeviceFilter) WhereUserID(p entql.Int64P) {
	f.Where(p.Field(device.FieldUserID))
}

// WhereToken applies the entql string predicate on the token field.
func (f *DeviceFilter) WhereToken(p entql.StringP) {
	f.Where(p.Field(device.FieldToken))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *DeviceFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(device.FieldCreatedAt))
}

// WhereLanguage applies the entql string predicate on the language field.
func (f *DeviceFilter) WhereLanguage(p entql.StringP) {
	f.Where(p.Field(device.FieldLanguage))
}

// addPredicate implements the predicateAdder interface.
func (lrnq *LastReadNotificationQuery) addPredicate(pred func(s *sql.Selector)) {
	lrnq.predicates = append(lrnq.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the LastReadNotificationQuery builder.
func (lrnq *LastReadNotificationQuery) Filter() *LastReadNotificationFilter {
	return &LastReadNotificationFilter{config: lrnq.config, predicateAdder: lrnq}
}

// addPredicate implements the predicateAdder interface.
func (m *LastReadNotificationMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the LastReadNotificationMutation builder.
func (m *LastReadNotificationMutation) Filter() *LastReadNotificationFilter {
	return &LastReadNotificationFilter{config: m.config, predicateAdder: m}
}

// LastReadNotificationFilter provides a generic filtering capability at runtime for LastReadNotificationQuery.
type LastReadNotificationFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *LastReadNotificationFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[1].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql int64 predicate on the id field.
func (f *LastReadNotificationFilter) WhereID(p entql.Int64P) {
	f.Where(p.Field(lastreadnotification.FieldID))
}

// WhereUserID applies the entql int64 predicate on the user_id field.
func (f *LastReadNotificationFilter) WhereUserID(p entql.Int64P) {
	f.Where(p.Field(lastreadnotification.FieldUserID))
}

// WhereType applies the entql string predicate on the type field.
func (f *LastReadNotificationFilter) WhereType(p entql.StringP) {
	f.Where(p.Field(lastreadnotification.FieldType))
}

// WhereLastReadID applies the entql int64 predicate on the last_read_id field.
func (f *LastReadNotificationFilter) WhereLastReadID(p entql.Int64P) {
	f.Where(p.Field(lastreadnotification.FieldLastReadID))
}

// addPredicate implements the predicateAdder interface.
func (nq *NotificationQuery) addPredicate(pred func(s *sql.Selector)) {
	nq.predicates = append(nq.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the NotificationQuery builder.
func (nq *NotificationQuery) Filter() *NotificationFilter {
	return &NotificationFilter{config: nq.config, predicateAdder: nq}
}

// addPredicate implements the predicateAdder interface.
func (m *NotificationMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the NotificationMutation builder.
func (m *NotificationMutation) Filter() *NotificationFilter {
	return &NotificationFilter{config: m.config, predicateAdder: m}
}

// NotificationFilter provides a generic filtering capability at runtime for NotificationQuery.
type NotificationFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *NotificationFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[2].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql int64 predicate on the id field.
func (f *NotificationFilter) WhereID(p entql.Int64P) {
	f.Where(p.Field(notification.FieldID))
}

// WhereUserID applies the entql int64 predicate on the user_id field.
func (f *NotificationFilter) WhereUserID(p entql.Int64P) {
	f.Where(p.Field(notification.FieldUserID))
}

// WhereType applies the entql string predicate on the type field.
func (f *NotificationFilter) WhereType(p entql.StringP) {
	f.Where(p.Field(notification.FieldType))
}

// WhereTitle applies the entql string predicate on the title field.
func (f *NotificationFilter) WhereTitle(p entql.StringP) {
	f.Where(p.Field(notification.FieldTitle))
}

// WhereText applies the entql string predicate on the text field.
func (f *NotificationFilter) WhereText(p entql.StringP) {
	f.Where(p.Field(notification.FieldText))
}

// WhereEventID applies the entql int64 predicate on the event_id field.
func (f *NotificationFilter) WhereEventID(p entql.Int64P) {
	f.Where(p.Field(notification.FieldEventID))
}

// WhereContactID applies the entql int64 predicate on the contact_id field.
func (f *NotificationFilter) WhereContactID(p entql.Int64P) {
	f.Where(p.Field(notification.FieldContactID))
}

// WhereTaskID applies the entql int64 predicate on the task_id field.
func (f *NotificationFilter) WhereTaskID(p entql.Int64P) {
	f.Where(p.Field(notification.FieldTaskID))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *NotificationFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(notification.FieldCreatedAt))
}

// WhereNotificationDataID applies the entql int64 predicate on the notification_data_id field.
func (f *NotificationFilter) WhereNotificationDataID(p entql.Int64P) {
	f.Where(p.Field(notification.FieldNotificationDataID))
}

// WhereHasNotificationData applies a predicate to check if query has an edge notification_data.
func (f *NotificationFilter) WhereHasNotificationData() {
	f.Where(entql.HasEdge("notification_data"))
}

// WhereHasNotificationDataWith applies a predicate to check if query has an edge notification_data with a given conditions (other predicates).
func (f *NotificationFilter) WhereHasNotificationDataWith(preds ...predicate.NotificationData) {
	f.Where(entql.HasEdgeWith("notification_data", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// addPredicate implements the predicateAdder interface.
func (ndq *NotificationDataQuery) addPredicate(pred func(s *sql.Selector)) {
	ndq.predicates = append(ndq.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the NotificationDataQuery builder.
func (ndq *NotificationDataQuery) Filter() *NotificationDataFilter {
	return &NotificationDataFilter{config: ndq.config, predicateAdder: ndq}
}

// addPredicate implements the predicateAdder interface.
func (m *NotificationDataMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the NotificationDataMutation builder.
func (m *NotificationDataMutation) Filter() *NotificationDataFilter {
	return &NotificationDataFilter{config: m.config, predicateAdder: m}
}

// NotificationDataFilter provides a generic filtering capability at runtime for NotificationDataQuery.
type NotificationDataFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *NotificationDataFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[3].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql int64 predicate on the id field.
func (f *NotificationDataFilter) WhereID(p entql.Int64P) {
	f.Where(p.Field(notificationdata.FieldID))
}

// WhereType applies the entql string predicate on the type field.
func (f *NotificationDataFilter) WhereType(p entql.StringP) {
	f.Where(p.Field(notificationdata.FieldType))
}

// WhereEvent applies the entql string predicate on the event field.
func (f *NotificationDataFilter) WhereEvent(p entql.StringP) {
	f.Where(p.Field(notificationdata.FieldEvent))
}

// WhereMember applies the entql string predicate on the member field.
func (f *NotificationDataFilter) WhereMember(p entql.StringP) {
	f.Where(p.Field(notificationdata.FieldMember))
}

// WhereChat applies the entql string predicate on the chat field.
func (f *NotificationDataFilter) WhereChat(p entql.StringP) {
	f.Where(p.Field(notificationdata.FieldChat))
}

// WhereMessage applies the entql string predicate on the message field.
func (f *NotificationDataFilter) WhereMessage(p entql.StringP) {
	f.Where(p.Field(notificationdata.FieldMessage))
}

// WhereContact applies the entql string predicate on the contact field.
func (f *NotificationDataFilter) WhereContact(p entql.StringP) {
	f.Where(p.Field(notificationdata.FieldContact))
}

// WhereTask applies the entql string predicate on the task field.
func (f *NotificationDataFilter) WhereTask(p entql.StringP) {
	f.Where(p.Field(notificationdata.FieldTask))
}

// WhereMetadata applies the entql string predicate on the metadata field.
func (f *NotificationDataFilter) WhereMetadata(p entql.StringP) {
	f.Where(p.Field(notificationdata.FieldMetadata))
}

// WherePluralCount applies the entql int64 predicate on the plural_count field.
func (f *NotificationDataFilter) WherePluralCount(p entql.Int64P) {
	f.Where(p.Field(notificationdata.FieldPluralCount))
}

// WhereHasNotification applies a predicate to check if query has an edge notification.
func (f *NotificationDataFilter) WhereHasNotification() {
	f.Where(entql.HasEdge("notification"))
}

// WhereHasNotificationWith applies a predicate to check if query has an edge notification with a given conditions (other predicates).
func (f *NotificationDataFilter) WhereHasNotificationWith(preds ...predicate.Notification) {
	f.Where(entql.HasEdgeWith("notification", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}
