// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.calendaria.team/services/notifications/ent/enum"
	"gitlab.calendaria.team/services/notifications/ent/lastreadnotification"
	"gitlab.calendaria.team/services/notifications/ent/predicate"
)

// LastReadNotificationUpdate is the builder for updating LastReadNotification entities.
type LastReadNotificationUpdate struct {
	config
	hooks     []Hook
	mutation  *LastReadNotificationMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the LastReadNotificationUpdate builder.
func (lrnu *LastReadNotificationUpdate) Where(ps ...predicate.LastReadNotification) *LastReadNotificationUpdate {
	lrnu.mutation.Where(ps...)
	return lrnu
}

// SetType sets the "type" field.
func (lrnu *LastReadNotificationUpdate) SetType(et enum.NotificationType) *LastReadNotificationUpdate {
	lrnu.mutation.SetType(et)
	return lrnu
}

// SetNillableType sets the "type" field if the given value is not nil.
func (lrnu *LastReadNotificationUpdate) SetNillableType(et *enum.NotificationType) *LastReadNotificationUpdate {
	if et != nil {
		lrnu.SetType(*et)
	}
	return lrnu
}

// SetLastReadID sets the "last_read_id" field.
func (lrnu *LastReadNotificationUpdate) SetLastReadID(i int64) *LastReadNotificationUpdate {
	lrnu.mutation.ResetLastReadID()
	lrnu.mutation.SetLastReadID(i)
	return lrnu
}

// AddLastReadID adds i to the "last_read_id" field.
func (lrnu *LastReadNotificationUpdate) AddLastReadID(i int64) *LastReadNotificationUpdate {
	lrnu.mutation.AddLastReadID(i)
	return lrnu
}

// Mutation returns the LastReadNotificationMutation object of the builder.
func (lrnu *LastReadNotificationUpdate) Mutation() *LastReadNotificationMutation {
	return lrnu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (lrnu *LastReadNotificationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, lrnu.sqlSave, lrnu.mutation, lrnu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (lrnu *LastReadNotificationUpdate) SaveX(ctx context.Context) int {
	affected, err := lrnu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (lrnu *LastReadNotificationUpdate) Exec(ctx context.Context) error {
	_, err := lrnu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lrnu *LastReadNotificationUpdate) ExecX(ctx context.Context) {
	if err := lrnu.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (lrnu *LastReadNotificationUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *LastReadNotificationUpdate {
	lrnu.modifiers = append(lrnu.modifiers, modifiers...)
	return lrnu
}

func (lrnu *LastReadNotificationUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(lastreadnotification.Table, lastreadnotification.Columns, sqlgraph.NewFieldSpec(lastreadnotification.FieldID, field.TypeInt64))
	if ps := lrnu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := lrnu.mutation.GetType(); ok {
		_spec.SetField(lastreadnotification.FieldType, field.TypeString, value)
	}
	if value, ok := lrnu.mutation.LastReadID(); ok {
		_spec.SetField(lastreadnotification.FieldLastReadID, field.TypeInt64, value)
	}
	if value, ok := lrnu.mutation.AddedLastReadID(); ok {
		_spec.AddField(lastreadnotification.FieldLastReadID, field.TypeInt64, value)
	}
	_spec.AddModifiers(lrnu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, lrnu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lastreadnotification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	lrnu.mutation.done = true
	return n, nil
}

// LastReadNotificationUpdateOne is the builder for updating a single LastReadNotification entity.
type LastReadNotificationUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *LastReadNotificationMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetType sets the "type" field.
func (lrnuo *LastReadNotificationUpdateOne) SetType(et enum.NotificationType) *LastReadNotificationUpdateOne {
	lrnuo.mutation.SetType(et)
	return lrnuo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (lrnuo *LastReadNotificationUpdateOne) SetNillableType(et *enum.NotificationType) *LastReadNotificationUpdateOne {
	if et != nil {
		lrnuo.SetType(*et)
	}
	return lrnuo
}

// SetLastReadID sets the "last_read_id" field.
func (lrnuo *LastReadNotificationUpdateOne) SetLastReadID(i int64) *LastReadNotificationUpdateOne {
	lrnuo.mutation.ResetLastReadID()
	lrnuo.mutation.SetLastReadID(i)
	return lrnuo
}

// AddLastReadID adds i to the "last_read_id" field.
func (lrnuo *LastReadNotificationUpdateOne) AddLastReadID(i int64) *LastReadNotificationUpdateOne {
	lrnuo.mutation.AddLastReadID(i)
	return lrnuo
}

// Mutation returns the LastReadNotificationMutation object of the builder.
func (lrnuo *LastReadNotificationUpdateOne) Mutation() *LastReadNotificationMutation {
	return lrnuo.mutation
}

// Where appends a list predicates to the LastReadNotificationUpdate builder.
func (lrnuo *LastReadNotificationUpdateOne) Where(ps ...predicate.LastReadNotification) *LastReadNotificationUpdateOne {
	lrnuo.mutation.Where(ps...)
	return lrnuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (lrnuo *LastReadNotificationUpdateOne) Select(field string, fields ...string) *LastReadNotificationUpdateOne {
	lrnuo.fields = append([]string{field}, fields...)
	return lrnuo
}

// Save executes the query and returns the updated LastReadNotification entity.
func (lrnuo *LastReadNotificationUpdateOne) Save(ctx context.Context) (*LastReadNotification, error) {
	return withHooks(ctx, lrnuo.sqlSave, lrnuo.mutation, lrnuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (lrnuo *LastReadNotificationUpdateOne) SaveX(ctx context.Context) *LastReadNotification {
	node, err := lrnuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (lrnuo *LastReadNotificationUpdateOne) Exec(ctx context.Context) error {
	_, err := lrnuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lrnuo *LastReadNotificationUpdateOne) ExecX(ctx context.Context) {
	if err := lrnuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (lrnuo *LastReadNotificationUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *LastReadNotificationUpdateOne {
	lrnuo.modifiers = append(lrnuo.modifiers, modifiers...)
	return lrnuo
}

func (lrnuo *LastReadNotificationUpdateOne) sqlSave(ctx context.Context) (_node *LastReadNotification, err error) {
	_spec := sqlgraph.NewUpdateSpec(lastreadnotification.Table, lastreadnotification.Columns, sqlgraph.NewFieldSpec(lastreadnotification.FieldID, field.TypeInt64))
	id, ok := lrnuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LastReadNotification.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := lrnuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lastreadnotification.FieldID)
		for _, f := range fields {
			if !lastreadnotification.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != lastreadnotification.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := lrnuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := lrnuo.mutation.GetType(); ok {
		_spec.SetField(lastreadnotification.FieldType, field.TypeString, value)
	}
	if value, ok := lrnuo.mutation.LastReadID(); ok {
		_spec.SetField(lastreadnotification.FieldLastReadID, field.TypeInt64, value)
	}
	if value, ok := lrnuo.mutation.AddedLastReadID(); ok {
		_spec.AddField(lastreadnotification.FieldLastReadID, field.TypeInt64, value)
	}
	_spec.AddModifiers(lrnuo.modifiers...)
	_node = &LastReadNotification{config: lrnuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, lrnuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lastreadnotification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	lrnuo.mutation.done = true
	return _node, nil
}
