// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/makesalekz/notifications/ent/lastreadnotification"
	"github.com/makesalekz/notifications/ent/predicate"
)

// LastReadNotificationQuery is the builder for querying LastReadNotification entities.
type LastReadNotificationQuery struct {
	config
	ctx        *QueryContext
	order      []lastreadnotification.OrderOption
	inters     []Interceptor
	predicates []predicate.LastReadNotification
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LastReadNotificationQuery builder.
func (lrnq *LastReadNotificationQuery) Where(ps ...predicate.LastReadNotification) *LastReadNotificationQuery {
	lrnq.predicates = append(lrnq.predicates, ps...)
	return lrnq
}

// Limit the number of records to be returned by this query.
func (lrnq *LastReadNotificationQuery) Limit(limit int) *LastReadNotificationQuery {
	lrnq.ctx.Limit = &limit
	return lrnq
}

// Offset to start from.
func (lrnq *LastReadNotificationQuery) Offset(offset int) *LastReadNotificationQuery {
	lrnq.ctx.Offset = &offset
	return lrnq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (lrnq *LastReadNotificationQuery) Unique(unique bool) *LastReadNotificationQuery {
	lrnq.ctx.Unique = &unique
	return lrnq
}

// Order specifies how the records should be ordered.
func (lrnq *LastReadNotificationQuery) Order(o ...lastreadnotification.OrderOption) *LastReadNotificationQuery {
	lrnq.order = append(lrnq.order, o...)
	return lrnq
}

// First returns the first LastReadNotification entity from the query.
// Returns a *NotFoundError when no LastReadNotification was found.
func (lrnq *LastReadNotificationQuery) First(ctx context.Context) (*LastReadNotification, error) {
	nodes, err := lrnq.Limit(1).All(setContextOp(ctx, lrnq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{lastreadnotification.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (lrnq *LastReadNotificationQuery) FirstX(ctx context.Context) *LastReadNotification {
	node, err := lrnq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first LastReadNotification ID from the query.
// Returns a *NotFoundError when no LastReadNotification ID was found.
func (lrnq *LastReadNotificationQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = lrnq.Limit(1).IDs(setContextOp(ctx, lrnq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{lastreadnotification.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (lrnq *LastReadNotificationQuery) FirstIDX(ctx context.Context) int64 {
	id, err := lrnq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single LastReadNotification entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one LastReadNotification entity is found.
// Returns a *NotFoundError when no LastReadNotification entities are found.
func (lrnq *LastReadNotificationQuery) Only(ctx context.Context) (*LastReadNotification, error) {
	nodes, err := lrnq.Limit(2).All(setContextOp(ctx, lrnq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{lastreadnotification.Label}
	default:
		return nil, &NotSingularError{lastreadnotification.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (lrnq *LastReadNotificationQuery) OnlyX(ctx context.Context) *LastReadNotification {
	node, err := lrnq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only LastReadNotification ID in the query.
// Returns a *NotSingularError when more than one LastReadNotification ID is found.
// Returns a *NotFoundError when no entities are found.
func (lrnq *LastReadNotificationQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = lrnq.Limit(2).IDs(setContextOp(ctx, lrnq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{lastreadnotification.Label}
	default:
		err = &NotSingularError{lastreadnotification.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (lrnq *LastReadNotificationQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := lrnq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of LastReadNotifications.
func (lrnq *LastReadNotificationQuery) All(ctx context.Context) ([]*LastReadNotification, error) {
	ctx = setContextOp(ctx, lrnq.ctx, ent.OpQueryAll)
	if err := lrnq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*LastReadNotification, *LastReadNotificationQuery]()
	return withInterceptors[[]*LastReadNotification](ctx, lrnq, qr, lrnq.inters)
}

// AllX is like All, but panics if an error occurs.
func (lrnq *LastReadNotificationQuery) AllX(ctx context.Context) []*LastReadNotification {
	nodes, err := lrnq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of LastReadNotification IDs.
func (lrnq *LastReadNotificationQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if lrnq.ctx.Unique == nil && lrnq.path != nil {
		lrnq.Unique(true)
	}
	ctx = setContextOp(ctx, lrnq.ctx, ent.OpQueryIDs)
	if err = lrnq.Select(lastreadnotification.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (lrnq *LastReadNotificationQuery) IDsX(ctx context.Context) []int64 {
	ids, err := lrnq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (lrnq *LastReadNotificationQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, lrnq.ctx, ent.OpQueryCount)
	if err := lrnq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, lrnq, querierCount[*LastReadNotificationQuery](), lrnq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (lrnq *LastReadNotificationQuery) CountX(ctx context.Context) int {
	count, err := lrnq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (lrnq *LastReadNotificationQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, lrnq.ctx, ent.OpQueryExist)
	switch _, err := lrnq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (lrnq *LastReadNotificationQuery) ExistX(ctx context.Context) bool {
	exist, err := lrnq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LastReadNotificationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (lrnq *LastReadNotificationQuery) Clone() *LastReadNotificationQuery {
	if lrnq == nil {
		return nil
	}
	return &LastReadNotificationQuery{
		config:     lrnq.config,
		ctx:        lrnq.ctx.Clone(),
		order:      append([]lastreadnotification.OrderOption{}, lrnq.order...),
		inters:     append([]Interceptor{}, lrnq.inters...),
		predicates: append([]predicate.LastReadNotification{}, lrnq.predicates...),
		// clone intermediate query.
		sql:       lrnq.sql.Clone(),
		path:      lrnq.path,
		modifiers: append([]func(*sql.Selector){}, lrnq.modifiers...),
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID int64 `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.LastReadNotification.Query().
//		GroupBy(lastreadnotification.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (lrnq *LastReadNotificationQuery) GroupBy(field string, fields ...string) *LastReadNotificationGroupBy {
	lrnq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &LastReadNotificationGroupBy{build: lrnq}
	grbuild.flds = &lrnq.ctx.Fields
	grbuild.label = lastreadnotification.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID int64 `json:"user_id,omitempty"`
//	}
//
//	client.LastReadNotification.Query().
//		Select(lastreadnotification.FieldUserID).
//		Scan(ctx, &v)
func (lrnq *LastReadNotificationQuery) Select(fields ...string) *LastReadNotificationSelect {
	lrnq.ctx.Fields = append(lrnq.ctx.Fields, fields...)
	sbuild := &LastReadNotificationSelect{LastReadNotificationQuery: lrnq}
	sbuild.label = lastreadnotification.Label
	sbuild.flds, sbuild.scan = &lrnq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a LastReadNotificationSelect configured with the given aggregations.
func (lrnq *LastReadNotificationQuery) Aggregate(fns ...AggregateFunc) *LastReadNotificationSelect {
	return lrnq.Select().Aggregate(fns...)
}

func (lrnq *LastReadNotificationQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range lrnq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, lrnq); err != nil {
				return err
			}
		}
	}
	for _, f := range lrnq.ctx.Fields {
		if !lastreadnotification.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if lrnq.path != nil {
		prev, err := lrnq.path(ctx)
		if err != nil {
			return err
		}
		lrnq.sql = prev
	}
	return nil
}

func (lrnq *LastReadNotificationQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*LastReadNotification, error) {
	var (
		nodes = []*LastReadNotification{}
		_spec = lrnq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*LastReadNotification).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &LastReadNotification{config: lrnq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(lrnq.modifiers) > 0 {
		_spec.Modifiers = lrnq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, lrnq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (lrnq *LastReadNotificationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := lrnq.querySpec()
	if len(lrnq.modifiers) > 0 {
		_spec.Modifiers = lrnq.modifiers
	}
	_spec.Node.Columns = lrnq.ctx.Fields
	if len(lrnq.ctx.Fields) > 0 {
		_spec.Unique = lrnq.ctx.Unique != nil && *lrnq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, lrnq.driver, _spec)
}

func (lrnq *LastReadNotificationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(lastreadnotification.Table, lastreadnotification.Columns, sqlgraph.NewFieldSpec(lastreadnotification.FieldID, field.TypeInt64))
	_spec.From = lrnq.sql
	if unique := lrnq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if lrnq.path != nil {
		_spec.Unique = true
	}
	if fields := lrnq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lastreadnotification.FieldID)
		for i := range fields {
			if fields[i] != lastreadnotification.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := lrnq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := lrnq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := lrnq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := lrnq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (lrnq *LastReadNotificationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(lrnq.driver.Dialect())
	t1 := builder.Table(lastreadnotification.Table)
	columns := lrnq.ctx.Fields
	if len(columns) == 0 {
		columns = lastreadnotification.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if lrnq.sql != nil {
		selector = lrnq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if lrnq.ctx.Unique != nil && *lrnq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range lrnq.modifiers {
		m(selector)
	}
	for _, p := range lrnq.predicates {
		p(selector)
	}
	for _, p := range lrnq.order {
		p(selector)
	}
	if offset := lrnq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := lrnq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (lrnq *LastReadNotificationQuery) Modify(modifiers ...func(s *sql.Selector)) *LastReadNotificationSelect {
	lrnq.modifiers = append(lrnq.modifiers, modifiers...)
	return lrnq.Select()
}

// LastReadNotificationGroupBy is the group-by builder for LastReadNotification entities.
type LastReadNotificationGroupBy struct {
	selector
	build *LastReadNotificationQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (lrngb *LastReadNotificationGroupBy) Aggregate(fns ...AggregateFunc) *LastReadNotificationGroupBy {
	lrngb.fns = append(lrngb.fns, fns...)
	return lrngb
}

// Scan applies the selector query and scans the result into the given value.
func (lrngb *LastReadNotificationGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, lrngb.build.ctx, ent.OpQueryGroupBy)
	if err := lrngb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LastReadNotificationQuery, *LastReadNotificationGroupBy](ctx, lrngb.build, lrngb, lrngb.build.inters, v)
}

func (lrngb *LastReadNotificationGroupBy) sqlScan(ctx context.Context, root *LastReadNotificationQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(lrngb.fns))
	for _, fn := range lrngb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*lrngb.flds)+len(lrngb.fns))
		for _, f := range *lrngb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*lrngb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lrngb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// LastReadNotificationSelect is the builder for selecting fields of LastReadNotification entities.
type LastReadNotificationSelect struct {
	*LastReadNotificationQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (lrns *LastReadNotificationSelect) Aggregate(fns ...AggregateFunc) *LastReadNotificationSelect {
	lrns.fns = append(lrns.fns, fns...)
	return lrns
}

// Scan applies the selector query and scans the result into the given value.
func (lrns *LastReadNotificationSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, lrns.ctx, ent.OpQuerySelect)
	if err := lrns.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LastReadNotificationQuery, *LastReadNotificationSelect](ctx, lrns.LastReadNotificationQuery, lrns, lrns.inters, v)
}

func (lrns *LastReadNotificationSelect) sqlScan(ctx context.Context, root *LastReadNotificationQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(lrns.fns))
	for _, fn := range lrns.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*lrns.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lrns.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (lrns *LastReadNotificationSelect) Modify(modifiers ...func(s *sql.Selector)) *LastReadNotificationSelect {
	lrns.modifiers = append(lrns.modifiers, modifiers...)
	return lrns
}
