// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.calendaria.team/services/notifications/ent/enum"
	"gitlab.calendaria.team/services/notifications/ent/notification"
	"gitlab.calendaria.team/services/notifications/ent/notificationdata"
)

// NotificationCreate is the builder for creating a Notification entity.
type NotificationCreate struct {
	config
	mutation *NotificationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (nc *NotificationCreate) SetUserID(i int64) *NotificationCreate {
	nc.mutation.SetUserID(i)
	return nc
}

// SetType sets the "type" field.
func (nc *NotificationCreate) SetType(et enum.NotificationType) *NotificationCreate {
	nc.mutation.SetType(et)
	return nc
}

// SetNillableType sets the "type" field if the given value is not nil.
func (nc *NotificationCreate) SetNillableType(et *enum.NotificationType) *NotificationCreate {
	if et != nil {
		nc.SetType(*et)
	}
	return nc
}

// SetTitle sets the "title" field.
func (nc *NotificationCreate) SetTitle(s string) *NotificationCreate {
	nc.mutation.SetTitle(s)
	return nc
}

// SetText sets the "text" field.
func (nc *NotificationCreate) SetText(s string) *NotificationCreate {
	nc.mutation.SetText(s)
	return nc
}

// SetEventID sets the "event_id" field.
func (nc *NotificationCreate) SetEventID(i int64) *NotificationCreate {
	nc.mutation.SetEventID(i)
	return nc
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (nc *NotificationCreate) SetNillableEventID(i *int64) *NotificationCreate {
	if i != nil {
		nc.SetEventID(*i)
	}
	return nc
}

// SetContactID sets the "contact_id" field.
func (nc *NotificationCreate) SetContactID(i int64) *NotificationCreate {
	nc.mutation.SetContactID(i)
	return nc
}

// SetNillableContactID sets the "contact_id" field if the given value is not nil.
func (nc *NotificationCreate) SetNillableContactID(i *int64) *NotificationCreate {
	if i != nil {
		nc.SetContactID(*i)
	}
	return nc
}

// SetTaskID sets the "task_id" field.
func (nc *NotificationCreate) SetTaskID(i int64) *NotificationCreate {
	nc.mutation.SetTaskID(i)
	return nc
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (nc *NotificationCreate) SetNillableTaskID(i *int64) *NotificationCreate {
	if i != nil {
		nc.SetTaskID(*i)
	}
	return nc
}

// SetCreatedAt sets the "created_at" field.
func (nc *NotificationCreate) SetCreatedAt(t time.Time) *NotificationCreate {
	nc.mutation.SetCreatedAt(t)
	return nc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (nc *NotificationCreate) SetNillableCreatedAt(t *time.Time) *NotificationCreate {
	if t != nil {
		nc.SetCreatedAt(*t)
	}
	return nc
}

// SetNotificationDataID sets the "notification_data_id" field.
func (nc *NotificationCreate) SetNotificationDataID(i int64) *NotificationCreate {
	nc.mutation.SetNotificationDataID(i)
	return nc
}

// SetNillableNotificationDataID sets the "notification_data_id" field if the given value is not nil.
func (nc *NotificationCreate) SetNillableNotificationDataID(i *int64) *NotificationCreate {
	if i != nil {
		nc.SetNotificationDataID(*i)
	}
	return nc
}

// SetNotificationData sets the "notification_data" edge to the NotificationData entity.
func (nc *NotificationCreate) SetNotificationData(n *NotificationData) *NotificationCreate {
	return nc.SetNotificationDataID(n.ID)
}

// Mutation returns the NotificationMutation object of the builder.
func (nc *NotificationCreate) Mutation() *NotificationMutation {
	return nc.mutation
}

// Save creates the Notification in the database.
func (nc *NotificationCreate) Save(ctx context.Context) (*Notification, error) {
	nc.defaults()
	return withHooks(ctx, nc.sqlSave, nc.mutation, nc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (nc *NotificationCreate) SaveX(ctx context.Context) *Notification {
	v, err := nc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (nc *NotificationCreate) Exec(ctx context.Context) error {
	_, err := nc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nc *NotificationCreate) ExecX(ctx context.Context) {
	if err := nc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (nc *NotificationCreate) defaults() {
	if _, ok := nc.mutation.GetType(); !ok {
		v := notification.DefaultType
		nc.mutation.SetType(v)
	}
	if _, ok := nc.mutation.CreatedAt(); !ok {
		v := notification.DefaultCreatedAt()
		nc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nc *NotificationCreate) check() error {
	if _, ok := nc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Notification.user_id"`)}
	}
	if v, ok := nc.mutation.UserID(); ok {
		if err := notification.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Notification.user_id": %w`, err)}
		}
	}
	if _, ok := nc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Notification.type"`)}
	}
	if _, ok := nc.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Notification.title"`)}
	}
	if v, ok := nc.mutation.Title(); ok {
		if err := notification.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Notification.title": %w`, err)}
		}
	}
	if _, ok := nc.mutation.Text(); !ok {
		return &ValidationError{Name: "text", err: errors.New(`ent: missing required field "Notification.text"`)}
	}
	if v, ok := nc.mutation.Text(); ok {
		if err := notification.TextValidator(v); err != nil {
			return &ValidationError{Name: "text", err: fmt.Errorf(`ent: validator failed for field "Notification.text": %w`, err)}
		}
	}
	if _, ok := nc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Notification.created_at"`)}
	}
	return nil
}

func (nc *NotificationCreate) sqlSave(ctx context.Context) (*Notification, error) {
	if err := nc.check(); err != nil {
		return nil, err
	}
	_node, _spec := nc.createSpec()
	if err := sqlgraph.CreateNode(ctx, nc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	nc.mutation.id = &_node.ID
	nc.mutation.done = true
	return _node, nil
}

func (nc *NotificationCreate) createSpec() (*Notification, *sqlgraph.CreateSpec) {
	var (
		_node = &Notification{config: nc.config}
		_spec = sqlgraph.NewCreateSpec(notification.Table, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = nc.conflict
	if value, ok := nc.mutation.UserID(); ok {
		_spec.SetField(notification.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := nc.mutation.GetType(); ok {
		_spec.SetField(notification.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := nc.mutation.Title(); ok {
		_spec.SetField(notification.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := nc.mutation.Text(); ok {
		_spec.SetField(notification.FieldText, field.TypeString, value)
		_node.Text = value
	}
	if value, ok := nc.mutation.EventID(); ok {
		_spec.SetField(notification.FieldEventID, field.TypeInt64, value)
		_node.EventID = &value
	}
	if value, ok := nc.mutation.ContactID(); ok {
		_spec.SetField(notification.FieldContactID, field.TypeInt64, value)
		_node.ContactID = &value
	}
	if value, ok := nc.mutation.TaskID(); ok {
		_spec.SetField(notification.FieldTaskID, field.TypeInt64, value)
		_node.TaskID = &value
	}
	if value, ok := nc.mutation.CreatedAt(); ok {
		_spec.SetField(notification.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := nc.mutation.NotificationDataIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   notification.NotificationDataTable,
			Columns: []string{notification.NotificationDataColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationdata.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.NotificationDataID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Notification.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NotificationUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (nc *NotificationCreate) OnConflict(opts ...sql.ConflictOption) *NotificationUpsertOne {
	nc.conflict = opts
	return &NotificationUpsertOne{
		create: nc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Notification.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (nc *NotificationCreate) OnConflictColumns(columns ...string) *NotificationUpsertOne {
	nc.conflict = append(nc.conflict, sql.ConflictColumns(columns...))
	return &NotificationUpsertOne{
		create: nc,
	}
}

type (
	// NotificationUpsertOne is the builder for "upsert"-ing
	//  one Notification node.
	NotificationUpsertOne struct {
		create *NotificationCreate
	}

	// NotificationUpsert is the "OnConflict" setter.
	NotificationUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *NotificationUpsert) SetUserID(v int64) *NotificationUpsert {
	u.Set(notification.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *NotificationUpsert) UpdateUserID() *NotificationUpsert {
	u.SetExcluded(notification.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *NotificationUpsert) AddUserID(v int64) *NotificationUpsert {
	u.Add(notification.FieldUserID, v)
	return u
}

// SetType sets the "type" field.
func (u *NotificationUpsert) SetType(v enum.NotificationType) *NotificationUpsert {
	u.Set(notification.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *NotificationUpsert) UpdateType() *NotificationUpsert {
	u.SetExcluded(notification.FieldType)
	return u
}

// SetTitle sets the "title" field.
func (u *NotificationUpsert) SetTitle(v string) *NotificationUpsert {
	u.Set(notification.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *NotificationUpsert) UpdateTitle() *NotificationUpsert {
	u.SetExcluded(notification.FieldTitle)
	return u
}

// SetText sets the "text" field.
func (u *NotificationUpsert) SetText(v string) *NotificationUpsert {
	u.Set(notification.FieldText, v)
	return u
}

// UpdateText sets the "text" field to the value that was provided on create.
func (u *NotificationUpsert) UpdateText() *NotificationUpsert {
	u.SetExcluded(notification.FieldText)
	return u
}

// SetEventID sets the "event_id" field.
func (u *NotificationUpsert) SetEventID(v int64) *NotificationUpsert {
	u.Set(notification.FieldEventID, v)
	return u
}

// UpdateEventID sets the "event_id" field to the value that was provided on create.
func (u *NotificationUpsert) UpdateEventID() *NotificationUpsert {
	u.SetExcluded(notification.FieldEventID)
	return u
}

// AddEventID adds v to the "event_id" field.
func (u *NotificationUpsert) AddEventID(v int64) *NotificationUpsert {
	u.Add(notification.FieldEventID, v)
	return u
}

// ClearEventID clears the value of the "event_id" field.
func (u *NotificationUpsert) ClearEventID() *NotificationUpsert {
	u.SetNull(notification.FieldEventID)
	return u
}

// SetContactID sets the "contact_id" field.
func (u *NotificationUpsert) SetContactID(v int64) *NotificationUpsert {
	u.Set(notification.FieldContactID, v)
	return u
}

// UpdateContactID sets the "contact_id" field to the value that was provided on create.
func (u *NotificationUpsert) UpdateContactID() *NotificationUpsert {
	u.SetExcluded(notification.FieldContactID)
	return u
}

// AddContactID adds v to the "contact_id" field.
func (u *NotificationUpsert) AddContactID(v int64) *NotificationUpsert {
	u.Add(notification.FieldContactID, v)
	return u
}

// ClearContactID clears the value of the "contact_id" field.
func (u *NotificationUpsert) ClearContactID() *NotificationUpsert {
	u.SetNull(notification.FieldContactID)
	return u
}

// SetTaskID sets the "task_id" field.
func (u *NotificationUpsert) SetTaskID(v int64) *NotificationUpsert {
	u.Set(notification.FieldTaskID, v)
	return u
}

// UpdateTaskID sets the "task_id" field to the value that was provided on create.
func (u *NotificationUpsert) UpdateTaskID() *NotificationUpsert {
	u.SetExcluded(notification.FieldTaskID)
	return u
}

// AddTaskID adds v to the "task_id" field.
func (u *NotificationUpsert) AddTaskID(v int64) *NotificationUpsert {
	u.Add(notification.FieldTaskID, v)
	return u
}

// ClearTaskID clears the value of the "task_id" field.
func (u *NotificationUpsert) ClearTaskID() *NotificationUpsert {
	u.SetNull(notification.FieldTaskID)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *NotificationUpsert) SetCreatedAt(v time.Time) *NotificationUpsert {
	u.Set(notification.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *NotificationUpsert) UpdateCreatedAt() *NotificationUpsert {
	u.SetExcluded(notification.FieldCreatedAt)
	return u
}

// SetNotificationDataID sets the "notification_data_id" field.
func (u *NotificationUpsert) SetNotificationDataID(v int64) *NotificationUpsert {
	u.Set(notification.FieldNotificationDataID, v)
	return u
}

// UpdateNotificationDataID sets the "notification_data_id" field to the value that was provided on create.
func (u *NotificationUpsert) UpdateNotificationDataID() *NotificationUpsert {
	u.SetExcluded(notification.FieldNotificationDataID)
	return u
}

// ClearNotificationDataID clears the value of the "notification_data_id" field.
func (u *NotificationUpsert) ClearNotificationDataID() *NotificationUpsert {
	u.SetNull(notification.FieldNotificationDataID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Notification.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *NotificationUpsertOne) UpdateNewValues() *NotificationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Notification.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *NotificationUpsertOne) Ignore() *NotificationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NotificationUpsertOne) DoNothing() *NotificationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NotificationCreate.OnConflict
// documentation for more info.
func (u *NotificationUpsertOne) Update(set func(*NotificationUpsert)) *NotificationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NotificationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *NotificationUpsertOne) SetUserID(v int64) *NotificationUpsertOne {
	return u.Update(func(s *NotificationUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *NotificationUpsertOne) AddUserID(v int64) *NotificationUpsertOne {
	return u.Update(func(s *NotificationUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *NotificationUpsertOne) UpdateUserID() *NotificationUpsertOne {
	return u.Update(func(s *NotificationUpsert) {
		s.UpdateUserID()
	})
}

// SetType sets the "type" field.
func (u *NotificationUpsertOne) SetType(v enum.NotificationType) *NotificationUpsertOne {
	return u.Update(func(s *NotificationUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *NotificationUpsertOne) UpdateType() *NotificationUpsertOne {
	return u.Update(func(s *NotificationUpsert) {
		s.UpdateType()
	})
}

// SetTitle sets the "title" field.
func (u *NotificationUpsertOne) SetTitle(v string) *NotificationUpsertOne {
	return u.Update(func(s *NotificationUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *NotificationUpsertOne) UpdateTitle() *NotificationUpsertOne {
	return u.Update(func(s *NotificationUpsert) {
		s.UpdateTitle()
	})
}

// SetText sets the "text" field.
func (u *NotificationUpsertOne) SetText(v string) *NotificationUpsertOne {
	return u.Update(func(s *NotificationUpsert) {
		s.SetText(v)
	})
}

// UpdateText sets the "text" field to the value that was provided on create.
func (u *NotificationUpsertOne) UpdateText() *NotificationUpsertOne {
	return u.Update(func(s *NotificationUpsert) {
		s.UpdateText()
	})
}

// SetEventID sets the "event_id" field.
func (u *NotificationUpsertOne) SetEventID(v int64) *NotificationUpsertOne {
	return u.Update(func(s *NotificationUpsert) {
		s.SetEventID(v)
	})
}

// AddEventID adds v to the "event_id" field.
func (u *NotificationUpsertOne) AddEventID(v int64) *NotificationUpsertOne {
	return u.Update(func(s *NotificationUpsert) {
		s.AddEventID(v)
	})
}

// UpdateEventID sets the "event_id" field to the value that was provided on create.
func (u *NotificationUpsertOne) UpdateEventID() *NotificationUpsertOne {
	return u.Update(func(s *NotificationUpsert) {
		s.UpdateEventID()
	})
}

// ClearEventID clears the value of the "event_id" field.
func (u *NotificationUpsertOne) ClearEventID() *NotificationUpsertOne {
	return u.Update(func(s *NotificationUpsert) {
		s.ClearEventID()
	})
}

// SetContactID sets the "contact_id" field.
func (u *NotificationUpsertOne) SetContactID(v int64) *NotificationUpsertOne {
	return u.Update(func(s *NotificationUpsert) {
		s.SetContactID(v)
	})
}

// AddContactID adds v to the "contact_id" field.
func (u *NotificationUpsertOne) AddContactID(v int64) *NotificationUpsertOne {
	return u.Update(func(s *NotificationUpsert) {
		s.AddContactID(v)
	})
}

// UpdateContactID sets the "contact_id" field to the value that was provided on create.
func (u *NotificationUpsertOne) UpdateContactID() *NotificationUpsertOne {
	return u.Update(func(s *NotificationUpsert) {
		s.UpdateContactID()
	})
}

// ClearContactID clears the value of the "contact_id" field.
func (u *NotificationUpsertOne) ClearContactID() *NotificationUpsertOne {
	return u.Update(func(s *NotificationUpsert) {
		s.ClearContactID()
	})
}

// SetTaskID sets the "task_id" field.
func (u *NotificationUpsertOne) SetTaskID(v int64) *NotificationUpsertOne {
	return u.Update(func(s *NotificationUpsert) {
		s.SetTaskID(v)
	})
}

// AddTaskID adds v to the "task_id" field.
func (u *NotificationUpsertOne) AddTaskID(v int64) *NotificationUpsertOne {
	return u.Update(func(s *NotificationUpsert) {
		s.AddTaskID(v)
	})
}

// UpdateTaskID sets the "task_id" field to the value that was provided on create.
func (u *NotificationUpsertOne) UpdateTaskID() *NotificationUpsertOne {
	return u.Update(func(s *NotificationUpsert) {
		s.UpdateTaskID()
	})
}

// ClearTaskID clears the value of the "task_id" field.
func (u *NotificationUpsertOne) ClearTaskID() *NotificationUpsertOne {
	return u.Update(func(s *NotificationUpsert) {
		s.ClearTaskID()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *NotificationUpsertOne) SetCreatedAt(v time.Time) *NotificationUpsertOne {
	return u.Update(func(s *NotificationUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *NotificationUpsertOne) UpdateCreatedAt() *NotificationUpsertOne {
	return u.Update(func(s *NotificationUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetNotificationDataID sets the "notification_data_id" field.
func (u *NotificationUpsertOne) SetNotificationDataID(v int64) *NotificationUpsertOne {
	return u.Update(func(s *NotificationUpsert) {
		s.SetNotificationDataID(v)
	})
}

// UpdateNotificationDataID sets the "notification_data_id" field to the value that was provided on create.
func (u *NotificationUpsertOne) UpdateNotificationDataID() *NotificationUpsertOne {
	return u.Update(func(s *NotificationUpsert) {
		s.UpdateNotificationDataID()
	})
}

// ClearNotificationDataID clears the value of the "notification_data_id" field.
func (u *NotificationUpsertOne) ClearNotificationDataID() *NotificationUpsertOne {
	return u.Update(func(s *NotificationUpsert) {
		s.ClearNotificationDataID()
	})
}

// Exec executes the query.
func (u *NotificationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NotificationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NotificationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *NotificationUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *NotificationUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// NotificationCreateBulk is the builder for creating many Notification entities in bulk.
type NotificationCreateBulk struct {
	config
	err      error
	builders []*NotificationCreate
	conflict []sql.ConflictOption
}

// Save creates the Notification entities in the database.
func (ncb *NotificationCreateBulk) Save(ctx context.Context) ([]*Notification, error) {
	if ncb.err != nil {
		return nil, ncb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ncb.builders))
	nodes := make([]*Notification, len(ncb.builders))
	mutators := make([]Mutator, len(ncb.builders))
	for i := range ncb.builders {
		func(i int, root context.Context) {
			builder := ncb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NotificationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ncb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = ncb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ncb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ncb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ncb *NotificationCreateBulk) SaveX(ctx context.Context) []*Notification {
	v, err := ncb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ncb *NotificationCreateBulk) Exec(ctx context.Context) error {
	_, err := ncb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ncb *NotificationCreateBulk) ExecX(ctx context.Context) {
	if err := ncb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Notification.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NotificationUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (ncb *NotificationCreateBulk) OnConflict(opts ...sql.ConflictOption) *NotificationUpsertBulk {
	ncb.conflict = opts
	return &NotificationUpsertBulk{
		create: ncb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Notification.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ncb *NotificationCreateBulk) OnConflictColumns(columns ...string) *NotificationUpsertBulk {
	ncb.conflict = append(ncb.conflict, sql.ConflictColumns(columns...))
	return &NotificationUpsertBulk{
		create: ncb,
	}
}

// NotificationUpsertBulk is the builder for "upsert"-ing
// a bulk of Notification nodes.
type NotificationUpsertBulk struct {
	create *NotificationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Notification.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *NotificationUpsertBulk) UpdateNewValues() *NotificationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Notification.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *NotificationUpsertBulk) Ignore() *NotificationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NotificationUpsertBulk) DoNothing() *NotificationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NotificationCreateBulk.OnConflict
// documentation for more info.
func (u *NotificationUpsertBulk) Update(set func(*NotificationUpsert)) *NotificationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NotificationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *NotificationUpsertBulk) SetUserID(v int64) *NotificationUpsertBulk {
	return u.Update(func(s *NotificationUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *NotificationUpsertBulk) AddUserID(v int64) *NotificationUpsertBulk {
	return u.Update(func(s *NotificationUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *NotificationUpsertBulk) UpdateUserID() *NotificationUpsertBulk {
	return u.Update(func(s *NotificationUpsert) {
		s.UpdateUserID()
	})
}

// SetType sets the "type" field.
func (u *NotificationUpsertBulk) SetType(v enum.NotificationType) *NotificationUpsertBulk {
	return u.Update(func(s *NotificationUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *NotificationUpsertBulk) UpdateType() *NotificationUpsertBulk {
	return u.Update(func(s *NotificationUpsert) {
		s.UpdateType()
	})
}

// SetTitle sets the "title" field.
func (u *NotificationUpsertBulk) SetTitle(v string) *NotificationUpsertBulk {
	return u.Update(func(s *NotificationUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *NotificationUpsertBulk) UpdateTitle() *NotificationUpsertBulk {
	return u.Update(func(s *NotificationUpsert) {
		s.UpdateTitle()
	})
}

// SetText sets the "text" field.
func (u *NotificationUpsertBulk) SetText(v string) *NotificationUpsertBulk {
	return u.Update(func(s *NotificationUpsert) {
		s.SetText(v)
	})
}

// UpdateText sets the "text" field to the value that was provided on create.
func (u *NotificationUpsertBulk) UpdateText() *NotificationUpsertBulk {
	return u.Update(func(s *NotificationUpsert) {
		s.UpdateText()
	})
}

// SetEventID sets the "event_id" field.
func (u *NotificationUpsertBulk) SetEventID(v int64) *NotificationUpsertBulk {
	return u.Update(func(s *NotificationUpsert) {
		s.SetEventID(v)
	})
}

// AddEventID adds v to the "event_id" field.
func (u *NotificationUpsertBulk) AddEventID(v int64) *NotificationUpsertBulk {
	return u.Update(func(s *NotificationUpsert) {
		s.AddEventID(v)
	})
}

// UpdateEventID sets the "event_id" field to the value that was provided on create.
func (u *NotificationUpsertBulk) UpdateEventID() *NotificationUpsertBulk {
	return u.Update(func(s *NotificationUpsert) {
		s.UpdateEventID()
	})
}

// ClearEventID clears the value of the "event_id" field.
func (u *NotificationUpsertBulk) ClearEventID() *NotificationUpsertBulk {
	return u.Update(func(s *NotificationUpsert) {
		s.ClearEventID()
	})
}

// SetContactID sets the "contact_id" field.
func (u *NotificationUpsertBulk) SetContactID(v int64) *NotificationUpsertBulk {
	return u.Update(func(s *NotificationUpsert) {
		s.SetContactID(v)
	})
}

// AddContactID adds v to the "contact_id" field.
func (u *NotificationUpsertBulk) AddContactID(v int64) *NotificationUpsertBulk {
	return u.Update(func(s *NotificationUpsert) {
		s.AddContactID(v)
	})
}

// UpdateContactID sets the "contact_id" field to the value that was provided on create.
func (u *NotificationUpsertBulk) UpdateContactID() *NotificationUpsertBulk {
	return u.Update(func(s *NotificationUpsert) {
		s.UpdateContactID()
	})
}

// ClearContactID clears the value of the "contact_id" field.
func (u *NotificationUpsertBulk) ClearContactID() *NotificationUpsertBulk {
	return u.Update(func(s *NotificationUpsert) {
		s.ClearContactID()
	})
}

// SetTaskID sets the "task_id" field.
func (u *NotificationUpsertBulk) SetTaskID(v int64) *NotificationUpsertBulk {
	return u.Update(func(s *NotificationUpsert) {
		s.SetTaskID(v)
	})
}

// AddTaskID adds v to the "task_id" field.
func (u *NotificationUpsertBulk) AddTaskID(v int64) *NotificationUpsertBulk {
	return u.Update(func(s *NotificationUpsert) {
		s.AddTaskID(v)
	})
}

// UpdateTaskID sets the "task_id" field to the value that was provided on create.
func (u *NotificationUpsertBulk) UpdateTaskID() *NotificationUpsertBulk {
	return u.Update(func(s *NotificationUpsert) {
		s.UpdateTaskID()
	})
}

// ClearTaskID clears the value of the "task_id" field.
func (u *NotificationUpsertBulk) ClearTaskID() *NotificationUpsertBulk {
	return u.Update(func(s *NotificationUpsert) {
		s.ClearTaskID()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *NotificationUpsertBulk) SetCreatedAt(v time.Time) *NotificationUpsertBulk {
	return u.Update(func(s *NotificationUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *NotificationUpsertBulk) UpdateCreatedAt() *NotificationUpsertBulk {
	return u.Update(func(s *NotificationUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetNotificationDataID sets the "notification_data_id" field.
func (u *NotificationUpsertBulk) SetNotificationDataID(v int64) *NotificationUpsertBulk {
	return u.Update(func(s *NotificationUpsert) {
		s.SetNotificationDataID(v)
	})
}

// UpdateNotificationDataID sets the "notification_data_id" field to the value that was provided on create.
func (u *NotificationUpsertBulk) UpdateNotificationDataID() *NotificationUpsertBulk {
	return u.Update(func(s *NotificationUpsert) {
		s.UpdateNotificationDataID()
	})
}

// ClearNotificationDataID clears the value of the "notification_data_id" field.
func (u *NotificationUpsertBulk) ClearNotificationDataID() *NotificationUpsertBulk {
	return u.Update(func(s *NotificationUpsert) {
		s.ClearNotificationDataID()
	})
}

// Exec executes the query.
func (u *NotificationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the NotificationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NotificationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NotificationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
