// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/makesalekz/notifications/ent/notificationdata"
	"github.com/makesalekz/notifications/ent/predicate"
)

// NotificationDataDelete is the builder for deleting a NotificationData entity.
type NotificationDataDelete struct {
	config
	hooks    []Hook
	mutation *NotificationDataMutation
}

// Where appends a list predicates to the NotificationDataDelete builder.
func (ndd *NotificationDataDelete) Where(ps ...predicate.NotificationData) *NotificationDataDelete {
	ndd.mutation.Where(ps...)
	return ndd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ndd *NotificationDataDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ndd.sqlExec, ndd.mutation, ndd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ndd *NotificationDataDelete) ExecX(ctx context.Context) int {
	n, err := ndd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ndd *NotificationDataDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(notificationdata.Table, sqlgraph.NewFieldSpec(notificationdata.FieldID, field.TypeInt64))
	if ps := ndd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ndd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ndd.mutation.done = true
	return affected, err
}

// NotificationDataDeleteOne is the builder for deleting a single NotificationData entity.
type NotificationDataDeleteOne struct {
	ndd *NotificationDataDelete
}

// Where appends a list predicates to the NotificationDataDelete builder.
func (nddo *NotificationDataDeleteOne) Where(ps ...predicate.NotificationData) *NotificationDataDeleteOne {
	nddo.ndd.mutation.Where(ps...)
	return nddo
}

// Exec executes the deletion query.
func (nddo *NotificationDataDeleteOne) Exec(ctx context.Context) error {
	n, err := nddo.ndd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{notificationdata.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (nddo *NotificationDataDeleteOne) ExecX(ctx context.Context) {
	if err := nddo.Exec(ctx); err != nil {
		panic(err)
	}
}
