// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.calendaria.team/services/notifications/ent/notification"
	"gitlab.calendaria.team/services/notifications/ent/notificationdata"
)

// NotificationDataCreate is the builder for creating a NotificationData entity.
type NotificationDataCreate struct {
	config
	mutation *NotificationDataMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetType sets the "type" field.
func (ndc *NotificationDataCreate) SetType(s string) *NotificationDataCreate {
	ndc.mutation.SetType(s)
	return ndc
}

// SetNillableType sets the "type" field if the given value is not nil.
func (ndc *NotificationDataCreate) SetNillableType(s *string) *NotificationDataCreate {
	if s != nil {
		ndc.SetType(*s)
	}
	return ndc
}

// SetEvent sets the "event" field.
func (ndc *NotificationDataCreate) SetEvent(s string) *NotificationDataCreate {
	ndc.mutation.SetEvent(s)
	return ndc
}

// SetNillableEvent sets the "event" field if the given value is not nil.
func (ndc *NotificationDataCreate) SetNillableEvent(s *string) *NotificationDataCreate {
	if s != nil {
		ndc.SetEvent(*s)
	}
	return ndc
}

// SetMember sets the "member" field.
func (ndc *NotificationDataCreate) SetMember(s string) *NotificationDataCreate {
	ndc.mutation.SetMember(s)
	return ndc
}

// SetNillableMember sets the "member" field if the given value is not nil.
func (ndc *NotificationDataCreate) SetNillableMember(s *string) *NotificationDataCreate {
	if s != nil {
		ndc.SetMember(*s)
	}
	return ndc
}

// SetChat sets the "chat" field.
func (ndc *NotificationDataCreate) SetChat(s string) *NotificationDataCreate {
	ndc.mutation.SetChat(s)
	return ndc
}

// SetNillableChat sets the "chat" field if the given value is not nil.
func (ndc *NotificationDataCreate) SetNillableChat(s *string) *NotificationDataCreate {
	if s != nil {
		ndc.SetChat(*s)
	}
	return ndc
}

// SetMessage sets the "message" field.
func (ndc *NotificationDataCreate) SetMessage(s string) *NotificationDataCreate {
	ndc.mutation.SetMessage(s)
	return ndc
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (ndc *NotificationDataCreate) SetNillableMessage(s *string) *NotificationDataCreate {
	if s != nil {
		ndc.SetMessage(*s)
	}
	return ndc
}

// SetContact sets the "contact" field.
func (ndc *NotificationDataCreate) SetContact(s string) *NotificationDataCreate {
	ndc.mutation.SetContact(s)
	return ndc
}

// SetNillableContact sets the "contact" field if the given value is not nil.
func (ndc *NotificationDataCreate) SetNillableContact(s *string) *NotificationDataCreate {
	if s != nil {
		ndc.SetContact(*s)
	}
	return ndc
}

// SetTask sets the "task" field.
func (ndc *NotificationDataCreate) SetTask(s string) *NotificationDataCreate {
	ndc.mutation.SetTask(s)
	return ndc
}

// SetNillableTask sets the "task" field if the given value is not nil.
func (ndc *NotificationDataCreate) SetNillableTask(s *string) *NotificationDataCreate {
	if s != nil {
		ndc.SetTask(*s)
	}
	return ndc
}

// SetProject sets the "project" field.
func (ndc *NotificationDataCreate) SetProject(s string) *NotificationDataCreate {
	ndc.mutation.SetProject(s)
	return ndc
}

// SetNillableProject sets the "project" field if the given value is not nil.
func (ndc *NotificationDataCreate) SetNillableProject(s *string) *NotificationDataCreate {
	if s != nil {
		ndc.SetProject(*s)
	}
	return ndc
}

// SetTargetUserID sets the "target_user_id" field.
func (ndc *NotificationDataCreate) SetTargetUserID(i int64) *NotificationDataCreate {
	ndc.mutation.SetTargetUserID(i)
	return ndc
}

// SetNillableTargetUserID sets the "target_user_id" field if the given value is not nil.
func (ndc *NotificationDataCreate) SetNillableTargetUserID(i *int64) *NotificationDataCreate {
	if i != nil {
		ndc.SetTargetUserID(*i)
	}
	return ndc
}

// SetMetadata sets the "metadata" field.
func (ndc *NotificationDataCreate) SetMetadata(s string) *NotificationDataCreate {
	ndc.mutation.SetMetadata(s)
	return ndc
}

// SetNillableMetadata sets the "metadata" field if the given value is not nil.
func (ndc *NotificationDataCreate) SetNillableMetadata(s *string) *NotificationDataCreate {
	if s != nil {
		ndc.SetMetadata(*s)
	}
	return ndc
}

// SetPluralCount sets the "plural_count" field.
func (ndc *NotificationDataCreate) SetPluralCount(i int64) *NotificationDataCreate {
	ndc.mutation.SetPluralCount(i)
	return ndc
}

// SetNillablePluralCount sets the "plural_count" field if the given value is not nil.
func (ndc *NotificationDataCreate) SetNillablePluralCount(i *int64) *NotificationDataCreate {
	if i != nil {
		ndc.SetPluralCount(*i)
	}
	return ndc
}

// SetID sets the "id" field.
func (ndc *NotificationDataCreate) SetID(i int64) *NotificationDataCreate {
	ndc.mutation.SetID(i)
	return ndc
}

// SetNotificationID sets the "notification" edge to the Notification entity by ID.
func (ndc *NotificationDataCreate) SetNotificationID(id int64) *NotificationDataCreate {
	ndc.mutation.SetNotificationID(id)
	return ndc
}

// SetNillableNotificationID sets the "notification" edge to the Notification entity by ID if the given value is not nil.
func (ndc *NotificationDataCreate) SetNillableNotificationID(id *int64) *NotificationDataCreate {
	if id != nil {
		ndc = ndc.SetNotificationID(*id)
	}
	return ndc
}

// SetNotification sets the "notification" edge to the Notification entity.
func (ndc *NotificationDataCreate) SetNotification(n *Notification) *NotificationDataCreate {
	return ndc.SetNotificationID(n.ID)
}

// Mutation returns the NotificationDataMutation object of the builder.
func (ndc *NotificationDataCreate) Mutation() *NotificationDataMutation {
	return ndc.mutation
}

// Save creates the NotificationData in the database.
func (ndc *NotificationDataCreate) Save(ctx context.Context) (*NotificationData, error) {
	return withHooks(ctx, ndc.sqlSave, ndc.mutation, ndc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ndc *NotificationDataCreate) SaveX(ctx context.Context) *NotificationData {
	v, err := ndc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ndc *NotificationDataCreate) Exec(ctx context.Context) error {
	_, err := ndc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ndc *NotificationDataCreate) ExecX(ctx context.Context) {
	if err := ndc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ndc *NotificationDataCreate) check() error {
	return nil
}

func (ndc *NotificationDataCreate) sqlSave(ctx context.Context) (*NotificationData, error) {
	if err := ndc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ndc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ndc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	ndc.mutation.id = &_node.ID
	ndc.mutation.done = true
	return _node, nil
}

func (ndc *NotificationDataCreate) createSpec() (*NotificationData, *sqlgraph.CreateSpec) {
	var (
		_node = &NotificationData{config: ndc.config}
		_spec = sqlgraph.NewCreateSpec(notificationdata.Table, sqlgraph.NewFieldSpec(notificationdata.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = ndc.conflict
	if id, ok := ndc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ndc.mutation.GetType(); ok {
		_spec.SetField(notificationdata.FieldType, field.TypeString, value)
		_node.Type = &value
	}
	if value, ok := ndc.mutation.Event(); ok {
		_spec.SetField(notificationdata.FieldEvent, field.TypeString, value)
		_node.Event = &value
	}
	if value, ok := ndc.mutation.Member(); ok {
		_spec.SetField(notificationdata.FieldMember, field.TypeString, value)
		_node.Member = &value
	}
	if value, ok := ndc.mutation.Chat(); ok {
		_spec.SetField(notificationdata.FieldChat, field.TypeString, value)
		_node.Chat = &value
	}
	if value, ok := ndc.mutation.Message(); ok {
		_spec.SetField(notificationdata.FieldMessage, field.TypeString, value)
		_node.Message = &value
	}
	if value, ok := ndc.mutation.Contact(); ok {
		_spec.SetField(notificationdata.FieldContact, field.TypeString, value)
		_node.Contact = &value
	}
	if value, ok := ndc.mutation.Task(); ok {
		_spec.SetField(notificationdata.FieldTask, field.TypeString, value)
		_node.Task = &value
	}
	if value, ok := ndc.mutation.Project(); ok {
		_spec.SetField(notificationdata.FieldProject, field.TypeString, value)
		_node.Project = &value
	}
	if value, ok := ndc.mutation.TargetUserID(); ok {
		_spec.SetField(notificationdata.FieldTargetUserID, field.TypeInt64, value)
		_node.TargetUserID = &value
	}
	if value, ok := ndc.mutation.Metadata(); ok {
		_spec.SetField(notificationdata.FieldMetadata, field.TypeString, value)
		_node.Metadata = &value
	}
	if value, ok := ndc.mutation.PluralCount(); ok {
		_spec.SetField(notificationdata.FieldPluralCount, field.TypeInt64, value)
		_node.PluralCount = &value
	}
	if nodes := ndc.mutation.NotificationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   notificationdata.NotificationTable,
			Columns: []string{notificationdata.NotificationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NotificationData.Create().
//		SetType(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NotificationDataUpsert) {
//			SetType(v+v).
//		}).
//		Exec(ctx)
func (ndc *NotificationDataCreate) OnConflict(opts ...sql.ConflictOption) *NotificationDataUpsertOne {
	ndc.conflict = opts
	return &NotificationDataUpsertOne{
		create: ndc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NotificationData.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ndc *NotificationDataCreate) OnConflictColumns(columns ...string) *NotificationDataUpsertOne {
	ndc.conflict = append(ndc.conflict, sql.ConflictColumns(columns...))
	return &NotificationDataUpsertOne{
		create: ndc,
	}
}

type (
	// NotificationDataUpsertOne is the builder for "upsert"-ing
	//  one NotificationData node.
	NotificationDataUpsertOne struct {
		create *NotificationDataCreate
	}

	// NotificationDataUpsert is the "OnConflict" setter.
	NotificationDataUpsert struct {
		*sql.UpdateSet
	}
)

// SetType sets the "type" field.
func (u *NotificationDataUpsert) SetType(v string) *NotificationDataUpsert {
	u.Set(notificationdata.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *NotificationDataUpsert) UpdateType() *NotificationDataUpsert {
	u.SetExcluded(notificationdata.FieldType)
	return u
}

// ClearType clears the value of the "type" field.
func (u *NotificationDataUpsert) ClearType() *NotificationDataUpsert {
	u.SetNull(notificationdata.FieldType)
	return u
}

// SetEvent sets the "event" field.
func (u *NotificationDataUpsert) SetEvent(v string) *NotificationDataUpsert {
	u.Set(notificationdata.FieldEvent, v)
	return u
}

// UpdateEvent sets the "event" field to the value that was provided on create.
func (u *NotificationDataUpsert) UpdateEvent() *NotificationDataUpsert {
	u.SetExcluded(notificationdata.FieldEvent)
	return u
}

// ClearEvent clears the value of the "event" field.
func (u *NotificationDataUpsert) ClearEvent() *NotificationDataUpsert {
	u.SetNull(notificationdata.FieldEvent)
	return u
}

// SetMember sets the "member" field.
func (u *NotificationDataUpsert) SetMember(v string) *NotificationDataUpsert {
	u.Set(notificationdata.FieldMember, v)
	return u
}

// UpdateMember sets the "member" field to the value that was provided on create.
func (u *NotificationDataUpsert) UpdateMember() *NotificationDataUpsert {
	u.SetExcluded(notificationdata.FieldMember)
	return u
}

// ClearMember clears the value of the "member" field.
func (u *NotificationDataUpsert) ClearMember() *NotificationDataUpsert {
	u.SetNull(notificationdata.FieldMember)
	return u
}

// SetChat sets the "chat" field.
func (u *NotificationDataUpsert) SetChat(v string) *NotificationDataUpsert {
	u.Set(notificationdata.FieldChat, v)
	return u
}

// UpdateChat sets the "chat" field to the value that was provided on create.
func (u *NotificationDataUpsert) UpdateChat() *NotificationDataUpsert {
	u.SetExcluded(notificationdata.FieldChat)
	return u
}

// ClearChat clears the value of the "chat" field.
func (u *NotificationDataUpsert) ClearChat() *NotificationDataUpsert {
	u.SetNull(notificationdata.FieldChat)
	return u
}

// SetMessage sets the "message" field.
func (u *NotificationDataUpsert) SetMessage(v string) *NotificationDataUpsert {
	u.Set(notificationdata.FieldMessage, v)
	return u
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *NotificationDataUpsert) UpdateMessage() *NotificationDataUpsert {
	u.SetExcluded(notificationdata.FieldMessage)
	return u
}

// ClearMessage clears the value of the "message" field.
func (u *NotificationDataUpsert) ClearMessage() *NotificationDataUpsert {
	u.SetNull(notificationdata.FieldMessage)
	return u
}

// SetContact sets the "contact" field.
func (u *NotificationDataUpsert) SetContact(v string) *NotificationDataUpsert {
	u.Set(notificationdata.FieldContact, v)
	return u
}

// UpdateContact sets the "contact" field to the value that was provided on create.
func (u *NotificationDataUpsert) UpdateContact() *NotificationDataUpsert {
	u.SetExcluded(notificationdata.FieldContact)
	return u
}

// ClearContact clears the value of the "contact" field.
func (u *NotificationDataUpsert) ClearContact() *NotificationDataUpsert {
	u.SetNull(notificationdata.FieldContact)
	return u
}

// SetTask sets the "task" field.
func (u *NotificationDataUpsert) SetTask(v string) *NotificationDataUpsert {
	u.Set(notificationdata.FieldTask, v)
	return u
}

// UpdateTask sets the "task" field to the value that was provided on create.
func (u *NotificationDataUpsert) UpdateTask() *NotificationDataUpsert {
	u.SetExcluded(notificationdata.FieldTask)
	return u
}

// ClearTask clears the value of the "task" field.
func (u *NotificationDataUpsert) ClearTask() *NotificationDataUpsert {
	u.SetNull(notificationdata.FieldTask)
	return u
}

// SetProject sets the "project" field.
func (u *NotificationDataUpsert) SetProject(v string) *NotificationDataUpsert {
	u.Set(notificationdata.FieldProject, v)
	return u
}

// UpdateProject sets the "project" field to the value that was provided on create.
func (u *NotificationDataUpsert) UpdateProject() *NotificationDataUpsert {
	u.SetExcluded(notificationdata.FieldProject)
	return u
}

// ClearProject clears the value of the "project" field.
func (u *NotificationDataUpsert) ClearProject() *NotificationDataUpsert {
	u.SetNull(notificationdata.FieldProject)
	return u
}

// SetTargetUserID sets the "target_user_id" field.
func (u *NotificationDataUpsert) SetTargetUserID(v int64) *NotificationDataUpsert {
	u.Set(notificationdata.FieldTargetUserID, v)
	return u
}

// UpdateTargetUserID sets the "target_user_id" field to the value that was provided on create.
func (u *NotificationDataUpsert) UpdateTargetUserID() *NotificationDataUpsert {
	u.SetExcluded(notificationdata.FieldTargetUserID)
	return u
}

// AddTargetUserID adds v to the "target_user_id" field.
func (u *NotificationDataUpsert) AddTargetUserID(v int64) *NotificationDataUpsert {
	u.Add(notificationdata.FieldTargetUserID, v)
	return u
}

// ClearTargetUserID clears the value of the "target_user_id" field.
func (u *NotificationDataUpsert) ClearTargetUserID() *NotificationDataUpsert {
	u.SetNull(notificationdata.FieldTargetUserID)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *NotificationDataUpsert) SetMetadata(v string) *NotificationDataUpsert {
	u.Set(notificationdata.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *NotificationDataUpsert) UpdateMetadata() *NotificationDataUpsert {
	u.SetExcluded(notificationdata.FieldMetadata)
	return u
}

// ClearMetadata clears the value of the "metadata" field.
func (u *NotificationDataUpsert) ClearMetadata() *NotificationDataUpsert {
	u.SetNull(notificationdata.FieldMetadata)
	return u
}

// SetPluralCount sets the "plural_count" field.
func (u *NotificationDataUpsert) SetPluralCount(v int64) *NotificationDataUpsert {
	u.Set(notificationdata.FieldPluralCount, v)
	return u
}

// UpdatePluralCount sets the "plural_count" field to the value that was provided on create.
func (u *NotificationDataUpsert) UpdatePluralCount() *NotificationDataUpsert {
	u.SetExcluded(notificationdata.FieldPluralCount)
	return u
}

// AddPluralCount adds v to the "plural_count" field.
func (u *NotificationDataUpsert) AddPluralCount(v int64) *NotificationDataUpsert {
	u.Add(notificationdata.FieldPluralCount, v)
	return u
}

// ClearPluralCount clears the value of the "plural_count" field.
func (u *NotificationDataUpsert) ClearPluralCount() *NotificationDataUpsert {
	u.SetNull(notificationdata.FieldPluralCount)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.NotificationData.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(notificationdata.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *NotificationDataUpsertOne) UpdateNewValues() *NotificationDataUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(notificationdata.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NotificationData.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *NotificationDataUpsertOne) Ignore() *NotificationDataUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NotificationDataUpsertOne) DoNothing() *NotificationDataUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NotificationDataCreate.OnConflict
// documentation for more info.
func (u *NotificationDataUpsertOne) Update(set func(*NotificationDataUpsert)) *NotificationDataUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NotificationDataUpsert{UpdateSet: update})
	}))
	return u
}

// SetType sets the "type" field.
func (u *NotificationDataUpsertOne) SetType(v string) *NotificationDataUpsertOne {
	return u.Update(func(s *NotificationDataUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *NotificationDataUpsertOne) UpdateType() *NotificationDataUpsertOne {
	return u.Update(func(s *NotificationDataUpsert) {
		s.UpdateType()
	})
}

// ClearType clears the value of the "type" field.
func (u *NotificationDataUpsertOne) ClearType() *NotificationDataUpsertOne {
	return u.Update(func(s *NotificationDataUpsert) {
		s.ClearType()
	})
}

// SetEvent sets the "event" field.
func (u *NotificationDataUpsertOne) SetEvent(v string) *NotificationDataUpsertOne {
	return u.Update(func(s *NotificationDataUpsert) {
		s.SetEvent(v)
	})
}

// UpdateEvent sets the "event" field to the value that was provided on create.
func (u *NotificationDataUpsertOne) UpdateEvent() *NotificationDataUpsertOne {
	return u.Update(func(s *NotificationDataUpsert) {
		s.UpdateEvent()
	})
}

// ClearEvent clears the value of the "event" field.
func (u *NotificationDataUpsertOne) ClearEvent() *NotificationDataUpsertOne {
	return u.Update(func(s *NotificationDataUpsert) {
		s.ClearEvent()
	})
}

// SetMember sets the "member" field.
func (u *NotificationDataUpsertOne) SetMember(v string) *NotificationDataUpsertOne {
	return u.Update(func(s *NotificationDataUpsert) {
		s.SetMember(v)
	})
}

// UpdateMember sets the "member" field to the value that was provided on create.
func (u *NotificationDataUpsertOne) UpdateMember() *NotificationDataUpsertOne {
	return u.Update(func(s *NotificationDataUpsert) {
		s.UpdateMember()
	})
}

// ClearMember clears the value of the "member" field.
func (u *NotificationDataUpsertOne) ClearMember() *NotificationDataUpsertOne {
	return u.Update(func(s *NotificationDataUpsert) {
		s.ClearMember()
	})
}

// SetChat sets the "chat" field.
func (u *NotificationDataUpsertOne) SetChat(v string) *NotificationDataUpsertOne {
	return u.Update(func(s *NotificationDataUpsert) {
		s.SetChat(v)
	})
}

// UpdateChat sets the "chat" field to the value that was provided on create.
func (u *NotificationDataUpsertOne) UpdateChat() *NotificationDataUpsertOne {
	return u.Update(func(s *NotificationDataUpsert) {
		s.UpdateChat()
	})
}

// ClearChat clears the value of the "chat" field.
func (u *NotificationDataUpsertOne) ClearChat() *NotificationDataUpsertOne {
	return u.Update(func(s *NotificationDataUpsert) {
		s.ClearChat()
	})
}

// SetMessage sets the "message" field.
func (u *NotificationDataUpsertOne) SetMessage(v string) *NotificationDataUpsertOne {
	return u.Update(func(s *NotificationDataUpsert) {
		s.SetMessage(v)
	})
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *NotificationDataUpsertOne) UpdateMessage() *NotificationDataUpsertOne {
	return u.Update(func(s *NotificationDataUpsert) {
		s.UpdateMessage()
	})
}

// ClearMessage clears the value of the "message" field.
func (u *NotificationDataUpsertOne) ClearMessage() *NotificationDataUpsertOne {
	return u.Update(func(s *NotificationDataUpsert) {
		s.ClearMessage()
	})
}

// SetContact sets the "contact" field.
func (u *NotificationDataUpsertOne) SetContact(v string) *NotificationDataUpsertOne {
	return u.Update(func(s *NotificationDataUpsert) {
		s.SetContact(v)
	})
}

// UpdateContact sets the "contact" field to the value that was provided on create.
func (u *NotificationDataUpsertOne) UpdateContact() *NotificationDataUpsertOne {
	return u.Update(func(s *NotificationDataUpsert) {
		s.UpdateContact()
	})
}

// ClearContact clears the value of the "contact" field.
func (u *NotificationDataUpsertOne) ClearContact() *NotificationDataUpsertOne {
	return u.Update(func(s *NotificationDataUpsert) {
		s.ClearContact()
	})
}

// SetTask sets the "task" field.
func (u *NotificationDataUpsertOne) SetTask(v string) *NotificationDataUpsertOne {
	return u.Update(func(s *NotificationDataUpsert) {
		s.SetTask(v)
	})
}

// UpdateTask sets the "task" field to the value that was provided on create.
func (u *NotificationDataUpsertOne) UpdateTask() *NotificationDataUpsertOne {
	return u.Update(func(s *NotificationDataUpsert) {
		s.UpdateTask()
	})
}

// ClearTask clears the value of the "task" field.
func (u *NotificationDataUpsertOne) ClearTask() *NotificationDataUpsertOne {
	return u.Update(func(s *NotificationDataUpsert) {
		s.ClearTask()
	})
}

// SetProject sets the "project" field.
func (u *NotificationDataUpsertOne) SetProject(v string) *NotificationDataUpsertOne {
	return u.Update(func(s *NotificationDataUpsert) {
		s.SetProject(v)
	})
}

// UpdateProject sets the "project" field to the value that was provided on create.
func (u *NotificationDataUpsertOne) UpdateProject() *NotificationDataUpsertOne {
	return u.Update(func(s *NotificationDataUpsert) {
		s.UpdateProject()
	})
}

// ClearProject clears the value of the "project" field.
func (u *NotificationDataUpsertOne) ClearProject() *NotificationDataUpsertOne {
	return u.Update(func(s *NotificationDataUpsert) {
		s.ClearProject()
	})
}

// SetTargetUserID sets the "target_user_id" field.
func (u *NotificationDataUpsertOne) SetTargetUserID(v int64) *NotificationDataUpsertOne {
	return u.Update(func(s *NotificationDataUpsert) {
		s.SetTargetUserID(v)
	})
}

// AddTargetUserID adds v to the "target_user_id" field.
func (u *NotificationDataUpsertOne) AddTargetUserID(v int64) *NotificationDataUpsertOne {
	return u.Update(func(s *NotificationDataUpsert) {
		s.AddTargetUserID(v)
	})
}

// UpdateTargetUserID sets the "target_user_id" field to the value that was provided on create.
func (u *NotificationDataUpsertOne) UpdateTargetUserID() *NotificationDataUpsertOne {
	return u.Update(func(s *NotificationDataUpsert) {
		s.UpdateTargetUserID()
	})
}

// ClearTargetUserID clears the value of the "target_user_id" field.
func (u *NotificationDataUpsertOne) ClearTargetUserID() *NotificationDataUpsertOne {
	return u.Update(func(s *NotificationDataUpsert) {
		s.ClearTargetUserID()
	})
}

// SetMetadata sets the "metadata" field.
func (u *NotificationDataUpsertOne) SetMetadata(v string) *NotificationDataUpsertOne {
	return u.Update(func(s *NotificationDataUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *NotificationDataUpsertOne) UpdateMetadata() *NotificationDataUpsertOne {
	return u.Update(func(s *NotificationDataUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *NotificationDataUpsertOne) ClearMetadata() *NotificationDataUpsertOne {
	return u.Update(func(s *NotificationDataUpsert) {
		s.ClearMetadata()
	})
}

// SetPluralCount sets the "plural_count" field.
func (u *NotificationDataUpsertOne) SetPluralCount(v int64) *NotificationDataUpsertOne {
	return u.Update(func(s *NotificationDataUpsert) {
		s.SetPluralCount(v)
	})
}

// AddPluralCount adds v to the "plural_count" field.
func (u *NotificationDataUpsertOne) AddPluralCount(v int64) *NotificationDataUpsertOne {
	return u.Update(func(s *NotificationDataUpsert) {
		s.AddPluralCount(v)
	})
}

// UpdatePluralCount sets the "plural_count" field to the value that was provided on create.
func (u *NotificationDataUpsertOne) UpdatePluralCount() *NotificationDataUpsertOne {
	return u.Update(func(s *NotificationDataUpsert) {
		s.UpdatePluralCount()
	})
}

// ClearPluralCount clears the value of the "plural_count" field.
func (u *NotificationDataUpsertOne) ClearPluralCount() *NotificationDataUpsertOne {
	return u.Update(func(s *NotificationDataUpsert) {
		s.ClearPluralCount()
	})
}

// Exec executes the query.
func (u *NotificationDataUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NotificationDataCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NotificationDataUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *NotificationDataUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *NotificationDataUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// NotificationDataCreateBulk is the builder for creating many NotificationData entities in bulk.
type NotificationDataCreateBulk struct {
	config
	err      error
	builders []*NotificationDataCreate
	conflict []sql.ConflictOption
}

// Save creates the NotificationData entities in the database.
func (ndcb *NotificationDataCreateBulk) Save(ctx context.Context) ([]*NotificationData, error) {
	if ndcb.err != nil {
		return nil, ndcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ndcb.builders))
	nodes := make([]*NotificationData, len(ndcb.builders))
	mutators := make([]Mutator, len(ndcb.builders))
	for i := range ndcb.builders {
		func(i int, root context.Context) {
			builder := ndcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NotificationDataMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ndcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = ndcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ndcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ndcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ndcb *NotificationDataCreateBulk) SaveX(ctx context.Context) []*NotificationData {
	v, err := ndcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ndcb *NotificationDataCreateBulk) Exec(ctx context.Context) error {
	_, err := ndcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ndcb *NotificationDataCreateBulk) ExecX(ctx context.Context) {
	if err := ndcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NotificationData.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NotificationDataUpsert) {
//			SetType(v+v).
//		}).
//		Exec(ctx)
func (ndcb *NotificationDataCreateBulk) OnConflict(opts ...sql.ConflictOption) *NotificationDataUpsertBulk {
	ndcb.conflict = opts
	return &NotificationDataUpsertBulk{
		create: ndcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NotificationData.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ndcb *NotificationDataCreateBulk) OnConflictColumns(columns ...string) *NotificationDataUpsertBulk {
	ndcb.conflict = append(ndcb.conflict, sql.ConflictColumns(columns...))
	return &NotificationDataUpsertBulk{
		create: ndcb,
	}
}

// NotificationDataUpsertBulk is the builder for "upsert"-ing
// a bulk of NotificationData nodes.
type NotificationDataUpsertBulk struct {
	create *NotificationDataCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.NotificationData.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(notificationdata.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *NotificationDataUpsertBulk) UpdateNewValues() *NotificationDataUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(notificationdata.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NotificationData.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *NotificationDataUpsertBulk) Ignore() *NotificationDataUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NotificationDataUpsertBulk) DoNothing() *NotificationDataUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NotificationDataCreateBulk.OnConflict
// documentation for more info.
func (u *NotificationDataUpsertBulk) Update(set func(*NotificationDataUpsert)) *NotificationDataUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NotificationDataUpsert{UpdateSet: update})
	}))
	return u
}

// SetType sets the "type" field.
func (u *NotificationDataUpsertBulk) SetType(v string) *NotificationDataUpsertBulk {
	return u.Update(func(s *NotificationDataUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *NotificationDataUpsertBulk) UpdateType() *NotificationDataUpsertBulk {
	return u.Update(func(s *NotificationDataUpsert) {
		s.UpdateType()
	})
}

// ClearType clears the value of the "type" field.
func (u *NotificationDataUpsertBulk) ClearType() *NotificationDataUpsertBulk {
	return u.Update(func(s *NotificationDataUpsert) {
		s.ClearType()
	})
}

// SetEvent sets the "event" field.
func (u *NotificationDataUpsertBulk) SetEvent(v string) *NotificationDataUpsertBulk {
	return u.Update(func(s *NotificationDataUpsert) {
		s.SetEvent(v)
	})
}

// UpdateEvent sets the "event" field to the value that was provided on create.
func (u *NotificationDataUpsertBulk) UpdateEvent() *NotificationDataUpsertBulk {
	return u.Update(func(s *NotificationDataUpsert) {
		s.UpdateEvent()
	})
}

// ClearEvent clears the value of the "event" field.
func (u *NotificationDataUpsertBulk) ClearEvent() *NotificationDataUpsertBulk {
	return u.Update(func(s *NotificationDataUpsert) {
		s.ClearEvent()
	})
}

// SetMember sets the "member" field.
func (u *NotificationDataUpsertBulk) SetMember(v string) *NotificationDataUpsertBulk {
	return u.Update(func(s *NotificationDataUpsert) {
		s.SetMember(v)
	})
}

// UpdateMember sets the "member" field to the value that was provided on create.
func (u *NotificationDataUpsertBulk) UpdateMember() *NotificationDataUpsertBulk {
	return u.Update(func(s *NotificationDataUpsert) {
		s.UpdateMember()
	})
}

// ClearMember clears the value of the "member" field.
func (u *NotificationDataUpsertBulk) ClearMember() *NotificationDataUpsertBulk {
	return u.Update(func(s *NotificationDataUpsert) {
		s.ClearMember()
	})
}

// SetChat sets the "chat" field.
func (u *NotificationDataUpsertBulk) SetChat(v string) *NotificationDataUpsertBulk {
	return u.Update(func(s *NotificationDataUpsert) {
		s.SetChat(v)
	})
}

// UpdateChat sets the "chat" field to the value that was provided on create.
func (u *NotificationDataUpsertBulk) UpdateChat() *NotificationDataUpsertBulk {
	return u.Update(func(s *NotificationDataUpsert) {
		s.UpdateChat()
	})
}

// ClearChat clears the value of the "chat" field.
func (u *NotificationDataUpsertBulk) ClearChat() *NotificationDataUpsertBulk {
	return u.Update(func(s *NotificationDataUpsert) {
		s.ClearChat()
	})
}

// SetMessage sets the "message" field.
func (u *NotificationDataUpsertBulk) SetMessage(v string) *NotificationDataUpsertBulk {
	return u.Update(func(s *NotificationDataUpsert) {
		s.SetMessage(v)
	})
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *NotificationDataUpsertBulk) UpdateMessage() *NotificationDataUpsertBulk {
	return u.Update(func(s *NotificationDataUpsert) {
		s.UpdateMessage()
	})
}

// ClearMessage clears the value of the "message" field.
func (u *NotificationDataUpsertBulk) ClearMessage() *NotificationDataUpsertBulk {
	return u.Update(func(s *NotificationDataUpsert) {
		s.ClearMessage()
	})
}

// SetContact sets the "contact" field.
func (u *NotificationDataUpsertBulk) SetContact(v string) *NotificationDataUpsertBulk {
	return u.Update(func(s *NotificationDataUpsert) {
		s.SetContact(v)
	})
}

// UpdateContact sets the "contact" field to the value that was provided on create.
func (u *NotificationDataUpsertBulk) UpdateContact() *NotificationDataUpsertBulk {
	return u.Update(func(s *NotificationDataUpsert) {
		s.UpdateContact()
	})
}

// ClearContact clears the value of the "contact" field.
func (u *NotificationDataUpsertBulk) ClearContact() *NotificationDataUpsertBulk {
	return u.Update(func(s *NotificationDataUpsert) {
		s.ClearContact()
	})
}

// SetTask sets the "task" field.
func (u *NotificationDataUpsertBulk) SetTask(v string) *NotificationDataUpsertBulk {
	return u.Update(func(s *NotificationDataUpsert) {
		s.SetTask(v)
	})
}

// UpdateTask sets the "task" field to the value that was provided on create.
func (u *NotificationDataUpsertBulk) UpdateTask() *NotificationDataUpsertBulk {
	return u.Update(func(s *NotificationDataUpsert) {
		s.UpdateTask()
	})
}

// ClearTask clears the value of the "task" field.
func (u *NotificationDataUpsertBulk) ClearTask() *NotificationDataUpsertBulk {
	return u.Update(func(s *NotificationDataUpsert) {
		s.ClearTask()
	})
}

// SetProject sets the "project" field.
func (u *NotificationDataUpsertBulk) SetProject(v string) *NotificationDataUpsertBulk {
	return u.Update(func(s *NotificationDataUpsert) {
		s.SetProject(v)
	})
}

// UpdateProject sets the "project" field to the value that was provided on create.
func (u *NotificationDataUpsertBulk) UpdateProject() *NotificationDataUpsertBulk {
	return u.Update(func(s *NotificationDataUpsert) {
		s.UpdateProject()
	})
}

// ClearProject clears the value of the "project" field.
func (u *NotificationDataUpsertBulk) ClearProject() *NotificationDataUpsertBulk {
	return u.Update(func(s *NotificationDataUpsert) {
		s.ClearProject()
	})
}

// SetTargetUserID sets the "target_user_id" field.
func (u *NotificationDataUpsertBulk) SetTargetUserID(v int64) *NotificationDataUpsertBulk {
	return u.Update(func(s *NotificationDataUpsert) {
		s.SetTargetUserID(v)
	})
}

// AddTargetUserID adds v to the "target_user_id" field.
func (u *NotificationDataUpsertBulk) AddTargetUserID(v int64) *NotificationDataUpsertBulk {
	return u.Update(func(s *NotificationDataUpsert) {
		s.AddTargetUserID(v)
	})
}

// UpdateTargetUserID sets the "target_user_id" field to the value that was provided on create.
func (u *NotificationDataUpsertBulk) UpdateTargetUserID() *NotificationDataUpsertBulk {
	return u.Update(func(s *NotificationDataUpsert) {
		s.UpdateTargetUserID()
	})
}

// ClearTargetUserID clears the value of the "target_user_id" field.
func (u *NotificationDataUpsertBulk) ClearTargetUserID() *NotificationDataUpsertBulk {
	return u.Update(func(s *NotificationDataUpsert) {
		s.ClearTargetUserID()
	})
}

// SetMetadata sets the "metadata" field.
func (u *NotificationDataUpsertBulk) SetMetadata(v string) *NotificationDataUpsertBulk {
	return u.Update(func(s *NotificationDataUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *NotificationDataUpsertBulk) UpdateMetadata() *NotificationDataUpsertBulk {
	return u.Update(func(s *NotificationDataUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *NotificationDataUpsertBulk) ClearMetadata() *NotificationDataUpsertBulk {
	return u.Update(func(s *NotificationDataUpsert) {
		s.ClearMetadata()
	})
}

// SetPluralCount sets the "plural_count" field.
func (u *NotificationDataUpsertBulk) SetPluralCount(v int64) *NotificationDataUpsertBulk {
	return u.Update(func(s *NotificationDataUpsert) {
		s.SetPluralCount(v)
	})
}

// AddPluralCount adds v to the "plural_count" field.
func (u *NotificationDataUpsertBulk) AddPluralCount(v int64) *NotificationDataUpsertBulk {
	return u.Update(func(s *NotificationDataUpsert) {
		s.AddPluralCount(v)
	})
}

// UpdatePluralCount sets the "plural_count" field to the value that was provided on create.
func (u *NotificationDataUpsertBulk) UpdatePluralCount() *NotificationDataUpsertBulk {
	return u.Update(func(s *NotificationDataUpsert) {
		s.UpdatePluralCount()
	})
}

// ClearPluralCount clears the value of the "plural_count" field.
func (u *NotificationDataUpsertBulk) ClearPluralCount() *NotificationDataUpsertBulk {
	return u.Update(func(s *NotificationDataUpsert) {
		s.ClearPluralCount()
	})
}

// Exec executes the query.
func (u *NotificationDataUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the NotificationDataCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NotificationDataCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NotificationDataUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
