// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.calendaria.team/services/notifications/ent/enum"
	"gitlab.calendaria.team/services/notifications/ent/notification"
	"gitlab.calendaria.team/services/notifications/ent/predicate"
)

// NotificationUpdate is the builder for updating Notification entities.
type NotificationUpdate struct {
	config
	hooks     []Hook
	mutation  *NotificationMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the NotificationUpdate builder.
func (nu *NotificationUpdate) Where(ps ...predicate.Notification) *NotificationUpdate {
	nu.mutation.Where(ps...)
	return nu
}

// SetUserID sets the "user_id" field.
func (nu *NotificationUpdate) SetUserID(i int64) *NotificationUpdate {
	nu.mutation.ResetUserID()
	nu.mutation.SetUserID(i)
	return nu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (nu *NotificationUpdate) SetNillableUserID(i *int64) *NotificationUpdate {
	if i != nil {
		nu.SetUserID(*i)
	}
	return nu
}

// AddUserID adds i to the "user_id" field.
func (nu *NotificationUpdate) AddUserID(i int64) *NotificationUpdate {
	nu.mutation.AddUserID(i)
	return nu
}

// SetType sets the "type" field.
func (nu *NotificationUpdate) SetType(et enum.NotificationType) *NotificationUpdate {
	nu.mutation.SetType(et)
	return nu
}

// SetNillableType sets the "type" field if the given value is not nil.
func (nu *NotificationUpdate) SetNillableType(et *enum.NotificationType) *NotificationUpdate {
	if et != nil {
		nu.SetType(*et)
	}
	return nu
}

// SetTitle sets the "title" field.
func (nu *NotificationUpdate) SetTitle(s string) *NotificationUpdate {
	nu.mutation.SetTitle(s)
	return nu
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (nu *NotificationUpdate) SetNillableTitle(s *string) *NotificationUpdate {
	if s != nil {
		nu.SetTitle(*s)
	}
	return nu
}

// SetText sets the "text" field.
func (nu *NotificationUpdate) SetText(s string) *NotificationUpdate {
	nu.mutation.SetText(s)
	return nu
}

// SetNillableText sets the "text" field if the given value is not nil.
func (nu *NotificationUpdate) SetNillableText(s *string) *NotificationUpdate {
	if s != nil {
		nu.SetText(*s)
	}
	return nu
}

// SetEventID sets the "event_id" field.
func (nu *NotificationUpdate) SetEventID(i int64) *NotificationUpdate {
	nu.mutation.ResetEventID()
	nu.mutation.SetEventID(i)
	return nu
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (nu *NotificationUpdate) SetNillableEventID(i *int64) *NotificationUpdate {
	if i != nil {
		nu.SetEventID(*i)
	}
	return nu
}

// AddEventID adds i to the "event_id" field.
func (nu *NotificationUpdate) AddEventID(i int64) *NotificationUpdate {
	nu.mutation.AddEventID(i)
	return nu
}

// ClearEventID clears the value of the "event_id" field.
func (nu *NotificationUpdate) ClearEventID() *NotificationUpdate {
	nu.mutation.ClearEventID()
	return nu
}

// SetContactID sets the "contact_id" field.
func (nu *NotificationUpdate) SetContactID(i int64) *NotificationUpdate {
	nu.mutation.ResetContactID()
	nu.mutation.SetContactID(i)
	return nu
}

// SetNillableContactID sets the "contact_id" field if the given value is not nil.
func (nu *NotificationUpdate) SetNillableContactID(i *int64) *NotificationUpdate {
	if i != nil {
		nu.SetContactID(*i)
	}
	return nu
}

// AddContactID adds i to the "contact_id" field.
func (nu *NotificationUpdate) AddContactID(i int64) *NotificationUpdate {
	nu.mutation.AddContactID(i)
	return nu
}

// ClearContactID clears the value of the "contact_id" field.
func (nu *NotificationUpdate) ClearContactID() *NotificationUpdate {
	nu.mutation.ClearContactID()
	return nu
}

// SetTaskID sets the "task_id" field.
func (nu *NotificationUpdate) SetTaskID(i int64) *NotificationUpdate {
	nu.mutation.ResetTaskID()
	nu.mutation.SetTaskID(i)
	return nu
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (nu *NotificationUpdate) SetNillableTaskID(i *int64) *NotificationUpdate {
	if i != nil {
		nu.SetTaskID(*i)
	}
	return nu
}

// AddTaskID adds i to the "task_id" field.
func (nu *NotificationUpdate) AddTaskID(i int64) *NotificationUpdate {
	nu.mutation.AddTaskID(i)
	return nu
}

// ClearTaskID clears the value of the "task_id" field.
func (nu *NotificationUpdate) ClearTaskID() *NotificationUpdate {
	nu.mutation.ClearTaskID()
	return nu
}

// SetCreatedAt sets the "created_at" field.
func (nu *NotificationUpdate) SetCreatedAt(t time.Time) *NotificationUpdate {
	nu.mutation.SetCreatedAt(t)
	return nu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (nu *NotificationUpdate) SetNillableCreatedAt(t *time.Time) *NotificationUpdate {
	if t != nil {
		nu.SetCreatedAt(*t)
	}
	return nu
}

// Mutation returns the NotificationMutation object of the builder.
func (nu *NotificationUpdate) Mutation() *NotificationMutation {
	return nu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (nu *NotificationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, nu.sqlSave, nu.mutation, nu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (nu *NotificationUpdate) SaveX(ctx context.Context) int {
	affected, err := nu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (nu *NotificationUpdate) Exec(ctx context.Context) error {
	_, err := nu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nu *NotificationUpdate) ExecX(ctx context.Context) {
	if err := nu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nu *NotificationUpdate) check() error {
	if v, ok := nu.mutation.UserID(); ok {
		if err := notification.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Notification.user_id": %w`, err)}
		}
	}
	if v, ok := nu.mutation.Title(); ok {
		if err := notification.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Notification.title": %w`, err)}
		}
	}
	if v, ok := nu.mutation.Text(); ok {
		if err := notification.TextValidator(v); err != nil {
			return &ValidationError{Name: "text", err: fmt.Errorf(`ent: validator failed for field "Notification.text": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (nu *NotificationUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *NotificationUpdate {
	nu.modifiers = append(nu.modifiers, modifiers...)
	return nu
}

func (nu *NotificationUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := nu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(notification.Table, notification.Columns, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeInt64))
	if ps := nu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := nu.mutation.UserID(); ok {
		_spec.SetField(notification.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := nu.mutation.AddedUserID(); ok {
		_spec.AddField(notification.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := nu.mutation.GetType(); ok {
		_spec.SetField(notification.FieldType, field.TypeString, value)
	}
	if value, ok := nu.mutation.Title(); ok {
		_spec.SetField(notification.FieldTitle, field.TypeString, value)
	}
	if value, ok := nu.mutation.Text(); ok {
		_spec.SetField(notification.FieldText, field.TypeString, value)
	}
	if value, ok := nu.mutation.EventID(); ok {
		_spec.SetField(notification.FieldEventID, field.TypeInt64, value)
	}
	if value, ok := nu.mutation.AddedEventID(); ok {
		_spec.AddField(notification.FieldEventID, field.TypeInt64, value)
	}
	if nu.mutation.EventIDCleared() {
		_spec.ClearField(notification.FieldEventID, field.TypeInt64)
	}
	if value, ok := nu.mutation.ContactID(); ok {
		_spec.SetField(notification.FieldContactID, field.TypeInt64, value)
	}
	if value, ok := nu.mutation.AddedContactID(); ok {
		_spec.AddField(notification.FieldContactID, field.TypeInt64, value)
	}
	if nu.mutation.ContactIDCleared() {
		_spec.ClearField(notification.FieldContactID, field.TypeInt64)
	}
	if value, ok := nu.mutation.TaskID(); ok {
		_spec.SetField(notification.FieldTaskID, field.TypeInt64, value)
	}
	if value, ok := nu.mutation.AddedTaskID(); ok {
		_spec.AddField(notification.FieldTaskID, field.TypeInt64, value)
	}
	if nu.mutation.TaskIDCleared() {
		_spec.ClearField(notification.FieldTaskID, field.TypeInt64)
	}
	if value, ok := nu.mutation.CreatedAt(); ok {
		_spec.SetField(notification.FieldCreatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(nu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, nu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	nu.mutation.done = true
	return n, nil
}

// NotificationUpdateOne is the builder for updating a single Notification entity.
type NotificationUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *NotificationMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUserID sets the "user_id" field.
func (nuo *NotificationUpdateOne) SetUserID(i int64) *NotificationUpdateOne {
	nuo.mutation.ResetUserID()
	nuo.mutation.SetUserID(i)
	return nuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (nuo *NotificationUpdateOne) SetNillableUserID(i *int64) *NotificationUpdateOne {
	if i != nil {
		nuo.SetUserID(*i)
	}
	return nuo
}

// AddUserID adds i to the "user_id" field.
func (nuo *NotificationUpdateOne) AddUserID(i int64) *NotificationUpdateOne {
	nuo.mutation.AddUserID(i)
	return nuo
}

// SetType sets the "type" field.
func (nuo *NotificationUpdateOne) SetType(et enum.NotificationType) *NotificationUpdateOne {
	nuo.mutation.SetType(et)
	return nuo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (nuo *NotificationUpdateOne) SetNillableType(et *enum.NotificationType) *NotificationUpdateOne {
	if et != nil {
		nuo.SetType(*et)
	}
	return nuo
}

// SetTitle sets the "title" field.
func (nuo *NotificationUpdateOne) SetTitle(s string) *NotificationUpdateOne {
	nuo.mutation.SetTitle(s)
	return nuo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (nuo *NotificationUpdateOne) SetNillableTitle(s *string) *NotificationUpdateOne {
	if s != nil {
		nuo.SetTitle(*s)
	}
	return nuo
}

// SetText sets the "text" field.
func (nuo *NotificationUpdateOne) SetText(s string) *NotificationUpdateOne {
	nuo.mutation.SetText(s)
	return nuo
}

// SetNillableText sets the "text" field if the given value is not nil.
func (nuo *NotificationUpdateOne) SetNillableText(s *string) *NotificationUpdateOne {
	if s != nil {
		nuo.SetText(*s)
	}
	return nuo
}

// SetEventID sets the "event_id" field.
func (nuo *NotificationUpdateOne) SetEventID(i int64) *NotificationUpdateOne {
	nuo.mutation.ResetEventID()
	nuo.mutation.SetEventID(i)
	return nuo
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (nuo *NotificationUpdateOne) SetNillableEventID(i *int64) *NotificationUpdateOne {
	if i != nil {
		nuo.SetEventID(*i)
	}
	return nuo
}

// AddEventID adds i to the "event_id" field.
func (nuo *NotificationUpdateOne) AddEventID(i int64) *NotificationUpdateOne {
	nuo.mutation.AddEventID(i)
	return nuo
}

// ClearEventID clears the value of the "event_id" field.
func (nuo *NotificationUpdateOne) ClearEventID() *NotificationUpdateOne {
	nuo.mutation.ClearEventID()
	return nuo
}

// SetContactID sets the "contact_id" field.
func (nuo *NotificationUpdateOne) SetContactID(i int64) *NotificationUpdateOne {
	nuo.mutation.ResetContactID()
	nuo.mutation.SetContactID(i)
	return nuo
}

// SetNillableContactID sets the "contact_id" field if the given value is not nil.
func (nuo *NotificationUpdateOne) SetNillableContactID(i *int64) *NotificationUpdateOne {
	if i != nil {
		nuo.SetContactID(*i)
	}
	return nuo
}

// AddContactID adds i to the "contact_id" field.
func (nuo *NotificationUpdateOne) AddContactID(i int64) *NotificationUpdateOne {
	nuo.mutation.AddContactID(i)
	return nuo
}

// ClearContactID clears the value of the "contact_id" field.
func (nuo *NotificationUpdateOne) ClearContactID() *NotificationUpdateOne {
	nuo.mutation.ClearContactID()
	return nuo
}

// SetTaskID sets the "task_id" field.
func (nuo *NotificationUpdateOne) SetTaskID(i int64) *NotificationUpdateOne {
	nuo.mutation.ResetTaskID()
	nuo.mutation.SetTaskID(i)
	return nuo
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (nuo *NotificationUpdateOne) SetNillableTaskID(i *int64) *NotificationUpdateOne {
	if i != nil {
		nuo.SetTaskID(*i)
	}
	return nuo
}

// AddTaskID adds i to the "task_id" field.
func (nuo *NotificationUpdateOne) AddTaskID(i int64) *NotificationUpdateOne {
	nuo.mutation.AddTaskID(i)
	return nuo
}

// ClearTaskID clears the value of the "task_id" field.
func (nuo *NotificationUpdateOne) ClearTaskID() *NotificationUpdateOne {
	nuo.mutation.ClearTaskID()
	return nuo
}

// SetCreatedAt sets the "created_at" field.
func (nuo *NotificationUpdateOne) SetCreatedAt(t time.Time) *NotificationUpdateOne {
	nuo.mutation.SetCreatedAt(t)
	return nuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (nuo *NotificationUpdateOne) SetNillableCreatedAt(t *time.Time) *NotificationUpdateOne {
	if t != nil {
		nuo.SetCreatedAt(*t)
	}
	return nuo
}

// Mutation returns the NotificationMutation object of the builder.
func (nuo *NotificationUpdateOne) Mutation() *NotificationMutation {
	return nuo.mutation
}

// Where appends a list predicates to the NotificationUpdate builder.
func (nuo *NotificationUpdateOne) Where(ps ...predicate.Notification) *NotificationUpdateOne {
	nuo.mutation.Where(ps...)
	return nuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (nuo *NotificationUpdateOne) Select(field string, fields ...string) *NotificationUpdateOne {
	nuo.fields = append([]string{field}, fields...)
	return nuo
}

// Save executes the query and returns the updated Notification entity.
func (nuo *NotificationUpdateOne) Save(ctx context.Context) (*Notification, error) {
	return withHooks(ctx, nuo.sqlSave, nuo.mutation, nuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (nuo *NotificationUpdateOne) SaveX(ctx context.Context) *Notification {
	node, err := nuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (nuo *NotificationUpdateOne) Exec(ctx context.Context) error {
	_, err := nuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nuo *NotificationUpdateOne) ExecX(ctx context.Context) {
	if err := nuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nuo *NotificationUpdateOne) check() error {
	if v, ok := nuo.mutation.UserID(); ok {
		if err := notification.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Notification.user_id": %w`, err)}
		}
	}
	if v, ok := nuo.mutation.Title(); ok {
		if err := notification.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Notification.title": %w`, err)}
		}
	}
	if v, ok := nuo.mutation.Text(); ok {
		if err := notification.TextValidator(v); err != nil {
			return &ValidationError{Name: "text", err: fmt.Errorf(`ent: validator failed for field "Notification.text": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (nuo *NotificationUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *NotificationUpdateOne {
	nuo.modifiers = append(nuo.modifiers, modifiers...)
	return nuo
}

func (nuo *NotificationUpdateOne) sqlSave(ctx context.Context) (_node *Notification, err error) {
	if err := nuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notification.Table, notification.Columns, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeInt64))
	id, ok := nuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Notification.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := nuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notification.FieldID)
		for _, f := range fields {
			if !notification.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notification.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := nuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := nuo.mutation.UserID(); ok {
		_spec.SetField(notification.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := nuo.mutation.AddedUserID(); ok {
		_spec.AddField(notification.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := nuo.mutation.GetType(); ok {
		_spec.SetField(notification.FieldType, field.TypeString, value)
	}
	if value, ok := nuo.mutation.Title(); ok {
		_spec.SetField(notification.FieldTitle, field.TypeString, value)
	}
	if value, ok := nuo.mutation.Text(); ok {
		_spec.SetField(notification.FieldText, field.TypeString, value)
	}
	if value, ok := nuo.mutation.EventID(); ok {
		_spec.SetField(notification.FieldEventID, field.TypeInt64, value)
	}
	if value, ok := nuo.mutation.AddedEventID(); ok {
		_spec.AddField(notification.FieldEventID, field.TypeInt64, value)
	}
	if nuo.mutation.EventIDCleared() {
		_spec.ClearField(notification.FieldEventID, field.TypeInt64)
	}
	if value, ok := nuo.mutation.ContactID(); ok {
		_spec.SetField(notification.FieldContactID, field.TypeInt64, value)
	}
	if value, ok := nuo.mutation.AddedContactID(); ok {
		_spec.AddField(notification.FieldContactID, field.TypeInt64, value)
	}
	if nuo.mutation.ContactIDCleared() {
		_spec.ClearField(notification.FieldContactID, field.TypeInt64)
	}
	if value, ok := nuo.mutation.TaskID(); ok {
		_spec.SetField(notification.FieldTaskID, field.TypeInt64, value)
	}
	if value, ok := nuo.mutation.AddedTaskID(); ok {
		_spec.AddField(notification.FieldTaskID, field.TypeInt64, value)
	}
	if nuo.mutation.TaskIDCleared() {
		_spec.ClearField(notification.FieldTaskID, field.TypeInt64)
	}
	if value, ok := nuo.mutation.CreatedAt(); ok {
		_spec.SetField(notification.FieldCreatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(nuo.modifiers...)
	_node = &Notification{config: nuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, nuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	nuo.mutation.done = true
	return _node, nil
}
