// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.calendaria.team/services/notifications/ent/notification"
	"gitlab.calendaria.team/services/notifications/ent/notificationdata"
	"gitlab.calendaria.team/services/notifications/ent/predicate"
)

// NotificationDataUpdate is the builder for updating NotificationData entities.
type NotificationDataUpdate struct {
	config
	hooks     []Hook
	mutation  *NotificationDataMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the NotificationDataUpdate builder.
func (ndu *NotificationDataUpdate) Where(ps ...predicate.NotificationData) *NotificationDataUpdate {
	ndu.mutation.Where(ps...)
	return ndu
}

// SetType sets the "type" field.
func (ndu *NotificationDataUpdate) SetType(s string) *NotificationDataUpdate {
	ndu.mutation.SetType(s)
	return ndu
}

// SetNillableType sets the "type" field if the given value is not nil.
func (ndu *NotificationDataUpdate) SetNillableType(s *string) *NotificationDataUpdate {
	if s != nil {
		ndu.SetType(*s)
	}
	return ndu
}

// ClearType clears the value of the "type" field.
func (ndu *NotificationDataUpdate) ClearType() *NotificationDataUpdate {
	ndu.mutation.ClearType()
	return ndu
}

// SetEvent sets the "event" field.
func (ndu *NotificationDataUpdate) SetEvent(s string) *NotificationDataUpdate {
	ndu.mutation.SetEvent(s)
	return ndu
}

// SetNillableEvent sets the "event" field if the given value is not nil.
func (ndu *NotificationDataUpdate) SetNillableEvent(s *string) *NotificationDataUpdate {
	if s != nil {
		ndu.SetEvent(*s)
	}
	return ndu
}

// ClearEvent clears the value of the "event" field.
func (ndu *NotificationDataUpdate) ClearEvent() *NotificationDataUpdate {
	ndu.mutation.ClearEvent()
	return ndu
}

// SetMember sets the "member" field.
func (ndu *NotificationDataUpdate) SetMember(s string) *NotificationDataUpdate {
	ndu.mutation.SetMember(s)
	return ndu
}

// SetNillableMember sets the "member" field if the given value is not nil.
func (ndu *NotificationDataUpdate) SetNillableMember(s *string) *NotificationDataUpdate {
	if s != nil {
		ndu.SetMember(*s)
	}
	return ndu
}

// ClearMember clears the value of the "member" field.
func (ndu *NotificationDataUpdate) ClearMember() *NotificationDataUpdate {
	ndu.mutation.ClearMember()
	return ndu
}

// SetChat sets the "chat" field.
func (ndu *NotificationDataUpdate) SetChat(s string) *NotificationDataUpdate {
	ndu.mutation.SetChat(s)
	return ndu
}

// SetNillableChat sets the "chat" field if the given value is not nil.
func (ndu *NotificationDataUpdate) SetNillableChat(s *string) *NotificationDataUpdate {
	if s != nil {
		ndu.SetChat(*s)
	}
	return ndu
}

// ClearChat clears the value of the "chat" field.
func (ndu *NotificationDataUpdate) ClearChat() *NotificationDataUpdate {
	ndu.mutation.ClearChat()
	return ndu
}

// SetMessage sets the "message" field.
func (ndu *NotificationDataUpdate) SetMessage(s string) *NotificationDataUpdate {
	ndu.mutation.SetMessage(s)
	return ndu
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (ndu *NotificationDataUpdate) SetNillableMessage(s *string) *NotificationDataUpdate {
	if s != nil {
		ndu.SetMessage(*s)
	}
	return ndu
}

// ClearMessage clears the value of the "message" field.
func (ndu *NotificationDataUpdate) ClearMessage() *NotificationDataUpdate {
	ndu.mutation.ClearMessage()
	return ndu
}

// SetContact sets the "contact" field.
func (ndu *NotificationDataUpdate) SetContact(s string) *NotificationDataUpdate {
	ndu.mutation.SetContact(s)
	return ndu
}

// SetNillableContact sets the "contact" field if the given value is not nil.
func (ndu *NotificationDataUpdate) SetNillableContact(s *string) *NotificationDataUpdate {
	if s != nil {
		ndu.SetContact(*s)
	}
	return ndu
}

// ClearContact clears the value of the "contact" field.
func (ndu *NotificationDataUpdate) ClearContact() *NotificationDataUpdate {
	ndu.mutation.ClearContact()
	return ndu
}

// SetTask sets the "task" field.
func (ndu *NotificationDataUpdate) SetTask(s string) *NotificationDataUpdate {
	ndu.mutation.SetTask(s)
	return ndu
}

// SetNillableTask sets the "task" field if the given value is not nil.
func (ndu *NotificationDataUpdate) SetNillableTask(s *string) *NotificationDataUpdate {
	if s != nil {
		ndu.SetTask(*s)
	}
	return ndu
}

// ClearTask clears the value of the "task" field.
func (ndu *NotificationDataUpdate) ClearTask() *NotificationDataUpdate {
	ndu.mutation.ClearTask()
	return ndu
}

// SetProject sets the "project" field.
func (ndu *NotificationDataUpdate) SetProject(s string) *NotificationDataUpdate {
	ndu.mutation.SetProject(s)
	return ndu
}

// SetNillableProject sets the "project" field if the given value is not nil.
func (ndu *NotificationDataUpdate) SetNillableProject(s *string) *NotificationDataUpdate {
	if s != nil {
		ndu.SetProject(*s)
	}
	return ndu
}

// ClearProject clears the value of the "project" field.
func (ndu *NotificationDataUpdate) ClearProject() *NotificationDataUpdate {
	ndu.mutation.ClearProject()
	return ndu
}

// SetUser sets the "user" field.
func (ndu *NotificationDataUpdate) SetUser(s string) *NotificationDataUpdate {
	ndu.mutation.SetUser(s)
	return ndu
}

// SetNillableUser sets the "user" field if the given value is not nil.
func (ndu *NotificationDataUpdate) SetNillableUser(s *string) *NotificationDataUpdate {
	if s != nil {
		ndu.SetUser(*s)
	}
	return ndu
}

// ClearUser clears the value of the "user" field.
func (ndu *NotificationDataUpdate) ClearUser() *NotificationDataUpdate {
	ndu.mutation.ClearUser()
	return ndu
}

// SetTargetUserID sets the "target_user_id" field.
func (ndu *NotificationDataUpdate) SetTargetUserID(i int64) *NotificationDataUpdate {
	ndu.mutation.ResetTargetUserID()
	ndu.mutation.SetTargetUserID(i)
	return ndu
}

// SetNillableTargetUserID sets the "target_user_id" field if the given value is not nil.
func (ndu *NotificationDataUpdate) SetNillableTargetUserID(i *int64) *NotificationDataUpdate {
	if i != nil {
		ndu.SetTargetUserID(*i)
	}
	return ndu
}

// AddTargetUserID adds i to the "target_user_id" field.
func (ndu *NotificationDataUpdate) AddTargetUserID(i int64) *NotificationDataUpdate {
	ndu.mutation.AddTargetUserID(i)
	return ndu
}

// ClearTargetUserID clears the value of the "target_user_id" field.
func (ndu *NotificationDataUpdate) ClearTargetUserID() *NotificationDataUpdate {
	ndu.mutation.ClearTargetUserID()
	return ndu
}

// SetMetadata sets the "metadata" field.
func (ndu *NotificationDataUpdate) SetMetadata(s string) *NotificationDataUpdate {
	ndu.mutation.SetMetadata(s)
	return ndu
}

// SetNillableMetadata sets the "metadata" field if the given value is not nil.
func (ndu *NotificationDataUpdate) SetNillableMetadata(s *string) *NotificationDataUpdate {
	if s != nil {
		ndu.SetMetadata(*s)
	}
	return ndu
}

// ClearMetadata clears the value of the "metadata" field.
func (ndu *NotificationDataUpdate) ClearMetadata() *NotificationDataUpdate {
	ndu.mutation.ClearMetadata()
	return ndu
}

// SetPluralCount sets the "plural_count" field.
func (ndu *NotificationDataUpdate) SetPluralCount(i int64) *NotificationDataUpdate {
	ndu.mutation.ResetPluralCount()
	ndu.mutation.SetPluralCount(i)
	return ndu
}

// SetNillablePluralCount sets the "plural_count" field if the given value is not nil.
func (ndu *NotificationDataUpdate) SetNillablePluralCount(i *int64) *NotificationDataUpdate {
	if i != nil {
		ndu.SetPluralCount(*i)
	}
	return ndu
}

// AddPluralCount adds i to the "plural_count" field.
func (ndu *NotificationDataUpdate) AddPluralCount(i int64) *NotificationDataUpdate {
	ndu.mutation.AddPluralCount(i)
	return ndu
}

// ClearPluralCount clears the value of the "plural_count" field.
func (ndu *NotificationDataUpdate) ClearPluralCount() *NotificationDataUpdate {
	ndu.mutation.ClearPluralCount()
	return ndu
}

// SetNotificationID sets the "notification" edge to the Notification entity by ID.
func (ndu *NotificationDataUpdate) SetNotificationID(id int64) *NotificationDataUpdate {
	ndu.mutation.SetNotificationID(id)
	return ndu
}

// SetNillableNotificationID sets the "notification" edge to the Notification entity by ID if the given value is not nil.
func (ndu *NotificationDataUpdate) SetNillableNotificationID(id *int64) *NotificationDataUpdate {
	if id != nil {
		ndu = ndu.SetNotificationID(*id)
	}
	return ndu
}

// SetNotification sets the "notification" edge to the Notification entity.
func (ndu *NotificationDataUpdate) SetNotification(n *Notification) *NotificationDataUpdate {
	return ndu.SetNotificationID(n.ID)
}

// Mutation returns the NotificationDataMutation object of the builder.
func (ndu *NotificationDataUpdate) Mutation() *NotificationDataMutation {
	return ndu.mutation
}

// ClearNotification clears the "notification" edge to the Notification entity.
func (ndu *NotificationDataUpdate) ClearNotification() *NotificationDataUpdate {
	ndu.mutation.ClearNotification()
	return ndu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ndu *NotificationDataUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ndu.sqlSave, ndu.mutation, ndu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ndu *NotificationDataUpdate) SaveX(ctx context.Context) int {
	affected, err := ndu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ndu *NotificationDataUpdate) Exec(ctx context.Context) error {
	_, err := ndu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ndu *NotificationDataUpdate) ExecX(ctx context.Context) {
	if err := ndu.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (ndu *NotificationDataUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *NotificationDataUpdate {
	ndu.modifiers = append(ndu.modifiers, modifiers...)
	return ndu
}

func (ndu *NotificationDataUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(notificationdata.Table, notificationdata.Columns, sqlgraph.NewFieldSpec(notificationdata.FieldID, field.TypeInt64))
	if ps := ndu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ndu.mutation.GetType(); ok {
		_spec.SetField(notificationdata.FieldType, field.TypeString, value)
	}
	if ndu.mutation.TypeCleared() {
		_spec.ClearField(notificationdata.FieldType, field.TypeString)
	}
	if value, ok := ndu.mutation.Event(); ok {
		_spec.SetField(notificationdata.FieldEvent, field.TypeString, value)
	}
	if ndu.mutation.EventCleared() {
		_spec.ClearField(notificationdata.FieldEvent, field.TypeString)
	}
	if value, ok := ndu.mutation.Member(); ok {
		_spec.SetField(notificationdata.FieldMember, field.TypeString, value)
	}
	if ndu.mutation.MemberCleared() {
		_spec.ClearField(notificationdata.FieldMember, field.TypeString)
	}
	if value, ok := ndu.mutation.Chat(); ok {
		_spec.SetField(notificationdata.FieldChat, field.TypeString, value)
	}
	if ndu.mutation.ChatCleared() {
		_spec.ClearField(notificationdata.FieldChat, field.TypeString)
	}
	if value, ok := ndu.mutation.Message(); ok {
		_spec.SetField(notificationdata.FieldMessage, field.TypeString, value)
	}
	if ndu.mutation.MessageCleared() {
		_spec.ClearField(notificationdata.FieldMessage, field.TypeString)
	}
	if value, ok := ndu.mutation.Contact(); ok {
		_spec.SetField(notificationdata.FieldContact, field.TypeString, value)
	}
	if ndu.mutation.ContactCleared() {
		_spec.ClearField(notificationdata.FieldContact, field.TypeString)
	}
	if value, ok := ndu.mutation.Task(); ok {
		_spec.SetField(notificationdata.FieldTask, field.TypeString, value)
	}
	if ndu.mutation.TaskCleared() {
		_spec.ClearField(notificationdata.FieldTask, field.TypeString)
	}
	if value, ok := ndu.mutation.Project(); ok {
		_spec.SetField(notificationdata.FieldProject, field.TypeString, value)
	}
	if ndu.mutation.ProjectCleared() {
		_spec.ClearField(notificationdata.FieldProject, field.TypeString)
	}
	if value, ok := ndu.mutation.User(); ok {
		_spec.SetField(notificationdata.FieldUser, field.TypeString, value)
	}
	if ndu.mutation.UserCleared() {
		_spec.ClearField(notificationdata.FieldUser, field.TypeString)
	}
	if value, ok := ndu.mutation.TargetUserID(); ok {
		_spec.SetField(notificationdata.FieldTargetUserID, field.TypeInt64, value)
	}
	if value, ok := ndu.mutation.AddedTargetUserID(); ok {
		_spec.AddField(notificationdata.FieldTargetUserID, field.TypeInt64, value)
	}
	if ndu.mutation.TargetUserIDCleared() {
		_spec.ClearField(notificationdata.FieldTargetUserID, field.TypeInt64)
	}
	if value, ok := ndu.mutation.Metadata(); ok {
		_spec.SetField(notificationdata.FieldMetadata, field.TypeString, value)
	}
	if ndu.mutation.MetadataCleared() {
		_spec.ClearField(notificationdata.FieldMetadata, field.TypeString)
	}
	if value, ok := ndu.mutation.PluralCount(); ok {
		_spec.SetField(notificationdata.FieldPluralCount, field.TypeInt64, value)
	}
	if value, ok := ndu.mutation.AddedPluralCount(); ok {
		_spec.AddField(notificationdata.FieldPluralCount, field.TypeInt64, value)
	}
	if ndu.mutation.PluralCountCleared() {
		_spec.ClearField(notificationdata.FieldPluralCount, field.TypeInt64)
	}
	if ndu.mutation.NotificationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   notificationdata.NotificationTable,
			Columns: []string{notificationdata.NotificationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ndu.mutation.NotificationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   notificationdata.NotificationTable,
			Columns: []string{notificationdata.NotificationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(ndu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, ndu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationdata.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ndu.mutation.done = true
	return n, nil
}

// NotificationDataUpdateOne is the builder for updating a single NotificationData entity.
type NotificationDataUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *NotificationDataMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetType sets the "type" field.
func (nduo *NotificationDataUpdateOne) SetType(s string) *NotificationDataUpdateOne {
	nduo.mutation.SetType(s)
	return nduo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (nduo *NotificationDataUpdateOne) SetNillableType(s *string) *NotificationDataUpdateOne {
	if s != nil {
		nduo.SetType(*s)
	}
	return nduo
}

// ClearType clears the value of the "type" field.
func (nduo *NotificationDataUpdateOne) ClearType() *NotificationDataUpdateOne {
	nduo.mutation.ClearType()
	return nduo
}

// SetEvent sets the "event" field.
func (nduo *NotificationDataUpdateOne) SetEvent(s string) *NotificationDataUpdateOne {
	nduo.mutation.SetEvent(s)
	return nduo
}

// SetNillableEvent sets the "event" field if the given value is not nil.
func (nduo *NotificationDataUpdateOne) SetNillableEvent(s *string) *NotificationDataUpdateOne {
	if s != nil {
		nduo.SetEvent(*s)
	}
	return nduo
}

// ClearEvent clears the value of the "event" field.
func (nduo *NotificationDataUpdateOne) ClearEvent() *NotificationDataUpdateOne {
	nduo.mutation.ClearEvent()
	return nduo
}

// SetMember sets the "member" field.
func (nduo *NotificationDataUpdateOne) SetMember(s string) *NotificationDataUpdateOne {
	nduo.mutation.SetMember(s)
	return nduo
}

// SetNillableMember sets the "member" field if the given value is not nil.
func (nduo *NotificationDataUpdateOne) SetNillableMember(s *string) *NotificationDataUpdateOne {
	if s != nil {
		nduo.SetMember(*s)
	}
	return nduo
}

// ClearMember clears the value of the "member" field.
func (nduo *NotificationDataUpdateOne) ClearMember() *NotificationDataUpdateOne {
	nduo.mutation.ClearMember()
	return nduo
}

// SetChat sets the "chat" field.
func (nduo *NotificationDataUpdateOne) SetChat(s string) *NotificationDataUpdateOne {
	nduo.mutation.SetChat(s)
	return nduo
}

// SetNillableChat sets the "chat" field if the given value is not nil.
func (nduo *NotificationDataUpdateOne) SetNillableChat(s *string) *NotificationDataUpdateOne {
	if s != nil {
		nduo.SetChat(*s)
	}
	return nduo
}

// ClearChat clears the value of the "chat" field.
func (nduo *NotificationDataUpdateOne) ClearChat() *NotificationDataUpdateOne {
	nduo.mutation.ClearChat()
	return nduo
}

// SetMessage sets the "message" field.
func (nduo *NotificationDataUpdateOne) SetMessage(s string) *NotificationDataUpdateOne {
	nduo.mutation.SetMessage(s)
	return nduo
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (nduo *NotificationDataUpdateOne) SetNillableMessage(s *string) *NotificationDataUpdateOne {
	if s != nil {
		nduo.SetMessage(*s)
	}
	return nduo
}

// ClearMessage clears the value of the "message" field.
func (nduo *NotificationDataUpdateOne) ClearMessage() *NotificationDataUpdateOne {
	nduo.mutation.ClearMessage()
	return nduo
}

// SetContact sets the "contact" field.
func (nduo *NotificationDataUpdateOne) SetContact(s string) *NotificationDataUpdateOne {
	nduo.mutation.SetContact(s)
	return nduo
}

// SetNillableContact sets the "contact" field if the given value is not nil.
func (nduo *NotificationDataUpdateOne) SetNillableContact(s *string) *NotificationDataUpdateOne {
	if s != nil {
		nduo.SetContact(*s)
	}
	return nduo
}

// ClearContact clears the value of the "contact" field.
func (nduo *NotificationDataUpdateOne) ClearContact() *NotificationDataUpdateOne {
	nduo.mutation.ClearContact()
	return nduo
}

// SetTask sets the "task" field.
func (nduo *NotificationDataUpdateOne) SetTask(s string) *NotificationDataUpdateOne {
	nduo.mutation.SetTask(s)
	return nduo
}

// SetNillableTask sets the "task" field if the given value is not nil.
func (nduo *NotificationDataUpdateOne) SetNillableTask(s *string) *NotificationDataUpdateOne {
	if s != nil {
		nduo.SetTask(*s)
	}
	return nduo
}

// ClearTask clears the value of the "task" field.
func (nduo *NotificationDataUpdateOne) ClearTask() *NotificationDataUpdateOne {
	nduo.mutation.ClearTask()
	return nduo
}

// SetProject sets the "project" field.
func (nduo *NotificationDataUpdateOne) SetProject(s string) *NotificationDataUpdateOne {
	nduo.mutation.SetProject(s)
	return nduo
}

// SetNillableProject sets the "project" field if the given value is not nil.
func (nduo *NotificationDataUpdateOne) SetNillableProject(s *string) *NotificationDataUpdateOne {
	if s != nil {
		nduo.SetProject(*s)
	}
	return nduo
}

// ClearProject clears the value of the "project" field.
func (nduo *NotificationDataUpdateOne) ClearProject() *NotificationDataUpdateOne {
	nduo.mutation.ClearProject()
	return nduo
}

// SetUser sets the "user" field.
func (nduo *NotificationDataUpdateOne) SetUser(s string) *NotificationDataUpdateOne {
	nduo.mutation.SetUser(s)
	return nduo
}

// SetNillableUser sets the "user" field if the given value is not nil.
func (nduo *NotificationDataUpdateOne) SetNillableUser(s *string) *NotificationDataUpdateOne {
	if s != nil {
		nduo.SetUser(*s)
	}
	return nduo
}

// ClearUser clears the value of the "user" field.
func (nduo *NotificationDataUpdateOne) ClearUser() *NotificationDataUpdateOne {
	nduo.mutation.ClearUser()
	return nduo
}

// SetTargetUserID sets the "target_user_id" field.
func (nduo *NotificationDataUpdateOne) SetTargetUserID(i int64) *NotificationDataUpdateOne {
	nduo.mutation.ResetTargetUserID()
	nduo.mutation.SetTargetUserID(i)
	return nduo
}

// SetNillableTargetUserID sets the "target_user_id" field if the given value is not nil.
func (nduo *NotificationDataUpdateOne) SetNillableTargetUserID(i *int64) *NotificationDataUpdateOne {
	if i != nil {
		nduo.SetTargetUserID(*i)
	}
	return nduo
}

// AddTargetUserID adds i to the "target_user_id" field.
func (nduo *NotificationDataUpdateOne) AddTargetUserID(i int64) *NotificationDataUpdateOne {
	nduo.mutation.AddTargetUserID(i)
	return nduo
}

// ClearTargetUserID clears the value of the "target_user_id" field.
func (nduo *NotificationDataUpdateOne) ClearTargetUserID() *NotificationDataUpdateOne {
	nduo.mutation.ClearTargetUserID()
	return nduo
}

// SetMetadata sets the "metadata" field.
func (nduo *NotificationDataUpdateOne) SetMetadata(s string) *NotificationDataUpdateOne {
	nduo.mutation.SetMetadata(s)
	return nduo
}

// SetNillableMetadata sets the "metadata" field if the given value is not nil.
func (nduo *NotificationDataUpdateOne) SetNillableMetadata(s *string) *NotificationDataUpdateOne {
	if s != nil {
		nduo.SetMetadata(*s)
	}
	return nduo
}

// ClearMetadata clears the value of the "metadata" field.
func (nduo *NotificationDataUpdateOne) ClearMetadata() *NotificationDataUpdateOne {
	nduo.mutation.ClearMetadata()
	return nduo
}

// SetPluralCount sets the "plural_count" field.
func (nduo *NotificationDataUpdateOne) SetPluralCount(i int64) *NotificationDataUpdateOne {
	nduo.mutation.ResetPluralCount()
	nduo.mutation.SetPluralCount(i)
	return nduo
}

// SetNillablePluralCount sets the "plural_count" field if the given value is not nil.
func (nduo *NotificationDataUpdateOne) SetNillablePluralCount(i *int64) *NotificationDataUpdateOne {
	if i != nil {
		nduo.SetPluralCount(*i)
	}
	return nduo
}

// AddPluralCount adds i to the "plural_count" field.
func (nduo *NotificationDataUpdateOne) AddPluralCount(i int64) *NotificationDataUpdateOne {
	nduo.mutation.AddPluralCount(i)
	return nduo
}

// ClearPluralCount clears the value of the "plural_count" field.
func (nduo *NotificationDataUpdateOne) ClearPluralCount() *NotificationDataUpdateOne {
	nduo.mutation.ClearPluralCount()
	return nduo
}

// SetNotificationID sets the "notification" edge to the Notification entity by ID.
func (nduo *NotificationDataUpdateOne) SetNotificationID(id int64) *NotificationDataUpdateOne {
	nduo.mutation.SetNotificationID(id)
	return nduo
}

// SetNillableNotificationID sets the "notification" edge to the Notification entity by ID if the given value is not nil.
func (nduo *NotificationDataUpdateOne) SetNillableNotificationID(id *int64) *NotificationDataUpdateOne {
	if id != nil {
		nduo = nduo.SetNotificationID(*id)
	}
	return nduo
}

// SetNotification sets the "notification" edge to the Notification entity.
func (nduo *NotificationDataUpdateOne) SetNotification(n *Notification) *NotificationDataUpdateOne {
	return nduo.SetNotificationID(n.ID)
}

// Mutation returns the NotificationDataMutation object of the builder.
func (nduo *NotificationDataUpdateOne) Mutation() *NotificationDataMutation {
	return nduo.mutation
}

// ClearNotification clears the "notification" edge to the Notification entity.
func (nduo *NotificationDataUpdateOne) ClearNotification() *NotificationDataUpdateOne {
	nduo.mutation.ClearNotification()
	return nduo
}

// Where appends a list predicates to the NotificationDataUpdate builder.
func (nduo *NotificationDataUpdateOne) Where(ps ...predicate.NotificationData) *NotificationDataUpdateOne {
	nduo.mutation.Where(ps...)
	return nduo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (nduo *NotificationDataUpdateOne) Select(field string, fields ...string) *NotificationDataUpdateOne {
	nduo.fields = append([]string{field}, fields...)
	return nduo
}

// Save executes the query and returns the updated NotificationData entity.
func (nduo *NotificationDataUpdateOne) Save(ctx context.Context) (*NotificationData, error) {
	return withHooks(ctx, nduo.sqlSave, nduo.mutation, nduo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (nduo *NotificationDataUpdateOne) SaveX(ctx context.Context) *NotificationData {
	node, err := nduo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (nduo *NotificationDataUpdateOne) Exec(ctx context.Context) error {
	_, err := nduo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nduo *NotificationDataUpdateOne) ExecX(ctx context.Context) {
	if err := nduo.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (nduo *NotificationDataUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *NotificationDataUpdateOne {
	nduo.modifiers = append(nduo.modifiers, modifiers...)
	return nduo
}

func (nduo *NotificationDataUpdateOne) sqlSave(ctx context.Context) (_node *NotificationData, err error) {
	_spec := sqlgraph.NewUpdateSpec(notificationdata.Table, notificationdata.Columns, sqlgraph.NewFieldSpec(notificationdata.FieldID, field.TypeInt64))
	id, ok := nduo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NotificationData.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := nduo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notificationdata.FieldID)
		for _, f := range fields {
			if !notificationdata.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notificationdata.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := nduo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := nduo.mutation.GetType(); ok {
		_spec.SetField(notificationdata.FieldType, field.TypeString, value)
	}
	if nduo.mutation.TypeCleared() {
		_spec.ClearField(notificationdata.FieldType, field.TypeString)
	}
	if value, ok := nduo.mutation.Event(); ok {
		_spec.SetField(notificationdata.FieldEvent, field.TypeString, value)
	}
	if nduo.mutation.EventCleared() {
		_spec.ClearField(notificationdata.FieldEvent, field.TypeString)
	}
	if value, ok := nduo.mutation.Member(); ok {
		_spec.SetField(notificationdata.FieldMember, field.TypeString, value)
	}
	if nduo.mutation.MemberCleared() {
		_spec.ClearField(notificationdata.FieldMember, field.TypeString)
	}
	if value, ok := nduo.mutation.Chat(); ok {
		_spec.SetField(notificationdata.FieldChat, field.TypeString, value)
	}
	if nduo.mutation.ChatCleared() {
		_spec.ClearField(notificationdata.FieldChat, field.TypeString)
	}
	if value, ok := nduo.mutation.Message(); ok {
		_spec.SetField(notificationdata.FieldMessage, field.TypeString, value)
	}
	if nduo.mutation.MessageCleared() {
		_spec.ClearField(notificationdata.FieldMessage, field.TypeString)
	}
	if value, ok := nduo.mutation.Contact(); ok {
		_spec.SetField(notificationdata.FieldContact, field.TypeString, value)
	}
	if nduo.mutation.ContactCleared() {
		_spec.ClearField(notificationdata.FieldContact, field.TypeString)
	}
	if value, ok := nduo.mutation.Task(); ok {
		_spec.SetField(notificationdata.FieldTask, field.TypeString, value)
	}
	if nduo.mutation.TaskCleared() {
		_spec.ClearField(notificationdata.FieldTask, field.TypeString)
	}
	if value, ok := nduo.mutation.Project(); ok {
		_spec.SetField(notificationdata.FieldProject, field.TypeString, value)
	}
	if nduo.mutation.ProjectCleared() {
		_spec.ClearField(notificationdata.FieldProject, field.TypeString)
	}
	if value, ok := nduo.mutation.User(); ok {
		_spec.SetField(notificationdata.FieldUser, field.TypeString, value)
	}
	if nduo.mutation.UserCleared() {
		_spec.ClearField(notificationdata.FieldUser, field.TypeString)
	}
	if value, ok := nduo.mutation.TargetUserID(); ok {
		_spec.SetField(notificationdata.FieldTargetUserID, field.TypeInt64, value)
	}
	if value, ok := nduo.mutation.AddedTargetUserID(); ok {
		_spec.AddField(notificationdata.FieldTargetUserID, field.TypeInt64, value)
	}
	if nduo.mutation.TargetUserIDCleared() {
		_spec.ClearField(notificationdata.FieldTargetUserID, field.TypeInt64)
	}
	if value, ok := nduo.mutation.Metadata(); ok {
		_spec.SetField(notificationdata.FieldMetadata, field.TypeString, value)
	}
	if nduo.mutation.MetadataCleared() {
		_spec.ClearField(notificationdata.FieldMetadata, field.TypeString)
	}
	if value, ok := nduo.mutation.PluralCount(); ok {
		_spec.SetField(notificationdata.FieldPluralCount, field.TypeInt64, value)
	}
	if value, ok := nduo.mutation.AddedPluralCount(); ok {
		_spec.AddField(notificationdata.FieldPluralCount, field.TypeInt64, value)
	}
	if nduo.mutation.PluralCountCleared() {
		_spec.ClearField(notificationdata.FieldPluralCount, field.TypeInt64)
	}
	if nduo.mutation.NotificationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   notificationdata.NotificationTable,
			Columns: []string{notificationdata.NotificationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nduo.mutation.NotificationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   notificationdata.NotificationTable,
			Columns: []string{notificationdata.NotificationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(nduo.modifiers...)
	_node = &NotificationData{config: nduo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, nduo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationdata.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	nduo.mutation.done = true
	return _node, nil
}
