// Code generated by ent, DO NOT EDIT.

package ent

import (
	"notifications/ent/device"
	"notifications/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	deviceFields := schema.Device{}.Fields()
	_ = deviceFields
	// deviceDescUserID is the schema descriptor for user_id field.
	deviceDescUserID := deviceFields[0].Descriptor()
	// device.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	device.UserIDValidator = deviceDescUserID.Validators[0].(func(int64) error)
	// deviceDescCreatedAt is the schema descriptor for created_at field.
	deviceDescCreatedAt := deviceFields[2].Descriptor()
	// device.DefaultCreatedAt holds the default value on creation for the created_at field.
	device.DefaultCreatedAt = deviceDescCreatedAt.Default.(func() time.Time)
}
