-- Create "notifications" table
CREATE TABLE "notifications" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "type" character varying NOT NULL DEFAULT 'COMMON', "title" character varying NOT NULL, "text" character varying NOT NULL, "event_id" bigint NULL, "contact_id" bigint NULL, "created_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
