-- Create "devices" table
CREATE TABLE "devices" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "token" character varying NOT NULL, "created_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create index "devices_token_key" to table: "devices"
CREATE UNIQUE INDEX "devices_token_key" ON "devices" ("token");
