-- Modify "devices" table
ALTER TABLE "devices" ADD COLUMN "language" character varying NULL DEFAULT 'en';
-- Create "notification_data" table
CREATE TABLE "notification_data" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "type" character varying NULL, "event" character varying NULL, "member" character varying NULL, "chat" character varying NULL, "message" character varying NULL, "contact" character varying NULL, "task" character varying NULL, "metadata" character varying NULL, "plural_count" bigint NULL, PRIMARY KEY ("id"));
-- Modify "notifications" table
ALTER TABLE "notifications" ADD COLUMN "notification_data_id" bigint NULL, ADD CONSTRAINT "notifications_notification_data_notification" FOREIGN KEY ("notification_data_id") REFERENCES "notification_data" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Create index "notifications_notification_data_id_key" to table: "notifications"
CREATE UNIQUE INDEX "notifications_notification_data_id_key" ON "notifications" ("notification_data_id");
